### ISSUE TITLE
How to change the color of a button when the form is valid before clicking on the button

### ISSUE THREAD

**Issue by jbt-cii** [joanpablo/reactive_forms#111]
Hello,

I try to follow explanations detailled here:
[https://github.com/joanpablo/reactive_forms#enabledisable-submit-button](https://github.com/joanpablo/reactive_forms#enabledisable-submit-button)

I success to disable the button but I don't understand something.
Before clicking on the button how can I change the color of a button when the form is valid?
I think I need a listener or something like that, is it corect?

**Comment by DevNico** [comment]
You said you successfully disabled the button already therefore just set the buttonStyle to something like:
```dart
style: ButtonStyle(
  backgroundColor: MaterialStateProperty.resolveWith((state) {
    if (state.contains(MaterialState.disabled)) return Colors.black54;
    return Colors.black;
  }),
),
```

**Comment by jbt-cii** [comment]
Thank you.
It works now!

I had some 'context' problems.
I use the same widget for all buttons in my application.
But I had problems with buttons not used with a form (buttons simply in order to navigate between 2 pages).
=> form was not known i these cases.

And also I had problems managing colors.
I got this error:
```
'package:flutter/src/painting/borders.dart': Failed assertion: line 69 pos 15: 'color != null': is not true.
```

I had this error even with your solution.
Finally it seems it was because of the usage of this type of code:
Theme.of(context).primaryColor
Using directly "Colors.black" for instance (or a global variable... I declared a specific class named "AppColors" with static const) made the job!

And also I had a problem with the "shape" property.
For instance I used this for the "background" property:
```
            child: TextButton(
              style: ButtonStyle(
                backgroundColor: MaterialStateProperty.resolveWith((state) {
                  if (state.contains(MaterialState.disabled) && form != null && form.valid) return Colors.grey.shade400;
                  return this._backgroundColor;
                }),
```

Before trying to manage the colors for the button I used this code for the "shape" property (which worked):
```
            child: TextButton(
              style: ButtonStyle(
                ...
                shape: MaterialStateProperty.all(
                  RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(this._radius),
                    side: BorderSide(
                      color: this._backgroundColor,
                    ),
                  ),
                ),
              ),
              ...
            ),
            ...
```

But trying to manage the colors for the button with the "shape" property I could not use "MaterialStateProperty.resolveWith((state) {}) method just for the "color" property of the "BorderSide" widget (inside the "RoundedRectangleBorder" widget).
So I could not do something like that:
```
            child: TextButton(
              style: ButtonStyle(
                ...
                shape: MaterialStateProperty.all(
                  RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(this._radius),
                    side: BorderSide(
                      color: MaterialStateProperty.resolveWith((state) {
                        if (state.contains(MaterialState.disabled) && form != null && form.valid) {
                          return AppColors.ACCENT_COLOR.withAlpha(90);
                        } else {
                          return this._backgroundColor;
                        }
                      }),
                    ),
                  ),
                ),
              ),
              ...
            ),
            ...
```

Finally I declared the "shape" property like that:
```
            child: TextButton(
              style: ButtonStyle(
                ...
                shape: MaterialStateProperty.resolveWith((state) {
                  if (state.contains(MaterialState.disabled) && form != null && form.valid) {
                    return RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(this._radius),
                      side: BorderSide(
                        color: AppColors.ACCENT_COLOR.withAlpha(90),
                      ),
                    );
                  } else {
                    return RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(this._radius),
                      side: BorderSide(
                        color: this._backgroundColor,
                      ),
                    );
                  }
                }),
```

Thanks for your help! :-)
