### ISSUE TITLE
Multiple Listeners

### ISSUE THREAD

**Issue by JulianSwales** [joanpablo/reactive_forms#113]
This is more a question then an issue.. 
I'm looking at this solution to replace flutter_form_bloc which is no longer being supported. That solution had fieldname.OnValueChanged which I used because I have three fields linked such that the value change on each affected the others and the result of all three is sent to a server. 
A date field, number of hours, and start time. Changing the date field updated the available start times, which changes based on the day of the week, changing the hours updated the available start times and once all values were set then we checked the server for availability. All of this queries a backend server for the data.
I'm not sure if this library can do something like that? I was going to use Validators at first, from reading, then looked at the reactivevaluelistenablebuilder, but didn't see it hooking multiple fields. I'm fairly new to all this so just working my way through learning. 
I also see bloc mentioned in the documentation, but was wondering if there was an example of it being used with this library somewhere? 
Any thoughts on this being viable option or pointers would be greatly appreciated. Thanks.

**Comment by joanpablo** [comment]
Hi @JulianSwales,

Thanks for the issue, I will try to explain the different options you have to archive what you want. 

The widget **ReactiveValueListenableBuilder** actually listens for changes of the value of a specific control. This widget is best suited for cases in which you want to update the widget's tree (that means repaint or rebuild the UI) based on a value of a control. For example, you want to Show/Hide a child widget depending on a value of a control.

All Controls (FormControl, FormGroup and FormArray) also expose the Stream **valueChanges**. You can subscribe to this Stream and listen form changes in the value of a *control*. For Example:

Given the definition of a FormGroup:
```dart
final form = FormGroup({
   'date': FormControl<DateTime>(),
   'time': FormControl<TimeOfDay>(),
});
```

You can start listening for changes:

```dart
final date = form.control('date') as FormControl<DateTime>;
date.valueChanges.listen((DateTime value) {
   print("date has changed");
  // update the start times
});

final time = form.control('time') as FormControl<TimeOfDay>;
time.valueChanges.listen((TimeOfDay value) {
   print("time has changed");
  // update the hours
});
```

I always suggest to use a State management library like Provider (it can be any of the others). The previous logic should be placed in the State management controller/bloc/viewmodel/etc.

```dart
class ExamSchedulerViewModel {
  final form = FormGroup({
    'date': FormControl<DateTime>(),
    'time': FormControl<TimeOfDay>(),
  });
  
  ExamSchedulerViewModel() {
    this.date.valueChanges.listen((DateTime value) { 
      print("date has changed");
      // update time
    });
    
    this.time.valueChanges.listen((TimeOfDay value) {
      print("time has changed");
      // update hours
    });
  }
  
  FormControl<DateTime> get date => this.form.control('date') as FormControl<DateTime>;
  
  FormControl<TimeOfDay> get time => this.form.control('time') as FormControl<TimeOfDay>; 
}
```

you can Provide the view model using any state management library and access it, then create a ReactiveForm and bind to the formGroup of the ViewModel.

If you need more help please don't hesitate to ask. I'm glad to help you.

**Comment by JulianSwales** [comment]
Hi @joanpablo 
Thank you so much for this. This valueChanges option will be helpful. I will take a closer look at that option. 
Do you know if there's an example of the state management binding to the formGroup of the ViewModel? 
As I said this is a learning experience and a challenging one. Flutter is fun, but it changes fast, and as I've discovered, sometimes libraries get left behind, as in the flutter_form_bloc one I was using. Hence my being here now. 
Thanks for any insights you can give.

**Comment by JulianSwales** [comment]
@joanpablo 
I'm making progress... However I have another question.. 
I have an async Validator defined at the Group level.. 

` final form = FormGroup(
    {
      'bookingInfo': FormGroup(
        {
          'bookingDate': FormControl<DateTime>(
            validators: [Validators.required],
          ),
          'numberOfHours':
              FormControl<String>(validators: [Validators.required]),
          'message': FormControl<String>(value: 'Test'),
        },
        asyncValidators: [getSimInfo],
      ),
      'customerInfo': FormGroup(
        {
          'email': FormControl<String>(
          ),
          'phone': FormControl(
            validators: [Validators.required],
          ),
        },
      )
    },
  );`

I have the following Widget:
`Expanded(
          child: ReactiveTextField(
                        formControlName: 'bookingInfo.message',
                        readOnly: true,
                ),
          )`

And here is the validator: 
`
Future<Map<String, dynamic>> getSimInfo(AbstractControl control) async {
  print('Function: getSimInfo');
  print('${control.value['bookingDate']}');
  print('${control.value['numberOfHours']}');
  control.value['message'] = "Updated Text";
  final error = {'msg': false};
  if (control.value['numberOfHours'] == '3') {
    return error;
  }
  return null;
}`

The line 

`control.value['message'] = 'Updated Text'; `

doesn't update the text in the widget.  This is just learning code, the actual async requests returns data, some of which will fill other fields ,so I'm trying to figure out how that will work..  I tried to mark the control as touched but that didn't work.  How should I update fields with data from an async validator? 

Thanks...

**Comment by JulianSwales** [comment]
Hi @joanpablo 
Thank you so much for your help.. Moving forward and I've even sorted out how to use a viewModel
I have a couple of questions.. 
I have the following form: 

```flutter
  final form = FormGroup(
    {
      'bookingInfo': FormGroup(
        {
          'bookingDate': FormControl<DateTime>(
            validators: [Validators.required],
          ),
          'numberOfHours': FormControl<String>(
            validators: [Validators.required],
          ),
          'startTime': FormControl<String>(
            validators: [
              Validators.required,
            ],
            //validators: [Validators.required, _updateHours],
            //asyncValidators: [availableTimes]
          ),
         'message': FormControl<String>(value: ''),
        },
        asyncValidators: [getSimInfo],
      ),
    },
  );
```

```flutter
Future<Map<String, dynamic>> getSimInfo(AbstractControl control) async {
  print('Function: getSimInfo');
  print('${control.value['bookingDate']}');
  print('${control.value['numberOfHours']}');
  final form = control as FormGroup;
  // set the value directly to the control
  form.control('message').value = 'Updated Text\nPart 2\nPart 3';

  // Setup Error Return
  final error = {'msg': false};
  if (control.value['numberOfHours'] == '3') {
    return error;
  }
  return null;
}```

However what I discovered is the async Validator runs after I update the message field, which made sense.  So I thought I'd move the message field out of this form group into its own like this: 

```flutter
  final form = FormGroup(
    {
      'bookingInfo': FormGroup(
        {
          'bookingDate': FormControl<DateTime>(
            validators: [Validators.required],
          ),
          'numberOfHours': FormControl<String>(
            validators: [Validators.required],
          ),
          'startTime': FormControl<String>(
            validators: [
              Validators.required,
            ],
            //validators: [Validators.required, _updateHours],
            //asyncValidators: [availableTimes]
          ),
        },
        asyncValidators: [getSimInfo],
      ),
      'msg': FormGroup({
        'message': FormControl<String>(value: ''),
      }),
   }
  );```

However from within the asyncValidator getSimInfo I can't see that form control msg.message to update it or is there a better way within reactive forms to do this process of updating a field with information from a validator?

I also found the ValidatorFunctions item in your documentation showing how to pass values down to a validator.  How would one do that with an asycValidator in the case where I'd like to do something like this: 

```asycValidators: [getSimInfo(passedValue,passedValue2)]```

Thank you for this package.. I can see it's potential.

**Comment by joanpablo** [comment]
Hi @JulianSwales,

Thanks for your kind words, and I'm glad that you see the potential of the library.

I have read your question, and I need to understand something about your code: Why you need the **message** control? Are you using the *message* control to personalize the Error Message? If that is the reason for using the *message*, then I can tell you that there are better ways to personalize and show error messages when using Reactive Forms.

Answer that question before I can continue. I will show you how to better customize messages.

**Comment by JulianSwales** [comment]
Hi @joanpablo 
Whilst this async validator you see currently does not do anything, what it will do is query a server based on the value of the three fields and returns data. There's two parts to the data returned. Whether there is an available option, if not the validator will return an error state to the form, as well as a message with available options available or, if there is an available option, it will return null as well as a message, so that the user can continue, with filling in the rest of the form. 
What I want is a "message" block below the first formgroup where I can put this response so that is visible as they fill in the rest of the form. 
So, top of form, date, time hours, check avail - formgroup
Return data on availabily and information
Show information in a "message" field whether it's a null or error async validator - formgroup
Then show email, phone name, etc, - formgroup
then once that is all valid a booking button. 

I had all this working utilizing the flutter_form_bloc package, but it's no longer supported and has stopped working for me.. So as with several others I see on here who've come from that package, I'm now wrapping my head around a new way to do the same thing, without shaking up the UI and my users to much. 

Hence this test project where I can figure out the reactive forms concepts before I rewrite the forms. 

Hope that helps. Thanks.

**Comment by joanpablo** [comment]
Hi @JulianSwales,

If you want to show the error message returned from the Server then I suggest you use a specific field within the controller/viewmodel/bloc/etc and not using a *control* from the FormGroup.

I don't recommend to change values of **controls** within a **validator**, because each time you change a value of a control then validators will try to validate the new value and you get trapped in an infinity loop (if you set a new value each time). 

Other possible solution is to **disable** the *message* **control**. A control that is *disabled* is not included in the FormGroup.value and does not trigger the validators.

**Comment by joanpablo** [comment]
Hi @JulianSwales,

How are going with this issue? Have you managed to solve the issue with my recommendations?

**Comment by JulianSwales** [comment]
Hi @joanpablo 

Yes, I'm slowly figuring out what I need to do. I'm going to use group status and bloc to manage the message flow. 

One more item about validators. 

I also found the ValidatorFunctions item in your documentation showing how to pass values down to a validator.  How would one do that with an asycValidator in the case where I'd like to do something like this: 

```asycValidators: [getSimInfo(passedValue,passedValue2)]```

Thank, Julian

**Comment by joanpablo** [comment]
Hi @JulianSwales,

You can pass values to **asyncValidators** the same way you do it with sync **validators**. Just create a function that returns an *AsyncValidatorFunction*

**Comment by JulianSwales** [comment]
Hi @joanpablo 
Ahh, ok. I'll take a look at that. 
I'm good if you close this issue now. I have some playing to do but I'll open a new issue if I have more questions. I want to thank you for your great package and time helping me through this. 
One of the things I really liked about the form_bloc package was it came with this site: 
https://giancarlocode.github.io/form_bloc/#/

Which had nice live scenerios I could learn from. Just an idea to think about. 
Thanks.

**Comment by joanpablo** [comment]
Thanks @JulianSwales,

About the site with examples from form_bloc, @vasilich6107 is trying to do the same, and in the examples folder of the package, we have an implementation of common scenarios.
