### ISSUE TITLE
How to add dynamic two field compare validation

### ISSUE THREAD

**Issue by AnanthGopal** [joanpablo/reactive_forms#115]
How to add dynamic two field compare validation like below

this.form.validators.addAll(
            {
              Validators.mustMatch('password', 'confirmPassword'),
            },
          )

**Comment by joanpablo** [comment]
Hi @AnanthGopal,

Thanks for your issue.

Could you please give us a complete use case of what you are trying to achieve? Maybe with a better example, We can help you better. 

Best regards

**Comment by AnanthGopal** [comment]
Requirement: For example, i have a screen like the Reset password screen, Initially I will show the one textbox(Get emailed from the user) and generate the OTP button.

The user enters a valid email id then click generate OTP button, after that we send OTP mail and we will show 3 more textboxes like OTP textbox and password textbox and confirm textbox 

here I need to add validation dynamically like compare password textbox and confirm textbox values.

Below I shared the code

`final form = FormGroup(
    {
      'email': FormControl<String>(
        validators: [
          Validators.required,
          Validators.email,
        ],
        asyncValidators: [_uniqueEmail],
        asyncValidatorsDebounceTime: 1000,
      ),
      'isSubmittedGeneratedOtp': FormControl<bool>(value: false),
    },
  );
 onSubmitting(BuildContext context) async {
if (this.form.valid) {
      if (this.form.value['isSubmittedGeneratedOtp'] == false) {
       this.form.control('isSubmittedGeneratedOtp').value = true;
       this.form.addAll(
            {
              'oneTimePassword': FormControl<String>(
                validators: [
                  Validators.required,
                ],
              ),
              'password': FormControl<String>(
                validators: [
                  Validators.required,
                ],
              ),
              'confirmPassword': FormControl<String>(
                validators: [
                  Validators.required,
                ],
              ),
            },
          );
       }
 }
}`

Code Explanation form  variable has two fields one is "email" another one is "isSubmittedGeneratedOtp" and we set isSubmittedGeneratedOtp as false

When the user click submits button we will isSubmittedGeneratedOtp is true and we add three extra fields by using this.form.addAll() method

Now I need to add a password and confirmpassword compare validation 

i try to add below code dynamically , but I can't add it I got error
 `
validators: [
  _mustMatch('password', 'passwordConfirmation')
]);
`

**Comment by joanpablo** [comment]
Hi @AnanthGopal,

If you allow me, I will advise you to enable/disable the controls. When controls are disabled, they are not included in form validation checks or in the value of the FormGroup. You can also hide/show controls based on the value of the **enabled/disabled** properties of the control.

For example, all you need to do is to create a FormGroup with all your controls:

```dart
final form = FormGroup({
   'email': FormControl<String>(validators: [Validators.required]),
   'oneTimePassword': FormControl<String>(disabled: true, validators: [Validators.required]),
   'password': FormControl<String>(disabled: true, validators: [Validators.required]),
   'confirmPassword': FormControl<String>(disabled: true, validators: [Validators.required]),
});

FormControl<String> get oneTimePassword => this.form.control('oneTimePassword') as FormControl<String>;

FormControl<String> get password => this.form.control('oneTimePassword') as FormControl<String>;

FormControl<String> get confirmPassword => this.form.control('oneTimePassword') as FormControl<String>;
``` 

And when you receive the X event (your business logic) you just simple enable the controls you want to validate:

```dart
// ...
//This means the control is included in validation checks and the aggregate
// value of its parent. Its status recalculates based on its value and its validators.
this.oneTimePassword.markAsEnabled();
this.password.markAsEnabled();
this.confirmPassword.markAsEnabled();
// ...
```

**Comment by AnanthGopal** [comment]
thank you i check it, it is working well. @joanpablo , your guys doing great work

**Comment by joanpablo** [comment]
Thanks @AnanthGopal :)
