### ISSUE TITLE
Multiple validators

### ISSUE THREAD

**Issue by julek-kal** [joanpablo/reactive_forms#116]
Hi, I want to achieve something like this bellow.
![image](https://user-images.githubusercontent.com/35259453/111934693-36a4f180-8ac2-11eb-9058-46d536fefc20.png)
So I need an access to status of all validators in FormControl. 
I have tried with `control.errors` but if I have [required, pattern, pattern] validators, getting errors in sequence. It would be perfect, if I get a Map of validators and it's statuses.
It is possible to get this?

**Comment by joanpablo** [comment]
Hi @julek-kal,

Thanks for using **Reactive Forms**.

I'm trying to understand your issue, but I'm not sure what is not working for you.

Given the form group definition:
```dart
final form = FormGroup({
   'email': FormControl(validators: [Validators.email, Validators.required]),
   'password': FormControl(validators: [Validators.minLenght(1)])
});
```

The follow expression:
```dart
print(form.control('email').errors);
```
will print all the errors of the *email* control.

and
```dart
print(form.errors);
```
will print all the errors of the complete form group.

The only errors that will not trigger ra the async validators only if there is **at least one invalid sync validator**. You can take a look at the documentation of [Asynchronous Validators](https://github.com/joanpablo/reactive_forms#asynchronous-validators-sunglasses)

**Comment by julek-kal** [comment]
So I have 3 validators, first is `required`, and two different `pattern` validator.

I can't find a method to display error from two pattern validators at once.
Always at first I'm getting an error from **CustomValidators.minOneUpperLetter**, only then **CustomValidators.minOneDigitOrSpecialCharacter** returns an error.
Now I'm started to thinking that is issue of bad RegExp, but I'm not sure.


https://user-images.githubusercontent.com/35259453/111998838-b364b980-8b1c-11eb-8d6a-3550d16f0ffd.mov



**FormGroup**
```dart
final form = FormGroup({
    EMAIL: FormControl<String>(
      validators: [
        Validators.email,
      ],
    ),
    PASSWORD: FormControl<String>(
      validators: [
        Validators.required,
        Validators.minLength(8),
        Validators.pattern(CustomValidators.minOneDigitOrSpecialCharacter),
        Validators.pattern(CustomValidators.minOneUpperLetter),
      ],
    ),
    PASSWORD_CONFIRMAITION: FormControl<String>(),
  }, validators: [
    Validators.mustMatch(PASSWORD, PASSWORD_CONFIRMAITION)
  ]);
```

**Validators**
```dart
class CustomValidators {
  static const minOneUpperLetter = '[A-Z]';
  static const minOneDigitOrSpecialCharacter = r'(?=.*[!"#$%&()*+,-./:;<=>?@[\]^_`{|}~0-9])';
}
```

**UI**
```dart
Column(
            children: [
              ReactiveTextField(
                formControl: _bloc.email,
              ),
              ReactiveValueListenableBuilder(
                formControl: _bloc.password,
                builder: (context, control, child) => Column(
                  children: [
                    child,
                    for (var status in control.errors.values) ...[
                      Text(status.toString()),
                      const SizedBox(
                        height: 20,
                      )
                    ]
                  ],
                ),
                child: ReactiveTextField(
                  formControl: _bloc.password,
                  showErrors: (control) => control.invalid,
                ),
              ),
              ReactiveTextField(
                formControl: _bloc.passwordConfirmation,
              )
            ],
          ),
```

P.S. **Reactive Forms** looks like a very great job. I have in plans migrate to this from form_bloc, because it's not maintained anymore. But it's quite time consuming, because I have a dozen of a quite big forms.
I have a hope that you don't abandon a **Reactive Forms** 😉

**Comment by joanpablo** [comment]
Hi @julek-kal,

Thanks for your kind words! As you can see in your video (great video showing the validators in action) all validators are running each time you change the value. I can check your *pattern validators* but maybe they are overridden each other, and you only see one at a time because of the regular expressions. 

When I have trouble finding the right regular expression, I always use https://regex101.com/. Maybe it can be useful for you too.

Best regards.

**Comment by julek-kal** [comment]
Hi @joanpablo I found a potential cause of this problem.
in **lib/src/models/models.dart line:542** you have a 
```dart
Map<String, dynamic> _runValidators() {
    final errors = Map<String, dynamic>();
    this.validators.forEach((validator) {
      final error = validator(this);
      if (error != null) {
        errors.addAll(error);
      }
    });

    return errors;
  }
  ```
but in case when I have 2 pattern validators key of each of them is as **"pattern"**.
 
When we take a look at [addAll](https://api.flutter.dev/flutter/dart-core/Map/addAll.html) documentation.
We can find sentence **"If a key of other is already in this map, its value is overwritten."**
 
And when I started debugging this piece of code **addAll** actually was called for each of pattern validators, but return Map with only one pattern validator error because, first pattern overwrite second.

I will suggest to use a pattern value as a key, or add **name** parameter at validator. Even I would make a pull request, but I'm know that you are thinking about refactor associated with null-safety, so maybe I stop myself.

**Comment by joanpablo** [comment]
Mmmm @julek-kal, you are totally right! You cannot have two *errors* with the same name, so I suggest you create a compose validator and just show a text error that contains both explanations.

instead of using:

```dart
FormControl<String>(
      validators: [
        Validators.pattern(CustomValidators.minOneDigitOrSpecialCharacter),
        Validators.pattern(CustomValidators.minOneUpperLetter),
      ],
    ),
```

you can use:

```dart
FormControl<String>(
      validators: [
         Validators.compose([
              Validators.pattern(CustomValidators.minOneDigitOrSpecialCharacter),
              Validators.pattern(CustomValidators.minOneUpperLetter),
         ]),
      ],
    ),
```

and instead of showing two errors:
* Have at least one capital letter
* Have at least one number

use:
* Have at least a capital letter and a number

I will think about the solution you suggested to me related to define a custom **name** to validators.

**Comment by julek-kal** [comment]
@joanpablo thanks for your advice. Unfortunately approach with merging validators isn't this, what I want to do.
Below is better example of what I have on mind

https://user-images.githubusercontent.com/35259453/112218819-7daaf800-8c24-11eb-8ab4-7abd87f46153.mov

I have achieved something like that with form_bloc, but sadly not out-of-the-box, and thats required a lot of dirty hacks.
Since I know that **Reactive Forms** can return multiple errors at once, I think it's almost perfectly fit to the above example, only required change is with those names.

I know there are things with much more higher priority, but I think this can be helpful and revolutionary because I can't find a package with this feature, so if you could keep it on mind, it's would be nice.
I don't know, that I should close this issue or keep it open, so I leave this for your decision.

Thanks for your time, and best regards

**Comment by joanpablo** [comment]
Hi @julek-kal,

You can always create your own validator and it will be very easy. For exmplae you can create you own validator and inside reuse the **Validators.pattern**:

```dart
ValidatorFunction _customPatternValidator(
    Pattern pattern, String errorName) {
  final patternValidator = Validators.pattern(pattern);

  return (AbstractControl<dynamic> control) {
    final error = patternValidator(control);
    return error != null ? <String, dynamic>{errorName: true} : null;
  };
}
```

Definition of the control:
```dart
final control = FormControl<String>(
  validators: [
    _customPatternValidator("some pattern", "minOneDigitOrSpecialCharacterError"),
    _customPatternValidator("some other pattern", "minOneUpperLetterError"),
    _customPatternValidator("etc etc", "otherPatternError"),
  ],
);
```

**Comment by julek-kal** [comment]
Ohh @joanpablo, its sounds like dream come true 😄  It looks like it's should work, thank you very much

**Comment by joanpablo** [comment]
Hi @julek-kal,

I'm planning to include the customization of the name of the error in the next release. As you know I'm heavily working in null safety, and type systems.

I almost have a fully functional version (the actual working code is in develop branch). In this new release you can customize the name of the error like this:

```dart
final control = FormControl<String>(
   validators: [
      Validators.pattern("some pattern", validationMessage: "minOneDigitOrSpecialCharacterError"),
      Validators.pattern("some other pattern", validationMessage: "minOneDigitOrSpecialCharacterError"),
      Validators.pattern("etc etc", validationMessage: "minOneDigitOrSpecialCharacterError"),
   ]
);
```

What do you think, Is it clear enough?

**Comment by julek-kal** [comment]
Yeah, its look good. But I think that `validationMessage` maybe isn't most suitable name. Because you have already `validationMessages` in ReactiveTextField and if I'm not mistaken it's associated with messages for end-user. In my opinion "name" should be more properly appellation. Anyway, I'm very surprised for how fast was this change. Thank you, and fingers crossed for this project.
