### ISSUE TITLE
Show hide password eye icon react native flutter

### ISSUE THREAD

**Issue by AnanthGopal** [joanpablo/reactive_forms#117]
Hi friends,

you are doing great work. 

is have an option to show hide password eye icon react-native flutter

**Comment by joanpablo** [comment]
Hi @AnanthGopal,

This is a small portion of code of a Reactive Password Text Field, I have created in the past in one of my projects:

```dart
@override
  Widget build(BuildContext context) {
    return ReactiveTextField(
      formControlName: widget.formControlName,
      decoration: widget.decoration.copyWith(
      // if _showSuffixIcon then show the Password Eye Button
      suffixIcon: _showSuffixIcon
            ? SuffixIcon(
                icon: this._buildShowPasswordButton(),
              )
            : Container(width: 0),
      ),
    );
  }
```

You can also create a custom Reactive Widget applying the same principle, basically is creating an InputDecoration with a Suffix icon, and show/hide the icon depending of value of the control your widget is bound.

**Comment by AnanthGopal** [comment]
thank you We are awaiting new version.
