### ISSUE TITLE
onchange event in the reactive switch

### ISSUE THREAD

**Issue by AnanthGopal** [joanpablo/reactive_forms#119]
Hi friends

I check the reactive switch, is it have onchange event in the reactive switch?

I need to do some work based on the reactive switch selection mode so that I need onchange event

**Comment by joanpablo** [comment]
Hi @AnanthGopal,

Thanks for using **Reactive Forms**. If you want to be notified when a *control* changes its value, then you can use **FormControl.valueChanges** or the widget **ReactiveValueListenableBuilder**.

Feel free to give me an example of what you are trying to achieve, so I can better help you.

Best regards

**Comment by AnanthGopal** [comment]
@joanpablo 
thank you
I used ReactiveFormConsumer to achieve my requirement
