### ISSUE TITLE
override DoubleValueAccessor

### ISSUE THREAD

**Issue by obione94** [joanpablo/reactive_forms#120]
'longitude': fb.control<double>(12.555555555,[]),
return 12.6 arfffff
how configure no this.fractionDigits please broo

**Comment by joanpablo** [comment]
Hi @obione94,

Thanks broo for using **Reactive Forms** and for the issue. You can override the **fractionDigits** just assigning a new **DoubleValueAccessor** to the **ReactiveTextField** and specifying the *fractionDigits*:

```dart
ReactiveTextField(
   formControlName: 'longitude',
   valueAccessor: DoubleValueAccessor(fractionDigits: 9)
),
```

**Comment by obione94** [comment]
lool so simple tks ;)
