### ISSUE TITLE
updateValue not working

### ISSUE THREAD

**Issue by rodriger06** [joanpablo/reactive_forms#122]
Hi, I am having an issue updating value in my textfields.  I have a screen that display a listview of values.  when i click one of the item in the list, it will take me to another screen that display my reactive form.  when I display the screen with the form, I am trying to update the value of the textfields with the values that had been past to the form but it is not working for me.  here is partial code

```

class AddEditIncomeForm extends StatelessWidget {
  AddEditIncomeForm({
    Key key,
    this.incomeTransactionType,
    this.incomeData
  }) : super(key: key);

  final String incomeTransactionType;
  final IncomeDetailListResult incomeData;
  FormGroup get form => fb.group(<String, dynamic>{
    'amount': FormControl<String>(validators: [Validators.required]),
    'frequency': FormControl<String>(),
  });



  @override
  Widget build(BuildContext context) {
    final database = Provider.of<AppDatabase>(context);

    form.control('frequency').value='test';
    this.form.value = {
      'amount': incomeData.actualAmount.toString(),
    };

    return Scaffold(
      appBar: AppBar(title: Text(incomeTitle), backgroundColor: colorPrimary,),
      floatingActionButtonLocation: FloatingActionButtonLocation.endTop,
      floatingActionButton: FloatingActionButton(
        backgroundColor: colorPrimary,
        onPressed: () {
        },
        child: Icon(
          Icons.save,
        ),
      ),
      body: SingleChildScrollView(
        physics: ClampingScrollPhysics(),
        child: ReactiveFormBuilder(
          form: () => this.form,
          builder: (context, form, child) {
            return Container(
              margin: EdgeInsets.all(13.0),
              child: Column(
                children: [
                 ReactiveTextField<String>(
                     textAlignVertical: TextAlignVertical.center,
                     keyboardType: TextInputType.number,
                    formControlName: 'amount',
                   decoration: InputDecoration(
                       labelText: incomeAmount,
                      labelStyle: TextStyle(
                        fontSize: text_size_20
                   ),
               border: OutlineInputBorder(),
              prefixIcon: Icon(Icons.attach_money, color:green),
            ),
          validationMessages: (errors) => {
          ValidationMessage.required: 'Amount must not be empty',
      
        );

        ReactiveTextField<String>(
                     textAlignVertical: TextAlignVertical.center,
                     keyboardType: TextInputType.number,
                    formControlName: 'frequency',
                   decoration: InputDecoration(
                       labelText: incomeAmount,
                      labelStyle: TextStyle(
                        fontSize: text_size_20
                   ),
               border: OutlineInputBorder(),
              prefixIcon: Icon(Icons.attach_money, color:green),
            ),
          validationMessages: (errors) => {
          ValidationMessage.required: 'frequency must not be empty',
      
        );,

                ],
              ),
            );
          },
        ),
      ),
    );
  }


```

i tried using different way to set the values such as  using control  or form.value{} and so on but the textfield doesnt get updated with the values. they stay blank

```
form.control('frequency').value='test';
    this.form.value = {
      'amount': incomeData.actualAmount.toString(),
    };
```

am I doing something wrong?  can someone help?  As mentioned above, I am passing values from one screen to my screen which contain the form and trying to update the textfields.

**Comment by joanpablo** [comment]
Hi @rodriger06,

Thanks for using **Reactive Forms** and for the issue.

You first need to understand two things:
1- Each time your widget builds you are creating a new **FormGroup**:
```dart
// calling this `get` will always create a new form group
FormGroup get form => fb.group(...);
```
So when you update the value you are not updating the value of the FormGroup bound with the **ReactiveFormBuilder**.

2- You should update your form value in a controller/viewmodel/provider/bloc/etc, not in the build method. Remember that a FormGroup or FormControl is your model and you should not update them when building the widget, but independently.

For example, in your case, I suggest you create a Provider that holds the definition of the FormGroup.  Then you access that provider within your *AddEditIncomeForm* widget and bind it to a **ReactiveForm**. And before navigate to the screen with the AddEditIncomeForm you can access your provider (from anywhere in your app) and update the controls.

I hope you get the idea. If you still have questions don't hesitate to ask me again.

Best regards.

**Comment by rodriger06** [comment]
Hi joanplablo, thank you for your input.  I really appreciate it.  I am not 100% sure how to create the provider and bind it to the reactiveform.  do you have some sample code that I can use based on my example?  It will be very helpful. thanks in advance

**Comment by rodriger06** [comment]
hi joanpablo,

I managed to do the following:
i created a model with the form defined
```
import 'dart:core';

import 'package:flutter/material.dart' ;
import 'package:provider/provider.dart';
import 'package:flutter/services.dart';
import 'package:reactive_forms_widgets/reactive_date_time_picker/reactive_date_time_picker.dart';
import 'package:reactive_forms_widgets/reactive_dropdown_search/reactive_dropdown_search.dart';
import 'package:reactive_forms/reactive_forms.dart';


class IncomeViewModel {
  FormGroup get form =>
      fb.group(<String, dynamic>{
        'amount': FormControl<String>(validators: [Validators.required]),
        'frequency': FormControl<String>(),
      });

  void updateValues(IncomeDetailListResult incomeData2)  {
    this.form.value = {
      'amount': incomeData2.actualAmount.toString(),
      'frequency': incomeData2.frequency,
    };
  }
}
```
then I call this class before calling my form screen.  i called it like this
``` 
final viewModel = new IncomeViewModel( );
viewModel.updateValues(transaction);`
```

then in my form, i have the following:
```
class AddEditIncomeForm extends StatelessWidget {
  AddEditIncomeForm({
    Key key,
    this.incomeTransactionType,
    this.incomeData
  }) : super(key: key);

  final String incomeTransactionType;
  final IncomeDetailListResult incomeData;
  FormGroup get form => fb.group(<String, dynamic>{
    'amount': FormControl<String>(validators: [Validators.required]),
    'frequency': FormControl<String>(),
  });



  @override
  Widget build(BuildContext context) {
    final database = Provider.of<AppDatabase>(context);
    **final viewModel = Provider.of<IncomeViewModel>(context, listen: false);**

    form.control('frequency').value='test';
    this.form.value = {
      'amount': incomeData.actualAmount.toString(),
    };

    return Scaffold(
      appBar: AppBar(title: Text(incomeTitle), backgroundColor: colorPrimary,),
      floatingActionButtonLocation: FloatingActionButtonLocation.endTop,
      floatingActionButton: FloatingActionButton(
        backgroundColor: colorPrimary,
        onPressed: () {
        },
        child: Icon(
          Icons.save,
        ),
      ),
      body: SingleChildScrollView(
        physics: ClampingScrollPhysics(),
        child: **ReactiveForm( 
          formGroup: viewModel.form,**
          child: Container(
              margin: EdgeInsets.all(13.0),
              child: Column(
                children: [
                 ReactiveTextField<String>(
                     textAlignVertical: TextAlignVertical.center,
                     keyboardType: TextInputType.number,
                    formControlName: 'amount',
                   decoration: InputDecoration(
                       labelText: incomeAmount,
                      labelStyle: TextStyle(
                        fontSize: text_size_20
                   ),
               border: OutlineInputBorder(),
              prefixIcon: Icon(Icons.attach_money, color:green),
            ),
          validationMessages: (errors) => {
          ValidationMessage.required: 'Amount must not be empty',
      
        );

        ReactiveTextField<String>(
                     textAlignVertical: TextAlignVertical.center,
                     keyboardType: TextInputType.number,
                    formControlName: 'frequency',
                   decoration: InputDecoration(
                       labelText: incomeAmount,
                      labelStyle: TextStyle(
                        fontSize: text_size_20
                   ),
               border: OutlineInputBorder(),
              prefixIcon: Icon(Icons.attach_money, color:green),
            ),
          validationMessages: (errors) => {
          ValidationMessage.required: 'frequency must not be empty',
      
        );,

                ],
              ),
            );
        ),
      ),
    );
  }
```
still i dont see the values updated in the reactive text field.  am I still missing something? please provide any feedback. thanks  in advance

**Comment by joanpablo** [comment]
Hi @rodriger06 

If you want quickly see your example running you can update your formGroup inside the *builder* of the **ReactiveFormBuilder**.

```dart
ReactiveFormBuilder(
          form: () => this.form,
          builder: (context, form, child) {
//update form here
 }
```

But that is not what I recommend.

What I always recommend is to use a state management library. For example I can see you are using Provider package, that's great. In the next comment I will show you an example

**Comment by joanpablo** [comment]
In you viewmodel class change this:

```dart
class IncomeViewModel {
  FormGroup get form =>
      fb.group(<String, dynamic>{
        'amount': FormControl<String>(validators: [Validators.required]),
        'frequency': FormControl<String>(),
      });
}
```

to this:

```dart
class IncomeViewModel {
  final form = fb.group(<String, dynamic>{
        'amount': FormControl<String>(validators: [Validators.required]),
        'frequency': FormControl<String>(),
      });
}
```

**Comment by rodriger06** [comment]
Hi joanpablo,

after changing the IncomeViewModel class, I can see the form is now updating the textfields.  thanks a lot.  I have one more question.  I have a reactive button  ReactiveFormConsumer

```
ReactiveFormConsumer(
                    builder: (context, form, child) {
                      return RaisedButton(
                        child: Text('SAVE'),
                        onPressed: form.valid ? () => print(form.value) : null,
                      );
                    },
                  ),
```
for this button to become active, i need to filled out the required fields.  When I fixed the IncomeViewModel class based on your suggesstions, the fields are now populating. however, the ReactiveFormConsumer becomes active even though not all required field are updated in my model class. here are my questions:

1.  how do I fix the ReactiveFormConsumer button so that when I update my form from values pass from another screen, the button will still be inactive ? see pic attached of active button circled in red
the rest of the blank fields are required. i only updated the first two but the button is active even though im using ReactiveFormConsumer . the button should had been grey out when inactive and blue when active.
<img width="194" alt="active button" src="https://user-images.githubusercontent.com/49496303/112475873-ac6dbf00-8d47-11eb-8888-229959554419.PNG">



2.  Instead of a ReactiveFormConsumer button, I want to create a regular button that will be active all the time. however, when user press on the button and the required fields are not populated with values, the fields will turn red and the error messsage will come up to indicate the user that the fields in red needs to be filled out before proceeding.  the error message should show below the textfield.   how can i do that?  can you provide sample code ? 

thanks in advance

**Comment by joanpablo** [comment]
Hi @rodriger06,

There are several questions, let's go in parts (like Jack the Ripper said) :)

First, if you have this code:
```dart
onPressed: form.valid ? () => print(form.value) : null,
```
and your button is always active, then your FormGroup is always **valid**. So you need to check your validators and the default value you are assigned to controls. (you can show me the definition of your form, so I can help you to detect the error)

The second question about having a button always active:

```dart
onPressed: () {
   if (form.invalid) {
      form.markAllAsTouched();
   } else {
      // some business logic here
   }
}
```

**Comment by joanpablo** [comment]
Hi @rodriger06,

I will close the issue now because I'm guessing you have achieved your goals, trying to update a control's value. Don't hesitate to open it again or open a new one if you have more questions.

Best regards.
