### ISSUE TITLE
disable all textfields at once

### ISSUE THREAD

**Issue by bhanuka96** [joanpablo/reactive_forms#123]
How to disable all textFields at once?

Currently, we are using it one by one.
```
 FormControl control = form.control('address_line_1');
 control.markAsDisabled();
```

**All TextFields**

```
  FormGroup address = fb.group({
    'address_line_1': FormControl<String>(...),
    'address_line_2': FormControl<String>(...),
    'city': FormControl<String>(...),
    'state': FormControl<String>(...),
    'pin_code': FormControl<String>(...),
  });
```

**Comment by joanpablo** [comment]
Hi @bhanuka96,

Thanks for the issue. You can simple disable the FormGroup:

```dart
address.markAsDisabled();
```

and all children will be marked as disabled.

Best regards

**Comment by bhanuka96** [comment]
> Hi @bhanuka96,
> 
> Thanks for the issue. You can simple disable the FormGroup:
> 
> ```dart
> address.markAsDisabled();
> ```
> 
> and all children will be marked as disabled.
> 
> Best regards
