### ISSUE TITLE
ReactiveTextField.maxLines cannot be null

### ISSUE THREAD

**Issue by limenote135** [joanpablo/reactive_forms#125]
Thank you for migrating to null-safety! However I found an issue.
TextField.maxLines can be null but ReactiveTextField.maxLines can't be.

https://github.com/joanpablo/reactive_forms/blob/master/lib/src/widgets/reactive_text_field.dart#L114

**Comment by joanpablo** [comment]
Thanks @limenote135 
I will fix it in next release very soon

**Comment by hayashi-ay** [comment]
A temporary workaround is simply set large number such as 999.

```dart
ReactiveTextField<String>(
            formControlName: 'something',
            minLines: 5,
            maxLines: 99, // instead of null
          )
```

**Comment by joanpablo** [comment]
In the current released version, this issue is solved. Thanks

**Comment by limenote135** [comment]
@joanpablo Hmm... Which version do you mean the current release is? v10.0.2 has this issue.

**Comment by joanpablo** [comment]
Hi @limenote135,

Sorry My misunderstood, you are right is not yet solved, I will quickly fix it and by the end of the day I will release a new version.

Thankd

**Comment by joanpablo** [comment]
Hi @limenote135,

I have just release v10.0.3 the **maxLines** fixed. Please check it and re-open the issue or create e new one if you find something else wrong.

Thanks, have a nice evening.

**Comment by limenote135** [comment]
@joanpablo Thank you for your quick fix!
