### ISSUE TITLE
using StreamBuilder inside ReactiveForm

### ISSUE THREAD

**Issue by kfchengkf** [joanpablo/reactive_forms#127]
Hi,
I wonder if there is any issue using StreamBuilder inside ReactiveForm.
I have a ReactiveForm with a StreamBuilder that populate a dropwdown (Not ReactiveDropdownField),
using records that feed into the stream used by the streambuilder.
However, there is always no data.
Using streambuilder on another page without the ReactiveForm, I can
see the data coming up.
Any idea ?
Thanks.

**Comment by joanpablo** [comment]
Hi @kfchengkf,

Could you please give a sample code to better understand what you are trying to achieve?

**Comment by kfchengkf** [comment]
Hi joanpablo,

In the process of making the sample code, I found that the issue is related to TabView.

I have a complex form with multiple pages, so the hierarchy is like this:
ReactiveForm
   TabView
      Page 1
      Page 2
        StreamBuilder
           Dropdown
      ....other pages

If the SteamBuilder and Dropdown is put to page 1, the dropdown have data.
If it is on Page 2, the dropdown does not have data.

The dropdown is used to pick a value, which will be used for filter criteria on
another dropdown (not mentioned above).  The list of values come from
a sqlite db.

Any idea ?

**Comment by kfchengkf** [comment]
Hi joanpablo,
Please ignore it. Removing the ReactiveForm does not solve this issue, so this is probably something else.
Thanks.

**Comment by joanpablo** [comment]
Hi @kfchengkf,

With some sample code, I could get a better understanding.

**Comment by joanpablo** [comment]
Hi @kfchengkf,

Have you solved the issue? I haven't here about you recently. I would like to know if you have success with your issue?

**Comment by kfchengkf** [comment]
Hi joanpablo,
Yes, I work around the issue by using Future builder instead of SteamBuilder. The issue is not related to ReactiveForm.
I think its somehow a known issue with SteamBuilder.
