### ISSUE TITLE
How to show form data into listview 

### ISSUE THREAD

**Issue by AnanthGopal** [joanpablo/reactive_forms#131]
Hi @joanpablo ,

can you have a sample code to show reactive form data into listview

For example,
I attached the two files one is ViewModel file another one is a view file

but I can't show data into listview

[test_view_model.txt](https://github.com/joanpablo/reactive_forms/files/6224305/test_view_model.txt)
[test_view.txt](https://github.com/joanpablo/reactive_forms/files/6224306/test_view.txt)

**Comment by AnanthGopal** [comment]
Hi @joanpablo 

I did the above requirement by using the below code 

`

> ReactiveForm(
>                 formGroup: viewModel.form,
>                 child: SingleChildScrollView(
>                   physics: ClampingScrollPhysics(),
>                   child: new Container(
>                     height: (MediaQuery.of(context).size.height - 25),
>                     child:
>                         ReactiveFormConsumer(builder: (context, form, child) {
>                       var currentControl = form.control('listData').value;
>                       return ListView.separated(
>                         itemCount: currentControl.length,
>                         itemBuilder: (BuildContext context, int index) {
>                           SubUserDetailListResponse rowData =
>                               currentControl[index];
>                           return new UserListView(rowData);
>                         },
>                         separatorBuilder: (BuildContext context, int index) {
>                           return SizedBox(
>                             height: 10.0,
>                           );
>                         },
>                       );
>                     }),
>                   ),
>                 ),
>               )

`

**Comment by joanpablo** [comment]
Hi @AnanthGopal,

I guess you have solved the issue, haven't you?
