### ISSUE TITLE
type 'Null' is not a subtype of type 'AbstractControl<Object>' in type cast

### ISSUE THREAD

**Issue by cezaryjk** [joanpablo/reactive_forms#133]
Hi, 
Your package is awesome! Thank you very much. 

Everything worked like a charm until null-safety migration (10.0.3). 
New version revealed my bad: I tried to focus non-existing control (instead of 'Id' i put 'id') using 
`form.focus('id');`

It ended up with error: 

type 'Null' is not a subtype of type 'AbstractControl<Object>' in type cast

in function findControl from form_control_collection.dart

Thanks!
Best regards
Cezary

**Comment by joanpablo** [comment]
Hi @cezaryjk,

Thanks for the issue. I will take a look and fix it. I will let you know when the new version is released.

Best regards

**Comment by joanpablo** [comment]
Hi @cezaryjk,

I have just release v10.0.4, this version solve the issue. Please test it and let me know for closing the issue.

Thanks and Best Regards

**Comment by joanpablo** [comment]
Don't hesitate to open it again or create a new one if something is not working.

**Comment by cezaryjk** [comment]
Hi @joanpablo ,

Thanks a lot for such a quick action!
Works like a charm!

Best regards
Cezary
