### ISSUE TITLE
I have some issue ControlValueAccessor<Class, String>

### ISSUE THREAD

**Issue by nousath** [joanpablo/reactive_forms#134]
I have some issue ControlValueAccessor<Class, String> value getting **Instance of 'Relation'** how to change String 

```
class RelationShipValueAccessor<T> extends ControlValueAccessor<Relation, String> {
  @override
  String? modelToViewValue(Relation? modelValue) {
    return modelValue == null ? null : modelValue.name;
  }

  @override
  Relation? viewToModelValue(String? viewValue) {
    return (viewValue == null || viewValue == null) ? null : Relation(id: viewValue, name: '');
  }
}
```

this is my code.

**Comment by joanpablo** [comment]
Hi @nousath, 

Thanks for the issue and for using Reactive Forms, but I don't understand very well what is your issue. Could you please argue e little more?

Thanks

**Comment by nousath** [comment]
thank you for fast repling @joanpablo creating custom fields **Typeahead** Items pass in Class i want form retrun value id but getting **Instance of 'Relation'** how to get in id from class.

Custom Field Code
`// Copyright 2020 Joan Pablo Jimenez Milian. All rights reserved.
// Use of this source code is governed by the MIT license that can be
// found in the LICENSE file.

import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:reactive_forms/reactive_forms.dart';
import 'package:reactive_forms/src/value_accessors/control_value_accessor.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';
import 'package:vyocrm/services_entity.dart';

import 'value_accessor/relationship_value_accessor.dart';

typedef SelectionToTextTransformer<T> = String Function(T suggestion);

/// A [ReactiveTypeaheadField] that contains a [TypeAheadField].
///
/// This is a convenience widget that wraps a [TypeAheadField] widget in a
/// [ReactiveTypeaheadField].
///
/// A [ReactiveForm] ancestor is required.
///
class ReactiveTypeaheadField<T> extends ReactiveFormField<T, String> {
  /// Creates a [ReactiveTypeaheadField] that contains a [TypeAheadField].
  ///
  /// Can optionally provide a [formControl] to bind this widget to a control.
  ///
  /// Can optionally provide a [formControlName] to bind this ReactiveFormField
  /// to a [FormControl].
  ///
  /// Must provide one of the arguments [formControl] or a [formControlName],
  /// but not both at the same time.
  ///
  /// Can optionally provide a [validationMessages] argument to customize a
  /// message for different kinds of validation errors.
  ///
  /// Can optionally provide a [valueAccessor] to set a custom value accessors.
  /// See [ControlValueAccessor].
  ///
  /// Can optionally provide a [showErrors] function to customize when to show
  /// validation messages. Reactive Widgets make validation messages visible
  /// when the control is INVALID and TOUCHED, this behavior can be customized
  /// in the [showErrors] function.
  ///
  /// ### Example:
  /// Binds a text field.
  /// ```
  /// final form = fb.group({'email': Validators.required});
  ///
  /// ReactiveTextField(
  ///   formControlName: 'email',
  /// ),
  ///
  /// ```
  ///
  /// Binds a text field directly with a *FormControl*.
  /// ```
  /// final form = fb.group({'email': Validators.required});
  ///
  /// ReactiveTextField(
  ///   formControl: form.control('email'),
  /// ),
  ///
  /// ```
  ///
  /// Customize validation messages
  /// ```dart
  /// ReactiveTextField(
  ///   formControlName: 'email',
  ///   validationMessages: {
  ///     ValidationMessage.required: 'The email must not be empty',
  ///     ValidationMessage.email: 'The email must be a valid email',
  ///   }
  /// ),
  /// ```
  ///
  /// Customize when to show up validation messages.
  /// ```dart
  /// ReactiveTextField(
  ///   formControlName: 'email',
  ///   showErrors: (control) => control.invalid && control.touched && control.dirty,
  /// ),
  /// ```
  ///
  /// For documentation about the various parameters, see the [TypeAheadField] class
  /// and [new TypeAheadField], the constructor.
  ReactiveTypeaheadField(
      {Key? key,
      String? formControlName,
      FormControl<T>? formControl,
      ValidationMessagesFunction<T>? validationMessages,
      ControlValueAccessor<T, String>? valueAccessor,
      ShowErrorsFunction? showErrors,
      InputDecoration decoration = const InputDecoration(),
      FocusNode? focusNode,
      TextFieldConfiguration textFieldConfiguration = const TextFieldConfiguration(),
      VoidCallback? onSubmitted,
      required ItemBuilder<T> itemBuilder,
      required SuggestionsCallback<T> suggestionsCallback,
      required SelectionToTextTransformer<T> selectionToTextTransformer,
      required SuggestionSelectionCallback<T> onSuggestionSelected,
      required AnimationTransitionBuilder transitionBuilder,
      ValueChanged<T>? onChanged,
      bool afterValue = false,
      bool getImmediateSuggestions = false,
      ErrorBuilder? errorBuilder,
      WidgetBuilder? noItemsFoundBuilder,
      WidgetBuilder? loadingBuilder,
      Duration debounceDuration = const Duration(milliseconds: 300),
      SuggestionsBoxDecoration suggestionsBoxDecoration = const SuggestionsBoxDecoration(),
      double suggestionsBoxVerticalOffset = 5.0,
      Duration animationDuration = const Duration(milliseconds: 500),
      double animationStart = 0.25,
      AxisDirection direction = AxisDirection.down,
      bool hideOnLoading = false,
      bool hideOnEmpty = false,
      bool hideOnError = false,
      bool hideSuggestionsOnKeyboardHide = true,
      bool keepSuggestionsOnLoading = false,
      bool keepSuggestionsOnSuggestionSelected = false,
      bool autoFlipDirection = false,
      bool hideKeyboard = false,
      ValueTransformer<T>? valueTransformer,
      SuggestionsBoxController? suggestionsBoxController})
      : assert(selectionToTextTransformer != null),
        super(
          key: key,
          formControl: formControl,
          formControlName: formControlName,
          valueAccessor: valueAccessor,
          validationMessages: validationMessages,
          showErrors: showErrors,
          builder: (ReactiveFormFieldState<T, String> field) {
            final state = field as _ReactiveTypeaheadFieldState<T>;
            final theme = Theme.of(state.context);
            final effectiveDecoration = decoration.applyDefaults(Theme.of(state.context).inputDecorationTheme);
            state._setFocusNode(focusNode);
            return TypeAheadField<T>(
              textFieldConfiguration: textFieldConfiguration.copyWith(
                enabled: field.control.enabled,
                controller: state._textController,
                style: state.control.enabled
                    ? textFieldConfiguration.style
                    : theme.textTheme.subtitle1!.copyWith(
                        color: theme.disabledColor,
                      ),
                focusNode: focusNode,
                decoration: effectiveDecoration.copyWith(errorText: state.errorText),
                onSubmitted: onSubmitted != null ? (_) => onSubmitted() : null,
              ) as TextFieldConfiguration,
              suggestionsCallback: suggestionsCallback,
              itemBuilder: itemBuilder,
              transitionBuilder: (context, suggestionsBox, controller) => suggestionsBox,
              onSuggestionSelected: (dynamic suggestion) {
                if (selectionToTextTransformer != null) {
                  state._textController.text = selectionToTextTransformer(suggestion);
                } else {
                  state._textController.text = suggestion != null ? suggestion.toString() : '';
                }
                // onSuggestionSelected.call(suggestion);
                // if (valueTransformer!(suggestion) == '') {
                //   controller!.clear();
                // }
                print(valueTransformer!(suggestion));
                field.didChange(valueTransformer(suggestion));

                if (afterValue == true) {
                  state._textController.clear();
                }
                onChanged?.call(suggestion);
              },
              getImmediateSuggestions: getImmediateSuggestions,
              errorBuilder: errorBuilder,
              noItemsFoundBuilder: noItemsFoundBuilder,
              loadingBuilder: loadingBuilder,
              debounceDuration: debounceDuration,
              suggestionsBoxDecoration: suggestionsBoxDecoration,
              suggestionsBoxVerticalOffset: suggestionsBoxVerticalOffset,
              animationDuration: animationDuration,
              animationStart: animationStart,
              direction: direction,
              hideOnLoading: hideOnLoading,
              hideOnEmpty: hideOnEmpty,
              hideOnError: hideOnError,
              hideSuggestionsOnKeyboardHide: hideSuggestionsOnKeyboardHide,
              keepSuggestionsOnLoading: keepSuggestionsOnLoading,
              autoFlipDirection: autoFlipDirection,
              suggestionsBoxController: suggestionsBoxController,
              keepSuggestionsOnSuggestionSelected: keepSuggestionsOnSuggestionSelected,
              hideKeyboard: hideKeyboard,
            );
          },
        );

  @override
  ReactiveFormFieldState<T, String> createState() => _ReactiveTypeaheadFieldState<T>();
}

class _ReactiveTypeaheadFieldState<T> extends ReactiveFormFieldState<T, String> {
  late TextEditingController _textController;
  FocusNode? _focusNode;
  late FocusController _focusController;

  FocusNode get focusNode => _focusNode ?? _focusController.focusNode;

  @override
  void initState() {
    super.initState();

    final initialValue = value;
    _textController = TextEditingController(text: initialValue == null ? '' : initialValue.toString());
  }

  @override
  void subscribeControl() {
    _registerFocusController(FocusController());
    super.subscribeControl();
  }

  @override
  void unsubscribeControl() {
    _unregisterFocusController();
    super.unsubscribeControl();
  }
  //
  // @override
  // void onControlValueChanged(dynamic value) {
  //   final effectiveValue = (value == null) ? '' : value.toString();
  //   _textController.value = _textController.value.copyWith(
  //     text: effectiveValue,
  //     selection: TextSelection.collapsed(offset: effectiveValue.length),
  //     composing: TextRange.empty,
  //   );
  //
  //   super.onControlValueChanged(value);
  // }
  //
  // @override
  // ControlValueAccessor<dynamic, dynamic> selectValueAccessor() {
  //   if (control is FormControl<int>) {
  //     return IntValueAccessor();
  //   } else if (control is FormControl<double>) {
  //     return DoubleValueAccessor();
  //   } else if (control is FormControl<DateTime>) {
  //     return DateTimeValueAccessor();
  //   } else if (control is FormControl<TimeOfDay>) {
  //     return TimeOfDayValueAccessor();
  //   } else if (control is FormControl<Relation>) {
  //     return RelationShipValueAccessor();
  //   }
  //
  //   return super.selectValueAccessor();
  // }
  //
  void _registerFocusController(FocusController focusController) {
    _focusController = focusController;
    control.registerFocusController(focusController);
  }

  void _unregisterFocusController() {
    control.unregisterFocusController(_focusController);
    _focusController.dispose();
  }

  void _setFocusNode(FocusNode? focusNode) {
    if (_focusNode == focusNode) {
      return;
    } else if (focusNode == null && _focusNode != null) {
      _focusNode = null;
    } else if (focusNode != null && _focusNode == null) {
      _focusNode = focusNode;
    }

    _unregisterFocusController();
    _registerFocusController(FocusController(focusNode: _focusNode));
  }
}
`
ControlValueAccessor Code
`
/// Represents a control value accessor that convert between data types
/// [Relation] and [String].
class RelationShipValueAccessor<T> extends ControlValueAccessor<Relation, String> {
  @override
  String? modelToViewValue(Relation? modelValue) {
    print("modelToViewValue ${modelValue}");
    return modelValue == null ? null : modelValue.name;
  }

  @override
  Relation? viewToModelValue(String? viewValue) {
    print("viewToModelValue ${viewValue}");
    return (viewValue == null || viewValue == null) ? null : Relation(id: viewValue, name: '');
  }
}
`

**Comment by nousath** [comment]
thank you for fast repling @joanpablo creating custom fields Typeahead Items pass in Class i want form retrun value id but getting Instance of 'Relation' how to get in id from class.

Custom Field Code

`import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:reactive_forms/reactive_forms.dart';
import 'package:reactive_forms/src/value_accessors/control_value_accessor.dart';
import 'package:flutter_typeahead/flutter_typeahead.dart';
import 'package:vyocrm/services_entity.dart';

import 'value_accessor/relationship_value_accessor.dart';

typedef SelectionToTextTransformer = String Function(T suggestion);

ReactiveTypeaheadField(
{Key? key,
String? formControlName,
FormControl? formControl,
ValidationMessagesFunction? validationMessages,
ControlValueAccessor<T, String>? valueAccessor,
ShowErrorsFunction? showErrors,
InputDecoration decoration = const InputDecoration(),
FocusNode? focusNode,
TextFieldConfiguration textFieldConfiguration = const TextFieldConfiguration(),
VoidCallback? onSubmitted,
required ItemBuilder itemBuilder,
required SuggestionsCallback suggestionsCallback,
required SelectionToTextTransformer selectionToTextTransformer,
required SuggestionSelectionCallback onSuggestionSelected,
required AnimationTransitionBuilder transitionBuilder,
ValueChanged? onChanged,
bool afterValue = false,
bool getImmediateSuggestions = false,
ErrorBuilder? errorBuilder,
WidgetBuilder? noItemsFoundBuilder,
WidgetBuilder? loadingBuilder,
Duration debounceDuration = const Duration(milliseconds: 300),
SuggestionsBoxDecoration suggestionsBoxDecoration = const SuggestionsBoxDecoration(),
double suggestionsBoxVerticalOffset = 5.0,
Duration animationDuration = const Duration(milliseconds: 500),
double animationStart = 0.25,
AxisDirection direction = AxisDirection.down,
bool hideOnLoading = false,
bool hideOnEmpty = false,
bool hideOnError = false,
bool hideSuggestionsOnKeyboardHide = true,
bool keepSuggestionsOnLoading = false,
bool keepSuggestionsOnSuggestionSelected = false,
bool autoFlipDirection = false,
bool hideKeyboard = false,
ValueTransformer? valueTransformer,
SuggestionsBoxController? suggestionsBoxController})
: assert(selectionToTextTransformer != null),
super(
key: key,
formControl: formControl,
formControlName: formControlName,
valueAccessor: valueAccessor,
validationMessages: validationMessages,
showErrors: showErrors,
builder: (ReactiveFormFieldState<T, String> field) {
final state = field as _ReactiveTypeaheadFieldState;
final theme = Theme.of(state.context);
final effectiveDecoration = decoration.applyDefaults(Theme.of(state.context).inputDecorationTheme);
state._setFocusNode(focusNode);
return TypeAheadField(
textFieldConfiguration: textFieldConfiguration.copyWith(
enabled: field.control.enabled,
controller: state.textController,
style: state.control.enabled
? textFieldConfiguration.style
: theme.textTheme.subtitle1!.copyWith(
color: theme.disabledColor,
),
focusNode: focusNode,
decoration: effectiveDecoration.copyWith(errorText: state.errorText),
onSubmitted: onSubmitted != null ? () => onSubmitted() : null,
) as TextFieldConfiguration,
suggestionsCallback: suggestionsCallback,
itemBuilder: itemBuilder,
transitionBuilder: (context, suggestionsBox, controller) => suggestionsBox,
onSuggestionSelected: (dynamic suggestion) {
if (selectionToTextTransformer != null) {
state._textController.text = selectionToTextTransformer(suggestion);
} else {
state._textController.text = suggestion != null ? suggestion.toString() : '';
}

            field.didChange(valueTransformer(suggestion));

            if (afterValue == true) {
              state._textController.clear();
            }
            onChanged?.call(suggestion);
          },
          getImmediateSuggestions: getImmediateSuggestions,
          errorBuilder: errorBuilder,
          noItemsFoundBuilder: noItemsFoundBuilder,
          loadingBuilder: loadingBuilder,
          debounceDuration: debounceDuration,
          suggestionsBoxDecoration: suggestionsBoxDecoration,
          suggestionsBoxVerticalOffset: suggestionsBoxVerticalOffset,
          animationDuration: animationDuration,
          animationStart: animationStart,
          direction: direction,
          hideOnLoading: hideOnLoading,
          hideOnEmpty: hideOnEmpty,
          hideOnError: hideOnError,
          hideSuggestionsOnKeyboardHide: hideSuggestionsOnKeyboardHide,
          keepSuggestionsOnLoading: keepSuggestionsOnLoading,
          autoFlipDirection: autoFlipDirection,
          suggestionsBoxController: suggestionsBoxController,
          keepSuggestionsOnSuggestionSelected: keepSuggestionsOnSuggestionSelected,
          hideKeyboard: hideKeyboard,
        );
      },
    );
@override
ReactiveFormFieldState<T, String> createState() => _ReactiveTypeaheadFieldState();
}

class _ReactiveTypeaheadFieldState extends ReactiveFormFieldState<T, String> {
late TextEditingController _textController;
FocusNode? _focusNode;
late FocusController _focusController;

FocusNode get focusNode => _focusNode ?? _focusController.focusNode;

@override
void initState() {
super.initState();

final initialValue = value;
_textController = TextEditingController(text: initialValue == null ? '' : initialValue.toString());
}

@override
void subscribeControl() {
_registerFocusController(FocusController());
super.subscribeControl();
}

@override
void unsubscribeControl() {
_unregisterFocusController();
super.unsubscribeControl();
}

void _registerFocusController(FocusController focusController) {
_focusController = focusController;
control.registerFocusController(focusController);
}

void _unregisterFocusController() {
control.unregisterFocusController(_focusController);
_focusController.dispose();
}

void _setFocusNode(FocusNode? focusNode) {
if (_focusNode == focusNode) {
return;
} else if (focusNode == null && _focusNode != null) {
_focusNode = null;
} else if (focusNode != null && _focusNode == null) {
_focusNode = focusNode;
}

_unregisterFocusController();
_registerFocusController(FocusController(focusNode: _focusNode));
}
}`

ControlValueAccessor Code
`
class RelationShipValueAccessor extends ControlValueAccessor<Relation, String> {
@override
String? modelToViewValue(Relation? modelValue) {
print("modelToViewValue ${modelValue}");
return modelValue == null ? null : modelValue.name;
}

@override
Relation? viewToModelValue(String? viewValue) {
print("viewToModelValue ${viewValue}");
return (viewValue == null || viewValue == null) ? null : Relation(id: viewValue, name: '');
}
}
`

form submit value {status: 2, source: 1, source_ref_type: suppliers, source_ref_id: Instance of 'Relation', source_ref_text: , assigned: 1, email: tseting@gmail.com}

**Comment by nousath** [comment]
If possible ValueTransformer to Submit the form?

**Comment by kuhnroyal** [comment]
Please format the code with ` ```dart `

**Comment by nousath** [comment]
Sorry @kuhnroyal 

Custom Typeahead Coding

```
typedef SelectionToTextTransformer<T> = String Function(T suggestion);

/// A [ReactiveTypeaheadField] that contains a [TypeAheadField].
///
/// This is a convenience widget that wraps a [TypeAheadField] widget in a
/// [ReactiveTypeaheadField].
///
/// A [ReactiveForm] ancestor is required.
///
class ReactiveTypeaheadField<T> extends ReactiveFormField<T, String> {
  /// Creates a [ReactiveTypeaheadField] that contains a [TypeAheadField].
  ///
  /// Can optionally provide a [formControl] to bind this widget to a control.
  ///
  /// Can optionally provide a [formControlName] to bind this ReactiveFormField
  /// to a [FormControl].
  ///
  /// Must provide one of the arguments [formControl] or a [formControlName],
  /// but not both at the same time.
  ///
  /// Can optionally provide a [validationMessages] argument to customize a
  /// message for different kinds of validation errors.
  ///
  /// Can optionally provide a [valueAccessor] to set a custom value accessors.
  /// See [ControlValueAccessor].
  ///
  /// Can optionally provide a [showErrors] function to customize when to show
  /// validation messages. Reactive Widgets make validation messages visible
  /// when the control is INVALID and TOUCHED, this behavior can be customized
  /// in the [showErrors] function.
  ///
  /// ### Example:
  /// Binds a text field.
  /// ```
  /// final form = fb.group({'email': Validators.required});
  ///
  /// ReactiveTextField(
  ///   formControlName: 'email',
  /// ),
  ///
  /// ```
  ///
  /// Binds a text field directly with a *FormControl*.
  /// ```
  /// final form = fb.group({'email': Validators.required});
  ///
  /// ReactiveTextField(
  ///   formControl: form.control('email'),
  /// ),
  ///
  /// ```
  ///
  /// Customize validation messages
  /// ```dart
  /// ReactiveTextField(
  ///   formControlName: 'email',
  ///   validationMessages: {
  ///     ValidationMessage.required: 'The email must not be empty',
  ///     ValidationMessage.email: 'The email must be a valid email',
  ///   }
  /// ),
  /// ```
  ///
  /// Customize when to show up validation messages.
  /// ```dart
  /// ReactiveTextField(
  ///   formControlName: 'email',
  ///   showErrors: (control) => control.invalid && control.touched && control.dirty,
  /// ),
  /// ```
  ///
  /// For documentation about the various parameters, see the [TypeAheadField] class
  /// and [new TypeAheadField], the constructor.
  ReactiveTypeaheadField(
      {Key? key,
      String? formControlName,
      FormControl<T>? formControl,
      ValidationMessagesFunction<T>? validationMessages,
      ControlValueAccessor<T, String>? valueAccessor,
      ShowErrorsFunction? showErrors,
      InputDecoration decoration = const InputDecoration(),
      FocusNode? focusNode,
      TextFieldConfiguration textFieldConfiguration = const TextFieldConfiguration(),
      VoidCallback? onSubmitted,
      required ItemBuilder<T> itemBuilder,
      required SuggestionsCallback<T> suggestionsCallback,
      required SelectionToTextTransformer<T> selectionToTextTransformer,
      required SuggestionSelectionCallback<T> onSuggestionSelected,
      required AnimationTransitionBuilder transitionBuilder,
      ValueChanged<T>? onChanged,
      bool afterValue = false,
      bool getImmediateSuggestions = false,
      ErrorBuilder? errorBuilder,
      WidgetBuilder? noItemsFoundBuilder,
      WidgetBuilder? loadingBuilder,
      Duration debounceDuration = const Duration(milliseconds: 300),
      SuggestionsBoxDecoration suggestionsBoxDecoration = const SuggestionsBoxDecoration(),
      double suggestionsBoxVerticalOffset = 5.0,
      Duration animationDuration = const Duration(milliseconds: 500),
      double animationStart = 0.25,
      AxisDirection direction = AxisDirection.down,
      bool hideOnLoading = false,
      bool hideOnEmpty = false,
      bool hideOnError = false,
      bool hideSuggestionsOnKeyboardHide = true,
      bool keepSuggestionsOnLoading = false,
      bool keepSuggestionsOnSuggestionSelected = false,
      bool autoFlipDirection = false,
      bool hideKeyboard = false,
      ValueTransformer<T>? valueTransformer,
      SuggestionsBoxController? suggestionsBoxController})
      : assert(selectionToTextTransformer != null),
        super(
          key: key,
          formControl: formControl,
          formControlName: formControlName,
          valueAccessor: valueAccessor,
          validationMessages: validationMessages,
          showErrors: showErrors,
          builder: (ReactiveFormFieldState<T, String> field) {
            final state = field as _ReactiveTypeaheadFieldState<T>;
            final theme = Theme.of(state.context);
            final effectiveDecoration = decoration.applyDefaults(Theme.of(state.context).inputDecorationTheme);
            state._setFocusNode(focusNode);
            return TypeAheadField<T>(
              textFieldConfiguration: textFieldConfiguration.copyWith(
                enabled: field.control.enabled,
                controller: state._textController,
                style: state.control.enabled
                    ? textFieldConfiguration.style
                    : theme.textTheme.subtitle1!.copyWith(
                        color: theme.disabledColor,
                      ),
                focusNode: focusNode,
                decoration: effectiveDecoration.copyWith(errorText: state.errorText),
                onSubmitted: onSubmitted != null ? (_) => onSubmitted() : null,
              ) as TextFieldConfiguration,
              suggestionsCallback: suggestionsCallback,
              itemBuilder: itemBuilder,
              transitionBuilder: (context, suggestionsBox, controller) => suggestionsBox,
              onSuggestionSelected: (dynamic suggestion) {
                if (selectionToTextTransformer != null) {
                  state._textController.text = selectionToTextTransformer(suggestion);
                } else {
                  state._textController.text = suggestion != null ? suggestion.toString() : '';
                }
                // onSuggestionSelected.call(suggestion);
                // if (valueTransformer!(suggestion) == '') {
                //   controller!.clear();
                // }
                print(valueTransformer!(suggestion));
                field.didChange(valueTransformer(suggestion));

                if (afterValue == true) {
                  state._textController.clear();
                }
                onChanged?.call(suggestion);
              },
              getImmediateSuggestions: getImmediateSuggestions,
              errorBuilder: errorBuilder,
              noItemsFoundBuilder: noItemsFoundBuilder,
              loadingBuilder: loadingBuilder,
              debounceDuration: debounceDuration,
              suggestionsBoxDecoration: suggestionsBoxDecoration,
              suggestionsBoxVerticalOffset: suggestionsBoxVerticalOffset,
              animationDuration: animationDuration,
              animationStart: animationStart,
              direction: direction,
              hideOnLoading: hideOnLoading,
              hideOnEmpty: hideOnEmpty,
              hideOnError: hideOnError,
              hideSuggestionsOnKeyboardHide: hideSuggestionsOnKeyboardHide,
              keepSuggestionsOnLoading: keepSuggestionsOnLoading,
              autoFlipDirection: autoFlipDirection,
              suggestionsBoxController: suggestionsBoxController,
              keepSuggestionsOnSuggestionSelected: keepSuggestionsOnSuggestionSelected,
              hideKeyboard: hideKeyboard,
            );
          },
        );

  @override
  ReactiveFormFieldState<T, String> createState() => _ReactiveTypeaheadFieldState<T>();
}

class _ReactiveTypeaheadFieldState<T> extends ReactiveFormFieldState<T, String> {
  late TextEditingController _textController;
  FocusNode? _focusNode;
  late FocusController _focusController;

  FocusNode get focusNode => _focusNode ?? _focusController.focusNode;

  @override
  void initState() {
    super.initState();

    final initialValue = value;
    _textController = TextEditingController(text: initialValue == null ? '' : initialValue.toString());
  }

  @override
  void subscribeControl() {
    _registerFocusController(FocusController());
    super.subscribeControl();
  }

  @override
  void unsubscribeControl() {
    _unregisterFocusController();
    super.unsubscribeControl();
  }
  //
  // @override
  // void onControlValueChanged(dynamic value) {
  //   final effectiveValue = (value == null) ? '' : value.toString();
  //   _textController.value = _textController.value.copyWith(
  //     text: effectiveValue,
  //     selection: TextSelection.collapsed(offset: effectiveValue.length),
  //     composing: TextRange.empty,
  //   );
  //
  //   super.onControlValueChanged(value);
  // }
  //
  // @override
  // ControlValueAccessor<dynamic, dynamic> selectValueAccessor() {
  //   if (control is FormControl<int>) {
  //     return IntValueAccessor();
  //   } else if (control is FormControl<double>) {
  //     return DoubleValueAccessor();
  //   } else if (control is FormControl<DateTime>) {
  //     return DateTimeValueAccessor();
  //   } else if (control is FormControl<TimeOfDay>) {
  //     return TimeOfDayValueAccessor();
  //   } else if (control is FormControl<Relation>) {
  //     return RelationShipValueAccessor();
  //   }
  //
  //   return super.selectValueAccessor();
  // }
  //
  void _registerFocusController(FocusController focusController) {
    _focusController = focusController;
    control.registerFocusController(focusController);
  }

  void _unregisterFocusController() {
    control.unregisterFocusController(_focusController);
    _focusController.dispose();
  }

  void _setFocusNode(FocusNode? focusNode) {
    if (_focusNode == focusNode) {
      return;
    } else if (focusNode == null && _focusNode != null) {
      _focusNode = null;
    } else if (focusNode != null && _focusNode == null) {
      _focusNode = focusNode;
    }

    _unregisterFocusController();
    _registerFocusController(FocusController(focusNode: _focusNode));
  }
}


```

Custom Relation ControlValueAccessor

```
/// Represents a control value accessor that convert between data types
/// [Relation] and [String].
class RelationShipValueAccessor<T> extends ControlValueAccessor<Relation, String> {
  @override
  Relation? viewToModelValue(String? viewValue) {
    return (viewValue == null || viewValue == null) ? null : Relation(id: viewValue, name: '');
  }

  @override
  String? modelToViewValue(Relation? modelValue) {
    return modelValue == null ? null : modelValue.name;
  }
}
```

i expected **{status: 2, source: 1, source_ref_type: suppliers, source_ref_id: 6, source_ref_text: , assigned: 1, email: testing@gmail.com}** 

but return : **{status: 2, source: 1, source_ref_type: suppliers, source_ref_id: Instance of 'Relation', source_ref_text: , assigned: 1, email: testing@gmail.com}**

**Comment by kuhnroyal** [comment]
Couple thing I can see off the spot.
1.  Your `RelationShipValueAccessor` doesn't seem to need the generic type `<T>`
2. Your `viewToModelValue` sets the `Relation.id` but the `modelToViewValue` use `Relation.name` - that won't work 
3. `(viewValue == null || viewValue == null)` doesn't make sense

**Comment by nousath** [comment]
Changed but not accept. I request make me some sample scripts.

![2021-04-09_15-41](https://user-images.githubusercontent.com/25167886/114165486-2c03ac80-994a-11eb-811f-beb690a3c1ab.png)
![Screenshot from 2021-04-07 11-39-33](https://user-images.githubusercontent.com/25167886/114165491-2d34d980-994a-11eb-8a72-5522dda9e10c.png)

**Comment by kuhnroyal** [comment]
Well, see 2. - if you want to return a `Relation` then you somehow need to build it. Nobody here knows what the `viewValue` is. An ID, a name? Only you know this, only you can construct the correct `Relation`.
There are several implemented accessors in the library that serve as fine samples.

**Comment by nousath** [comment]
Thank you for Response @kuhnroyal @joanpablo
