### ISSUE TITLE
Custom validator type changed in null safety release 

### ISSUE THREAD

**Issue by cezaryjk** [joanpablo/reactive_forms#135]
Hi @joanpablo, 

Just for records (and others dealing with it)
It looks like custom validator type changed in null safety version from 
Map<String, dynamic> 
to
Map<String, Object>?
or
ValidatorFunction

Casting doesn't work since there is a check verifying if all validator are of ValidatorFunction type.

BR
Cezary

**Comment by joanpablo** [comment]
Hi @cezaryjk,

Yes I was thinking to move it again to **Map<String, dynamic>** but could you please tell me if you have any issue right now??

**Comment by cezaryjk** [comment]
Hi again,
No more issues. I just had to update old declarations.
That's all :) .

BR
Cezary

niedz., 11 kwi 2021, 15:51 użytkownik Joan Pablo ***@***.***>
napisał:

**Comment by joanpablo** [comment]
Hi @cezaryjk,

Do you think is better to leave it as Map<String, dynamic>  ??

**Comment by kuhnroyal** [comment]
There is a fine difference. `dynamic` can be null but `Object` can not. If it should not be null, don't change it back.

**Comment by joanpablo** [comment]
> There is a fine difference. `dynamic` can be null but `Object` can not. If it should not be null, don't change it back.

Good point @kuhnroyal Thanks.

**Comment by cezaryjk** [comment]
Hi @joanpablo, 
Well, I'm not that wise, but in my opinion using Object is more soundness in safety context having in mind what @kuhnroyal said.

Have a nice week!
BR
Cezary

**Comment by joanpablo** [comment]
I will define it as dynamic in the next release instead of Object. That will cover more use cases, null and not null.
