### ISSUE TITLE
Must provide a valueAccessor for field ReactiveTextField<dynamic> as ModelDataType and ViewDataType don't match.

### ISSUE THREAD

**Issue by stact** [joanpablo/reactive_forms#136]
Hi

Migrating current app to null-safety got this prob

```
======== Exception caught by widgets library =======================================================
The following assertion was thrown building RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#2c7a1](state: RawGestureDetectorState#6ef01(gestures: <none>, behavior: opaque)):
Must provide a valueAccessor for field ReactiveTextField<dynamic> as ModelDataType and ViewDataType don't match.
'package:reactive_forms/src/widgets/reactive_form_field.dart':
Failed assertion: line 148 pos 7: 'ModelDataType == ViewDataType'
```

We have a simple statefull widget:
```dart
import [...]

class GroupsAddView extends StatefulWidget {
  GroupsAddView({Key? key}) : super(key: key);

  @override
  _GroupsAddViewState createState() => _GroupsAddViewState();
}

class _GroupsAddViewState extends State<GroupsAddView> {
  FormGroup formGroup = FormGroup({
    '_title': FormControl<String>(
      validators: [Validators.required],
    ),
    '_description': FormControl<String>(),
  });

  @override
  Widget build(BuildContext context) {
    return ReactiveForm(
      formGroup: formGroup,
      child: Scaffold(
        body: CustomScrollView(
          slivers: <Widget>[
            CustomSliverAppBar(
              title: "Add a group",
            ),
            SliverToBoxAdapter(
              child: Padding(
                padding: EdgeInsets.all(16.0),
                child: Wrap(
                  spacing: 20.0,
                  runSpacing: 20.0,
                  children: <Widget>[
                    ReactiveTextField(
                      formControlName: '_title',
                      decoration: InputDecoration(labelText: "Name"),
                      onSubmitted: () => formGroup.focus('_description'),
                    ),
                    ReactiveTextField(
                      formControlName: '_description',
                      decoration: InputDecoration(labelText: "Description"),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

```

Do you have the same problem? Does the code need to be updated? (I've checked the doc and it seems that we aligned with)

Additional info:
pubsec version: `reactive_forms: ^10.0.4`
flutter doctor: 
```
Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.55.1)
[√] Connected device (3 available)

• No issues found!

```

Thanks for your help!

**Comment by kuhnroyal** [comment]
@joanpablo I'm afraid that this may be caused by #132
The data type is `dynamic` which doesn't match `String` so it is not using the default accessor. We could probably add a check for dynamic and try to use the default accessor but that could also result in a runtime error.

@stact You can probably work around this by using `ReactiveTextField<String>`.

**Comment by stact** [comment]
Yes the workaround is working. Thx! Best support ever!

**Comment by stact** [comment]
Let's wait #132 to resolve the issue definetively

**Comment by joanpablo** [comment]
Hi @kuhnroyal, I guess we should remove the **assert** or go back to **ControlValueAccessor<dynamic, dynamic>**.
I think that removing the assertion does the job. I will remove it for the next release, what do you think?

**Comment by kuhnroyal** [comment]
Well I am not so sure, I think that will just throw another error in some.

Could try `ModelDataType == ViewDataType || ModelDataType == dynamic` as assert.
There is also no test case for `ReactiveTextField<dynamic>`.

**Comment by joanpablo** [comment]
Hi @kuhnroyal,

I have removed the assert and added a test case for *ReactiveTextField<dynamic>* in this new version v10.1.0.

If you find any other issues let me know as soon as possible. 

Best regards

**Comment by stact** [comment]
@joanpablo I've removed the workaround `ReactiveTextField<String>` to use use only `ReactiveTextField()`

No issue on compilation and usage with 10.1.0. I let you know if I find a related issue.

**Comment by stact** [comment]
@joanpablo Unfortunatelly I need to cast other kind of values : DateTime, TimeOfDay, int, bool etc. (working only for String)

Sample:
```dart
FormGroup formGroup = FormGroup({
  '_eTimeOfDay': FormControl<TimeOfDay>(value: TimeOfDay.now(), validators: [Validators.required]),
});

ReactiveTextField<TimeOfDay>(
  formControlName: '_eTimeOfDay',
  readOnly: true,
  decoration: InputDecoration(
    labelText: 'Hour',
    suffixIcon: ReactiveTimePicker(
      formControlName: '_eTimeOfDay',
      builder: (context, picker, child) {
        return IconButton(
          onPressed: picker.showPicker,
          icon: Icon(Icons.access_time),
        );
      },
    ),
  ),
),
```

**Comment by stact** [comment]
The cast is normal, we declare FormGroup casted and we display text field casted, it's not really a problem.
Just we don't have this information in the readme.md doc.

Maybe we need to force type T on ReactiveTextField and FormControl?

**Comment by kuhnroyal** [comment]
> Maybe we need to force type T on ReactiveTextField and FormControl?

Not sure this is possible but it would be great if we can simply forbid `dynamic` somehow.
Maybe `<T extends Object>`?

**Comment by joanpablo** [comment]
Hi @stact,

I have release v10.2.0 with that fix. Now you don't need to explicitly specify the data type when defining the ReactiveTextField. you can just write ReactiveTextField<dynamic>, ReactiveTextField and use String, double, DateTime, etc in the data type of the control.

Please check the new version and let me know to close the issue or fix something missing.

Thanks and best regards

**Comment by stact** [comment]
It's working thx!
