### ISSUE TITLE
Add onEditingComplete to ReactiveTextField

### ISSUE THREAD

**Issue by naamapps** [joanpablo/reactive_forms#139]
Hey,
Just noticed that there is no option to pass `onEditingComplete` to a ReactiveTextField.
Please add it,
Thanks :)

**Comment by vasilich6107** [comment]
@naamapps `ReactiveTextField` supports custom `focusNode`
When field looses focus it could be a sign of editing complition

Could you describe your use case more verbose?

**Comment by naamapps** [comment]
@vasilich6107 well it's built into flutter native `TextField` so I suppose there's a difference.
I need it to focus another input that doesn't exist yet (a dynamic list of inputs) without closing the keyboard.
`onSubmitted` closes the keyboard and it is not what I want.

**Comment by joanpablo** [comment]
Hi @naamapps,

In the example folder of the project, in the complex example, we use **onSubmitted** to move focus between several *ReactiveTextFields*, and the behavior is that the keyboard never hides, but the focus jump from one TextField to another.

So I'm not clear yet about the issue. Could you post a dart file with the code so I can include it in an application and test what you want to achieve?

Thanks

**Comment by naamapps** [comment]
@joanpablo,
As far a I know the default `onEditingComplete` dismisses the keyboard automatically, so overriding it stops this behavior. 

And I think it is better to give the developer an option to override all of flutter's `TextField` properties, even if you think it's not important or unnecessary.

I hope you understand
Thanks

**Comment by joanpablo** [comment]
Hi @naamapps,

You are right about giving the developer the option to decide, I completely agree with you. I think it will not harm any feature if I include it in the next release.

Thanks

**Comment by joanpablo** [comment]
Hi @naamapps,

The latest version that I have just released v 10.3.0, includes this new callback in the **ReactiveTextField**.

Don't hesitate to reopen the issue or create e new one if something else is missing.

Thanks for your support, and best regards
