### ISSUE TITLE
Detect if a field has changed

### ISSUE THREAD

**Issue by kerbo** [joanpablo/reactive_forms#142]
I need the ability to "save" a field that has been validated and changed. 

The ReactiveTextField has "onSubmitted" which works but no other controls have an equivalent function. 

Ideally it would be better if I could check if a value changes in the FormGroup model. Maybe add an "onChanged" event?

**Comment by naamapps** [comment]
@kerbo You can listen to `valueChanges` stream in the form control.

**Comment by kerbo** [comment]
Can you provide an example or point me to some docs that show how this works?

**Comment by naamapps** [comment]
@kerbo 
```
formControl.valueChanges.listen((dynamic value) {
   // Here you can anything you want when the value changes.
});
```
Hope that helps

**Comment by joanpablo** [comment]
Hi @kerbo,

As @naamapps  metioned you have the **valueChanges**, and also you can know if a control has changed using the properties: **dirty** or **pristine** of any *AbstractControl* (FormGrop, FormControl, FormArray)

Could you argue more about what you want to achieve?

Best regards

**Comment by joanpablo** [comment]
Hi @kerbo,

Have you already resolved your issue? I haven't heard from you for a while. Please let me know.

Best regards

**Comment by kerbo** [comment]
valueChanges works.
