### ISSUE TITLE
Problem Validation not required fields

### ISSUE THREAD

**Issue by agares29** [joanpablo/reactive_forms#147]
I have a field with this validations

```
validators: [
  Validators.minLength(10),
  Validators.maxLength(10),
  Validators.number,
],
```

The problem that I'm facing is that the field is not required, so it could be empty, but when the field gets empty, it shows the validation error.

Does any body know how to handle it? :(

**Comment by joanpablo** [comment]
Hi @agares29,

Thanks for the issue. When the control gets empty then the value is an empty String "". So you have added a validator that validates that the length of the String must be >= 10. It's a normal behavior that the control is marked as invalid. You can assign NULL to the control and that will not trigger the Validators.minLength.

I guess that what you are looking for is the following combination of validators:

```dart
final control = FormControl<String>(
   value: '1234567890',
   validators: [
      Validators.composeOR([
         Validators.equals(''),
         Validators.compose([
            Validators.minLength(10),
            Validators.maxLength(10),
            Validators.number,
         ]),
      ]),
   ],
);
```

**Comment by joanpablo** [comment]
Hi @agares29,

Have you resolved your issue already? Please let me know. 

Best regards.

**Comment by agares29** [comment]
Sorry for the late response, but I've been struggling with the covid shit.

Yeah, that worked, thank you for your help :)

**Comment by joanpablo** [comment]
Hi @agares29,

Thanks for your reply. And I'm glad that you are well or better after the covid. If you have any other questions don't hesitate to open another issue. 

Best regards.
