### ISSUE TITLE
Add more customizability to built-in widgets [enhancement]

### ISSUE THREAD

**Issue by jans-y** [joanpablo/reactive_forms#149]
Hi, 👋

Thank you for this plugin. Coming from Angular I really like your implementation for Flutter.

I would like to propose adding more customizability options to built-in widgets. It would be nice to have all the built-in properties available through your wrappers.

For example, in _ReactiveRadioListTile_ I lacked: **contentPadding** and **toggleable**.

I would create a Pull request but I am not really familiar with Github and PRs here.

Thank you! 🙏

**Comment by joanpablo** [comment]
Hi @jans-y,

Thanks for your issue. I will add those properties in the next release.

Best regards

**Comment by joanpablo** [comment]
Hi @jans-y,

I have just released version 10.3.0. In this version, I have added more properties to ReactiveRadioListTile and ReactiveRadio, including those that you mention in your issue.

Please test the latest version and don't hesitate to reopen the issue or create e new one.

Best regards

**Comment by jans-y** [comment]
Thank you, I really appreciate it. 🙏
