### ISSUE TITLE
font size in ReactiveDropdownSearch

### ISSUE THREAD

**Issue by rodriger06** [joanpablo/reactive_forms#152]
Hi, I would like to know how to change the font size in ReactiveDropdownSearch for the selected items and for the list of items in the popup.  I tried using style like
```
  style: TextStyle(
          fontSize: 20,
      ),
```
but ReactiveDropdownSearch  doesnt recognize it.

here is my code
```
Widget frequencyField(BuildContext context) {
    return  ReactiveDropdownSearch<String>(
      formControlName: frequencyLabel,
      mode: ReactiveDropdownSearchMode.DIALOG,
      items: ["Weekly", "Bi-Weekly", "Monthly", 'Quarterly', 'Yearly', 'One Time'],
     
      decoration: InputDecoration(
        border: new OutlineInputBorder(
            borderSide: new BorderSide(color: Colors.teal)),
        // labelText: incomeAmount,
        prefixIcon: Icon(Icons.refresh),
        contentPadding: EdgeInsets.fromLTRB(0,6.5,0,6.5),
        labelStyle: TextStyle(fontSize: text_size_18),
      ),
      label: frequencyLabel,
      showSearchBox: true,
      popupTitle: Container(
        height: margin_50dp,
        decoration: BoxDecoration(
          color: Theme.of(context).primaryColorDark,
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(10),
            topRight: Radius.circular(10),
          ),
        ),
        child: Center(
          child: Text(
            frequencyLabel,
            style: TextStyle(
              fontSize: 24,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
        ),
      ),
      popupShape: RoundedRectangleBorder(
        borderRadius: BorderRadius.circular(margin_10dp),
      ),
    );
  }
```
take a look at the pics attached at the text circled in red.  I want to increase the font size of the selected item as well as the items in the popup screen

<img width="184" alt="freq_font_increase" src="https://user-images.githubusercontent.com/49496303/119073324-15298e80-b9bb-11eb-91e9-533d411f2c42.PNG">

<img width="183" alt="freq_font_increase2" src="https://user-images.githubusercontent.com/49496303/119073343-1f4b8d00-b9bb-11eb-828c-8902d619eb40.PNG">

**Comment by vasilich6107** [comment]
Hi.
I answered you question https://github.com/artflutter/reactive_forms_widgets/issues/13#issuecomment-846608241

It is not the best practice to duplicate issues. 
I describe shortly how to act next time if you'll have any widget specific questions here https://github.com/artflutter/reactive_forms_widgets/issues/13#issuecomment-846608711

**Comment by vasilich6107** [comment]
@joanpablo this issue could be closed
