### ISSUE TITLE
10.3.0 requires Flutter 2.2.0

### ISSUE THREAD

**Issue by kuhnroyal** [joanpablo/reactive_forms#153]
This is not a bug, just a request for documentation.
Due to the use of `MouseCursor` in `ReactiveRadio` the 10.3.0 release does not work with pre-2.2.0 releases.

**Comment by joanpablo** [comment]
Yeap, @kuhnroyal you are right, I need to specify these break changes in the doc. Thanks

**Comment by joanpablo** [comment]
Hi @kuhnroyal,

I have released version 10.4.0 that specifies the FLutter version in Documentation (Readme) please let me know if it is OK like that.

Best regards.

**Comment by kuhnroyal** [comment]
I would still
