### ISSUE TITLE
Error: Type 'MouseCursor' not found. | Error: 'MouseCursor' isn't a type.

### ISSUE THREAD

**Issue by Zacharias02** [joanpablo/reactive_forms#154]
I found these errors after migrating to version 10.3.0 causing crash during building the app.

![image](https://user-images.githubusercontent.com/52057825/119230340-57370980-bb4e-11eb-9cba-2a03092c8f96.png)

**Comment by joanpablo** [comment]
Hi @Zacharias02,

Yeap you are right, my fault, I need to specify in the documentation that this is because of the upgrade to Flutter 2.2 that has this braking changes.

**Comment by joanpablo** [comment]
Maybe I will release one without the cursor, and the other with the MouseCursor and the specification in documentations

**Comment by francipvb** [comment]
> Maybe I will release one without the cursor, and the other with the MouseCursor and the specification in documentations

You can release a 10.0.2 branch with updates and add the constraint to stop installing before flutter 2.2.

**Comment by joanpablo** [comment]
Hi @francipvb and @Zacharias02,

I have released version 10.4.0 that specifies the FLutter version in Documentation (Readme) please let me know if it is OK like that.

Best regards.
