### ISSUE TITLE
Dynamic list of ReactiveTextField does not update the value when an item is removed

### ISSUE THREAD

**Issue by rooque** [joanpablo/reactive_forms#156]
Hello!

I am trying to implement a relatively simple behavior, a dynamic list of strings. In this list I can add new elements dynamically and delete any item from the list. However I am having a problem, when I delete an item other than the last one I am observing strange behavior. The values ​​are not updated on the screen despite making sure that the right form control and list item is cleared. So when I click to remove an item from the middle of the list, it gives the impression that it removed the last one but it removed the correct one, only the values ​​of the screen that have not been updated

Am I doing something wrong or could this be a bug?

<img src="https://user-images.githubusercontent.com/8527149/119546064-deac9480-bd69-11eb-8da0-bc707a5c6d7e.gif" width="300">

<details>
  <summary>pubspec.yaml</summary>

```yaml
name: app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  reactive_forms: 10.3.0
  get: 4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

```

</details>

<details>
  <summary>example</summary>

```dart
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:reactive_forms/reactive_forms.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    Get.put(HomeController());
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyString {
  String s;
  MyString({
    required this.s,
  });
}

class HomeController extends GetxController {
  var myList = <MyString>[].obs;

  var formGroup = fb.group({'list': fb.array([])});

  FormArray get formArray => formGroup.control('list') as FormArray;

  void remove(MyString s) {
    var i = myList.indexOf(s);

    // this remove the right item but the valeu is't updated
    formArray.removeAt(i);

    // this disable the right item and update the right item
    //formArray.control(i.toString()).markAsDisabled();

    myList.remove(s);
  }

  void add(MyString s) {
    formArray.add(FormControl<String>(value: s.s));
    myList.add(s);
  }
}

class MyHomePage extends GetView<HomeController> {
  List<Widget> get list {
    return controller.myList.map((e) => formText(e)).toList();
  }

  Widget formText(MyString s) {
    var i = controller.myList.indexOf(s);
    return Container(
      child: Row(
        children: [
          Expanded(
            child: ReactiveTextField(
              formControlName: 'list.$i',
            ),
          ),
          Expanded(
              child: ElevatedButton(
                  onPressed: () {
                    controller.remove(s);
                  },
                  child: Text('-')))
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: Obx(
      () => ReactiveForm(
        formGroup: controller.formGroup,
        child: Center(
          child: Column(
            children: [
              ...list,
              ElevatedButton(
                  onPressed: () {
                    controller
                        .add(MyString(s: Random().nextInt(100).toString()));
                  },
                  child: Text('+'))
            ],
          ),
        ),
      ),
    ));
  }
}

```

</details>

<details>
  <summary>flutter doctor</summary>

```
[✓] Flutter (Channel stable, 2.2.0, on macOS 11.1 20C69 darwin-x64, locale
    pt-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.56.2)
[✓] Connected device (1 available)
```

</details>

**Comment by joanpablo** [comment]
Hi @rooque,

Thanks for using Reactive Forms, and sorry for the late answer.

You are removing from the FormArray, but you are not listening for **valueChanges**. You must use a **ReactiveFormArray** or a **ReactiveValueListenableBuilder** and listen for changes in the value of the array or the Form. 

The value does change, but you are not listening for these changes.

If you need a complete example let me know.

Best regards.

**Comment by rooque** [comment]
> Hi @rooque,
> 
> Thanks for using Reactive Forms, and sorry for the late answer.
> 
> You are removing from the FormArray, but you are not listening for **valueChanges**. You must use a **ReactiveFormArray** or a **ReactiveValueListenableBuilder** and listen for changes in the value of the array or the Form.
> 
> The value does change, but you are not listening for these changes.
> 
> If you need a complete example let me know.
> 
> Best regards.

@joanpablo Thank you for creating this awesome lib!

Tried to use **ReactiveValueListenableBuilder**, but no luck ... got the same result :(


<details>
  <summary>sample code</summary>

```dart
import 'dart:math';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:reactive_forms/reactive_forms.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    Get.put(HomeController());
    return GetMaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyString {
  String s;
  MyString({
    required this.s,
  });
}

class HomeController extends GetxController {
  var myList = <MyString>[].obs;

  var formGroup = fb.group({'list': fb.array([])});

  FormArray get formArray => formGroup.control('list') as FormArray;

  void remove(MyString s) {
    var i = myList.indexOf(s);

    // this remove the right item but the valeu is't updated
    formArray.removeAt(i);

    // this disable the right item and update the right item
    //formArray.control(i.toString()).markAsDisabled();

    myList.remove(s);
  }

  void add(MyString s) {
    formArray.add(FormControl<String>(value: s.s));
    myList.add(s);
  }
}

class MyHomePage extends GetView<HomeController> {
  List<Widget> get list {
    return controller.myList.map((e) => formText(e)).toList();
  }

  Widget formText(MyString s) {
    var i = controller.myList.indexOf(s);
    return Container(
      child: Row(
        children: [
          Expanded(
            child: ReactiveTextField(
              formControlName: 'list.$i',
            ),
          ),
          Expanded(
              child: ElevatedButton(
                  onPressed: () {
                    controller.remove(s);
                  },
                  child: Text('-')))
        ],
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: ReactiveForm(
        formGroup: controller.formGroup,
        child: Center(
          child: ReactiveValueListenableBuilder(
            formControlName: 'list',
            builder: (_, __, ___) => Column(
              children: [
                ...list,
                ElevatedButton(
                    onPressed: () {
                      controller
                          .add(MyString(s: Random().nextInt(100).toString()));
                    },
                    child: Text('+'))
              ],
            ),
          ),
        ),
      ),
    );
  }
}

```
</details>

**Comment by joanpablo** [comment]
Hi @rooque,

Your example and Reactive Forms are working correctly, but to see the effects you need to make a small tweak. Because you are first removing from the **FormArray**:

```dart
// this remove the right item but the valeu is't updated
formArray.removeAt(i);
```

it will trigger the **valueChanges** correctly, and because you are listen to the changes with the **ReactiveValueListenableBuilder** your widget will rebuild correctly...... But....... :) ........ you are building your widget based on the variable **myList** which has not been yet updated (you have not removed the element yet from this list). So your widget is going to build again using all the items of the **myList** variable (including the item that you removed from the FormArray but not yet removed from myList).

So the simple change you need to do is:

Fisrt remove from **myList** and then remove from **formArray** to trigger the rebuild. That's all.

Let me know your results.
Best Regards

**Comment by joanpablo** [comment]
@rooque another suggestion is to use **ReactiveFormArray** instead of **ReactiveValueListenableBuilder** like this:

```dart
return Scaffold(
      body: ReactiveForm(
        formGroup: controller.formGroup,
        child: Center(
          child: ReactiveFormArray<String>(
            formControlName: 'list',
            builder: (context, formArray, child) => Column(
              children: [
                ...list,
                ElevatedButton(
                  onPressed: () {
                    controller
                        .add(MyString(s: Random().nextInt(100).toString()));
                  },
                  child: Text('+'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
```

and change the name of the control boud to the text field in the **fromText** method from this:  
```dart
child: ReactiveTextField(
   formControlName: 'list.$i',
),
```

to this:
```dart
child: ReactiveTextField(
   formControlName: '$i',
),
```

**Comment by rooque** [comment]
@joanpablo 

Like these?

```dart
void remove(MyString s) {
    var i = myList.indexOf(s);
    myList.remove(s);
    formArray.removeAt(i);
}
```

Tried and got same result.

Also tried to change how the list is built

```dart
List<Widget> get list {
    return controller.formArray.controls.map((e) {
      var i = controller.formArray.controls.indexOf(e);
      return formText(controller.myList[i]);
    }).toList();
  }
```

And got the same result.

**Comment by joanpablo** [comment]
What version of Reactive FOrms you are using?

Can you send me a simple project with these code so I can run it and see it in action?

**Comment by joanpablo** [comment]
Or better you can clone the Reactive Forms git repo, and run the example Project. There you are going to have an Array Sample. These Array Sample add items but does not remove them. But I will send you the code to remove items, the same code I'm testing right now and you will see it working correctly. In future versions I will include in the sample the option to remove them.

So wich way do you prefer? Send me a working sample small project, or clone the repo run the example folder and I will send you the code to include the *remove* functionality?

**Comment by rooque** [comment]
> What version of Reactive FOrms you are using?
> 
> Can you send me a simple project with this code so I can run it and see it in action?

I published it here: https://github.com/rooque/reactive_forms_issue156_sample/

**Comment by joanpablo** [comment]
Wait, I will update the sample project with the option to remove items and you will clone the git repo, switch to **develop** branch and run the sample project. You will have and example of adding and removing items from the FormArray. Give a few minutes.

**Comment by joanpablo** [comment]
I will try your code right now

**Comment by rooque** [comment]
Also, I'm running it on web, forgot to mention it earlier

**Comment by joanpablo** [comment]
Well your code in mobile is working just fine, I just add an extra small code to make it work completely fine and is add a **key** to the ReactiveTextFields like this:

```dart
Expanded(
            child: ReactiveTextField(
              key: ObjectKey(s),
              formControlName: 'list.$i',
            ),
          ),
```

See how I add the key as an ObjectKey and pass the same object MyString instance. With this small change the code is working completely fine in mobile.

**Comment by joanpablo** [comment]
I have executed the code with **flutter run** and selected **Chrome** and the code just work fine.

**Comment by joanpablo** [comment]
o problema foi resolvido com este pequeno ajuste? :)

**Comment by rooque** [comment]
@joanpablo Yes, tested it here with the key parameter and worked just fine!

That was definitely the missing piece, How did you found it?

Thanks a lot!

**Comment by joanpablo** [comment]
This is s common issue with Widget Lists (for example a list of Text Fields) in Flutter. I mean is not an issue is the way FLutter works. You need to set a key to items when you add and remove it from a collection, so Flutter can identify them.

**Comment by joanpablo** [comment]
Thanks to you for using Reactive Forms and for the issue, with your issue I realize that I need to include an example of removing items in the Example folder of the project.

**Comment by rooque** [comment]
> This is s common issue with Widget Lists (for example a list of Text Fields) in Flutter. I mean is not an issue is the way FLutter works. You need to set a key to items when you add and remove it from a collection, so Flutter can identify them.

Got it!  

Muito obrigado amigo @joanpablo! Problema resolvido

**Comment by joanpablo** [comment]
Fue un placer ayudarte @rooque . No dudes en volver a escribir si tienes alguna otra duda o problema.
