### ISSUE TITLE
Activate error border on all TextFields

### ISSUE THREAD

**Issue by Fiyiin** [joanpablo/reactive_forms#157]
Thanks for this awesome package. I want to activate and deactivate the error border on all my ReactiveTextFields programmatically. How can I achieve this, something like this:
![Group 7](https://user-images.githubusercontent.com/38258693/119814177-058dd680-bee2-11eb-800f-4004b1164420.png)

**Comment by joanpablo** [comment]
Hi @Fiyiin,

Thanks for using Reactive Forms and for the issue.

Could you argue a little more about what you are trying to accomplish? As far as I understand you want to customize the Theme (Style) of the widget. Reactive widgets like **ReactiveTextField** use inside a traditional TextField, a native widget. So you can apply styles and themes as you do with native widgets.

If you apply a Theme to your application (change styles for example to inputDecorationTheme) these changes will apply to Reactive Forms widgets as well.

Best regards.

**Comment by Fiyiin** [comment]
@joanpablo I'm trying to activate the error borders on the textFields. For example, let's say the password is incorrect, I want the borders of all the textfields to show their error colors, just the way it appears in the screenshot.
Something like calling

**Comment by joanpablo** [comment]
Hi @Fiyiin,

I still don't understand your issue, sorry I will need more explanation or e use case. But I will try to explain how ReactiveTextFields works. 

By default, if the **FormControl** is **invalid** and the **ReactiveTextField** is **touched** (the user clicks on it and then remove focus by clicking another widget for example) then the *borders* of the TextField are going to get the *error color* (red by default) and the error message will appear below the text field (exactly like in your picture).

You can customize when to show the error message and when to show the error borders, for example lets say that we want to show the errors (and error borders) as soon as the FormControl is invalid, then we just supply the **showError** method to the ReactiveTextField:

[Here](https://github.com/joanpablo/reactive_forms#overriding-reactive-widgets-show-errors-behavior) you can read about this feature.

**Comment by Fiyiin** [comment]
> By default, if the **FormControl** is **invalid** and the **ReactiveTextField** is **touched** (the user clicks on it and then remove focus by clicking another widget for example) then the _borders_ of the TextField are going to get the _error color_ (red by default) and the error message will appear below the text field (exactly like in your picture).
> 
Exactly, I want to mimic this behavior from code. 
one use case, when the user clicks on a submit button and the server reports an error, I want all the TextFields to get the error color, but they shouldn't show an error message below them.
Something like
 ```
 if(error){
    // make all textFields show error, but don't
    // show a message below , only change the borders to their 
    // error colors
    form.setError({'':''})
  }
 ```

**Comment by joanpablo** [comment]
Hi @Fiyiin,

Mmm an interesting feature, I understand now. You don't want to show the error message. Just the red borders, but not the message text... I see....

ReactiveTextField is a wrapper to the native TextField widget. The way to *marks* the TextField widget with with an error is to set the [*errorText*](https://api.flutter.dev/flutter/material/InputDecoration/errorText.html) of the InputDecorator with a non null value (the error message). So I think that right now the only way you can go is to set an *empty string* to the error message.

```dart
ReactiveTextField(
    formControlName: 'email',
    validationMessages: (control) => {
       ValidationMessage.required: ''
    },
),
```

**Comment by joanpablo** [comment]
I forgot to mention that **validationMessages** receive a function with the *control* as an argument. Each time the status of the control changes (valid, invalid) this function is going to execute, so you can dynamically update the validation message depending on errors and info (from control or from some other place like for example a controller/bloc/viewmodel/etc).

**Comment by joanpablo** [comment]
Hi @Fiyiin,

Remember also that **FormGroup.marksAllAsTouched** will mark all children as touched and the errors will show up programatically.
