### ISSUE TITLE
next button on numeric keypad

### ISSUE THREAD

**Issue by SogoGolf** [joanpablo/reactive_forms#160]
Thanks for this great library, which we have incorporated into our app(s).

Dumb question I guess - but how do we get a "NEXT" button or arrow on the keyboard when we're using a ReactiveTextField ?

**Comment by SogoGolf** [comment]
actually this seems to do the trick: https://pub.dev/packages/keyboard_actions

**Comment by joanpablo** [comment]
Hi @SogoGolf,

Thanks for using Reactive Forms.

For showing the NEXT button in the keyboard, you can set the **textInputAction** of the text field to **TextInputAction.next**. In Android it works perfect. In IOS I don't remember right now if textInputAction is working, but many developers are using the package that you mentioned **keyboard_actions** for adding extra buttons to the keyboard.

Best Regards.

**Comment by stact** [comment]
Hi @joanpablo is it plan to have this feature natively in flutter reactive_forms? 😁
I've integrated `keyboard_actions` on multiline fields, but it add additional boilerplate and add complexity in our forms 👎
