### ISSUE TITLE
ReactiveValueListenableBuilder does not update value

### ISSUE THREAD

**Issue by liveaffiliates** [joanpablo/reactive_forms#161]
Hi,

Thanks for making this package it is really handy for model driven design.  

I am trying to implement custom widgets for this package and I am having issues. The counter wiki and star rating guide are from an older version of reactive forms. I have got it working by changing a few things but I am not sure if what I am doing is right because the counter visually updates but ReactiveValueListenableBuilder does not update.

These are the changes I made in attempt to get custom widgets working in the latest version:

1. 

I changed the example ReactiveCounter like this:

`ReactiveCounter extends ReactiveFormField<int>` to `class ReactiveCounter extends ReactiveFormField<int,int> `

I also did this for the state as well as the builder. 

2. I also changed the form control in the form group like this:

`final form = FormGroup({
    'counter': FormControl<int>(value: 0),
  });`
 
to

`  final form = FormGroup({
    'counter': FormControl<int>(defaultValue: 0),
  });`

3.

I edited the return value from the value listener to get the stream valu:

` ReactiveValueListenableBuilder(
                formControlName: 'counter',
                builder: (context, counterValue, child) {
                  return Text(counterValue.toString());
                },
              ),`

to

`ReactiveValueListenableBuilder(
     formControlName: 'counter',
     builder: (context, counterValue, child) {
         return Text(counterValue.value.toString());
  },
 ),`

This clears all the errors and the widget for the counter updates but the text for the valuelistener stays at 0. Is this approach even valid with the updates to the library or is there an error in the way I did it.

Thanks 

I have added the entire code below:

```
import 'package:flutter/material.dart';
import 'package:reactive_forms/reactive_forms.dart';

class ReactiveCounter extends ReactiveFormField<int,int> {
  ReactiveCounter({
    @required String formControlName,
  }) : super(
      formControlName: formControlName,
      builder: (ReactiveFormFieldState<int,int> field) {
        return Counter(
          value: field.value,
          onDecrementPressed: () => field.didChange(field.value - 1),
          onIncrementPressed: () => field.didChange(field.value + 1),
        );
      });

  @override
  ReactiveFormFieldState<int,int> createState() => ReactiveFormFieldState<int,int>();
}



class Counter extends StatelessWidget {
  /// The value of the Counter
  final int value;

  /// The callback to notify that the user has pressed decrement button
  final VoidCallback onIncrementPressed;

  /// The callback to notify that the user has pressed increment button
  final VoidCallback onDecrementPressed;

  /// Creates a [Counter] instance.
  /// The [value] of the counter is required and must not by null.
  const Counter({
    @required this.value,
    this.onIncrementPressed,
    this.onDecrementPressed,
  })  : assert(value != null);

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: <Widget>[
        IconButton(
          icon: Icon(Icons.chevron_left),
          onPressed: this.onDecrementPressed, // call on decrement callback
        ),
        Text(this.value.toString()),
        IconButton(
          icon: Icon(Icons.chevron_right),
          onPressed: onIncrementPressed, // call on increment callback
        ),
      ],
    );
  }
}`

```

**Comment by joanpablo** [comment]
Hi @liveaffiliates,

Sorry for the late answer. I have updated the Custom Reactive Counter documentation with the latest version of the package. Thanks for the catch. 

You can check the doc again. Please if you still have any issue running the code let me know.
