### ISSUE TITLE
Sample with GetX Library

### ISSUE THREAD

**Issue by NiranjanShah** [joanpablo/reactive_forms#163]
it will be gr8, if a sample can be provide using GetX Library.

**Comment by vasilich6107** [comment]
@NiranjanShah `reacitve_forms` hadels form state internally 
It is not clear what example are you talking about

**Comment by joanpablo** [comment]
I will close this issue because we don't have any updates about the creator of the issue.

Please @NiranjanShah don't hesitate to open it again or open a new one.

Thanks @vasilich6107
