### ISSUE TITLE
ReactiveRangeSlider

### ISSUE THREAD

**Issue by adiospace** [joanpablo/reactive_forms#166]
Is there a reactive variant of RangeSlider? From what I can see there's only ReactiveSlider which only works with double.

**Comment by vasilich6107** [comment]
@adiospace 
https://pub.dev/packages/reactive_range_slider

**Comment by vasilich6107** [comment]
@joanpablo we can close this issue

**Comment by adiospace** [comment]
Oh, i was pretty sure i looked everywhere 🤣 ty

**Comment by vasilich6107** [comment]
@adiospace haha
You definitely did)
I released it 10 mins ago)

**Comment by vasilich6107** [comment]
@adiospace does it fits your needs?

**Comment by vasilich6107** [comment]
https://pub.dev/packages/reactive_range_slider
@joanpablo we can close this issue

**Comment by vasilich6107** [comment]
@adiospace does it fits your needs?
If it does could you close the issue?

**Comment by joanpablo** [comment]
Hi @adiospace,

Don't hesitate to reopen the issue if it does not fits your needs.
