### ISSUE TITLE
Globally defined validation messages

### ISSUE THREAD

**Issue by jans-y** [joanpablo/reactive_forms#168]
Hi,

Is it possible to globally define validation messages? For example, I would like to set default validation messages instead of generic "required" or "minLength" to sentence in the language in which I am building an app.

Sometimes I don't need custom validation message for every field, generic message will suffice.

Thank you.

**Comment by kuhnroyal** [comment]
Really like the idea!

**Comment by dhsont** [comment]
you can change default error messages,

see  this thread  #164 


you can show by default  generic messages
ex.  Validators.minLength(6) 

`Charactors should be more`


only issue is you can not pas value to messages.  so you cant show it should be greater than 6.
`Value must have a length greater than or equal to 6`

**Comment by joanpablo** [comment]
Hi,

So, as far as I understand you would like to globally configure the default messages for validations, instead of 'required', etc.

But you would also like to define a method/function that receives the error (or the control) and then customize the error message based on the error information. Is that right?

Thanks to all of you for the issue

**Comment by jans-y** [comment]
Hi,

1. Yes, since we are doing app in our domestic language, it seems a little bit tedious to repeat ourselves at every field for simple validations as required, email, etc.
2. Yes, it makes sense to have method/function to have the ability to handle validations with parameters as minLength, maxLength, etc.

Thank you.

**Comment by jasonlaw** [comment]
Any update on this? Would like to have this feature too.

**Comment by joanpablo** [comment]
Hi @jans-y @jasonlaw @kuhnroyal @vasilich6107 @dhsont 

I have release version `14.1.0` of **Reactive Forms**, in which we can define validation messages Globally. You can find documentation [here](https://github.com/joanpablo/reactive_forms#2-globalapplication-level).

Please give it a look and don´t hesitate to create a new issue if you have new suggestions or issues.

Thanks once again for your support.

Please let me know if the new version covers all your needs.
