### ISSUE TITLE
Configuring a disabled 1-FormControl only FormGroup makes the form always invalid

### ISSUE THREAD

**Issue by Frank-D** [joanpablo/reactive_forms#172]
Hi,

I have a super simple forgot password form with only one form control field defined (email). I am receiving the already entered email value form a previous screen, hence, I am prepolutating such form control with that value, and I don't want this control to be editable at this point in the UX flow, hence, I am also making this form control disabled:

```
forgotPasswordForm = FormGroup(
          {
            'email': FormControl<String>(
              value: userEmail,
              disabled: true,
              validators: [Validators.required, Validators.email],
            ),
          },
);
```

The generated UI input control is as expected, pre-populated with such 'userEmail' value, and is also 'disabled', e.g. I can't edit the input. This is great so far.

Problem is, the form is not initialized as "valid" by default from the above code, even though I've provided a predefined 'value' for the only form control the form contains, despite the fact that such 'userEmail' value is not empty and in the right email format, so it passes both defined form control validators.

Because of this, I'm unable to define my Submit button as part of a 'ReactiveFormConsumer', because the submit button is always disabled, since the form is not valid.

So I've instead created a standalone Submit button without any 'ReactiveFormConsumer' context. Now I am able to hit the submit button and access my BLOC logic. Then, inside the BLOC logic, I am checking if the form is valid before calling any backend logic, but again, obviously, the form is still not valid, so the below IF-test always fail, even though I am able to read from that same form and obtain the 'email' formControl value properly..:

```
    if (! state.forgotPasswordForm.valid) {
      emit(state.copyWith(forgotPasswordStatus: ForgotPasswordStatus.invalidEmail));
      return;
    }
```

This problem is 100% related to the fact that I am defining my 'email' form control with "disabled: true". If I remove that, everything is working fine, the form becomes valid etc.

My current alternative solution was to indeed get rid of such "disabled: true" form control config, and instead rely on defining my email 'ReactiveTextField' in the UI with the attribute "readOnly: true". This makes my entire scenario to work (e.g., input textfield with a prepolated value + is disabled / user can not edit the value + form is valid, so I can continue with submitting my backend forgot password logic..), BUT, the UI control when using "readOnly: true" is not the same as when defining the formControl with "disabled: true", I like better the default look & field of the UI textfield when I use the "disabled" formControl attribute, it looks more official to the user that the field is not editable, as opposed to when using the "readOnly" textfield attribute, the look & field of the textfield still looks editable even though it's not, so user might try to click on the field, and thinks it's a bug that it's not editable...

Is there anything I'm doing wrong here or mis-understanding?
thanks

**Comment by joanpablo** [comment]
Hi @Frank-D,

Sorry for the answer to this issue so late, and thanks for using Reactive Forms.

Have you tried to use they **readOnly** property that is present in the **ReactiveTextField**? Don't disable the email control, just use the *readOnly* in the widget.

Let me know if it solves your issue.

**Comment by Frank-D** [comment]
Hi @joanpablo,

No worries. Looking at your answer however, I’m wondering if you have read my previous comment till the end, more specifically the paragraph which starts with “My current alternative solution…” where I actually mentioned that I ended up using such “readOnly” attribute that you are referring to, but as I stated in that previous comment/paragraph, I don’t think the look & feel is right with this approach, since it’s not clear to the user that the field is not editable. So I don’t like this alternative approach which I’m stuck in currently, reason why I had filed this issue:)

thanks

**Comment by joanpablo** [comment]
Hi @Frank-D,

I understand now the issue, what is actually happening is that the Form is in state **disabled** not valid, not invalid, but *disabled*. And that is because all the children controls (just one: email) is disabled. When a Form has all its children as disabled then it turns into disabled.

So maybe you can just continue using your disable *email* control, but in the Submit button don't check for the **VALID** of the form, but instead check if the form is INVALID or PENDING (disable the button if the FOrm is INVALID or PENDING).

**Comment by joanpablo** [comment]
These are the states of the controls:

```dart
/// Enums that represents the different
/// validation status of an [AbstractControl]
///
/// See [AbstractControl.status]
enum ControlStatus {
  /// The control is in the midst of conducting a validation check.
  pending,

  /// The control has passed all validation checks.
  valid,

  /// The control has failed at least one validation check.
  invalid,

  /// This control is exempt from validation checks.
  disabled,
}
```

So in your case the Form is in state **disabled**

**Comment by Frank-D** [comment]
Thanks a lot @joanpablo for your explanation, makes it super easy to understand now what's happening, and why the package logic will consider this form not valid neither invalid, but instead disabled, that's fine..

So I ended up changing my bloc logic (..which handles the form submit action and first validates the form..) from:
```
// BLOC: On form submit, first validate form...
if (!state.forgotPasswordForm.valid || userEmail.isEmpty) {
    // Handle error here...      
    emit(...);
    return;
}
// Form is valid, handle forgot password logic here...
```
to
```
// BLOC: On form submit, first validate form...
if (state.forgotPasswordForm.invalid || state.forgotPasswordForm.pending || userEmail.isEmpty) {
    // Handle error here...      
    emit(...);
    return;
}
// Form is valid, handle forgot password logic here...
```
as you suggested, and it did the trick perfectly.
Thank again
