### ISSUE TITLE
ValueNotifier.notifyListeners() elsewhere in the code causes ReactiveFormFieldState methods to not rebuild the widget

### ISSUE THREAD

**Issue by BenjaminFarquhar** [joanpablo/reactive_forms#179]
```
flutter 2.2.2
reactive_forms: ^10.2.0
```
I have this form:

```
form = FormGroup({
  'nickName': FormControl<String>(validators: [Validators.required]),
  'emailAddress': FormControl<String>(
    validators: [Validators.required],
  ),
  'darkMode': FormControl<bool>(),
});
```
    
When I update the value of the following `ReactiveSwitch` :

```
Expanded(
  flex: 1,
  child: ReactiveForm(
    formGroup: vm.form,
    child: Column([
        ...
        ReactiveSwitch(formControlName:  'darkMode'),
        ...
      ])
```
programmatically like so:

```
void toggleDarkMode() {
  final darkModeValue = form.control('darkMode').value as bool;
  // form.control('darkMode').value = !darkModeValue;
  form.control('darkMode').updateValue(!darkModeValue);
}
```

I only get the animation of the switch changing on the first time doing it. Subsequent changes of the form value do not animate or even visually change the switch between on/off. 

I'm not sure if this is supposed to work, or if this is just not implemented/not going to be implemented?

Cheers!

**Comment by BenjaminFarquhar** [comment]
I should have mentioned I'm also doing this:

```
form.control('darkMode').valueChanges.listen(onDarkModeChange);

  void onDarkModeChange(dynamic value) {
    if (value as bool) {
      AdaptiveTheme.of(context).setDark();
    } else {
      AdaptiveTheme.of(context).setLight();
    }
  }
```

The bug goes away when I remove that code. It will be because `AdaptiveTheme.of(context).setDark();` calls `setState(() {});` around the same time as `form.control('darkMode').value = !darkModeValue` causes a `setState` to happen also. So it is not a bug with any package. I still would like to find a solution to this if anyone knows one. I tried calling the `AdaptiveTheme.of(context).setDark();` inside `WidgetsBinding.instance!.addPostFrameCallback((_) {` and also `Future.delayed(Duration.zero, () {` to try to wait for the next build cycle before it calls `setState` again, however it didn't work.

**Comment by vasilich6107** [comment]
https://user-images.githubusercontent.com/6721286/125626527-bb13b483-aab5-49fe-bdac-c9bc1d714392.mov

**Comment by vasilich6107** [comment]
https://user-images.githubusercontent.com/6721286/125626817-5a7318cd-8890-49ca-bce4-4d10bab7f6bc.mov

**Comment by vasilich6107** [comment]
Create your form inside statefull widget
![image](https://user-images.githubusercontent.com/6721286/125626921-6aa103c9-fbf6-41b4-ae33-267b6db5ffc5.png)

**Comment by vasilich6107** [comment]
Here 
```dart
widget.test();
    setState(() {
      counter += 1;
    });
```

it calls local set state and `widget.test()` which is call back from parent statefull widget also calling set state
and everything seems to work fine

**Comment by BenjaminFarquhar** [comment]
Cheers @vasilich6107. I will try this on my code later. In the mean time I can see that this is not a bug and can work so I have closed.

**Comment by BenjaminFarquhar** [comment]
@vasilich6107  `AdaptiveTheme.of(context).setDark();` and `AdaptiveTheme.of(context).setLight();` cause the `ReactiveFormFieldState` methods:

```
 void _checkTouchedState() {
    if (touched) {
      setState(() {});
    }
  }

  void _onControlStatusChanged(ControlStatus status) {
    setState(() {});
  }

  void _onControlTouchChanged(bool touched) {
    setState(() {});
  } 
```
  
to never execute.
  
I've added code to manually trigger `_onControlStatusChanged` so that it calls `setState`:

```
  void toggleDarkMode() {
    form.control('darkMode').value = !(form.control('darkMode').value as bool);
    form.control('darkMode').markAsDisabled();
    form.control('darkMode').markAsEnabled();
  }
```

It executes this line of `markAsEnabled`:

`_status = ControlStatus.valid;`

and  `_onControlStatusChanged(ControlStatus status)` is not triggered, when it should be as it is listening to a subscription. 

Very weird. I am quite stuck. I need to gain access to the `ReactiveFormFieldState` of the control so that I can manually trigger a rebuild. I don't think we get access to that through using a ReactiveSwitch. I will probably need to just wrap the ReactiveSwitch in a custom control so that I gain access to the `ReactiveFormFieldState` of the control.

**Comment by BenjaminFarquhar** [comment]
@vasilich6107 commenting out `notifyListeners` of `ValueNotifier` causes the ReactiveSwitch to visually toggle. So `notifyListeners` does something funky to the `ReactiveFormFieldState`

```
  @override
  T get value => _value;
  T _value;
  set value(T newValue) {
    if (_value == newValue) return;
    _value = newValue;
    // notifyListeners();
  }
```

**Comment by vasilich6107** [comment]
Could you post a reproducible sample?

**Comment by BenjaminFarquhar** [comment]
I think it will be reproducible if you add a changeNotifier and notifyListeners inside your `onDarkModeChange()`. I will post again when I get a reproducible example without AdaptiveThemes. 

the widget:

```
import 'package:flutter/material.dart';
import 'package:reactive_forms/reactive_forms.dart';
import 'settings_page_vm.dart';

class SettingsPage extends StatelessWidget {
  const SettingsPage();

  @override
  Widget build(BuildContext context) {
    final vm = SettingsPageVm(context: context);
    return ReactiveForm(
        formGroup: vm.form,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          crossAxisAlignment: CrossAxisAlignment.start,
          mainAxisAlignment: MainAxisAlignment.start,
          children: [vm.darkModeWidget],
        ));
  }
}
```

the viewModel:

```
import 'package:adaptive_theme/adaptive_theme.dart';
import 'package:flutter/material.dart';
import 'package:reactive_forms/reactive_forms.dart';

class SettingsPageVm {
  SettingsPageVm({required this.context}) {
    onInitialise();
  }

  final BuildContext context;
  late FormGroup form;
  ReactiveSwitch darkModeWidget = ReactiveSwitch(formControlName: 'darkMode');

  Future<void> onInitialise() async {
    form = FormGroup({
      'darkMode': FormControl<bool>(),
    });

    final themeMode = await AdaptiveTheme.getThemeMode();

    if (themeMode == AdaptiveThemeMode.dark) {
      form.control('darkMode').value = true;
    } else {
      form.control('darkMode').value = false;
    }

    form.control('darkMode').valueChanges.listen(onDarkModeChange);
  }

  void toggleDarkMode(BuildContext context) {
    final darkMode = form.control('darkMode').value as bool;
    form.control('darkMode').value = !darkMode;
  }

  void onDarkModeChange(dynamic value) {
    if (value as bool) {
      AdaptiveTheme.of(context).setDark();
    } else {
      AdaptiveTheme.of(context).setLight();
    }
  }
}


```

**Comment by BenjaminFarquhar** [comment]
Actually I think the bug is on adaptive_theme's end or my usage of it, I can't reproduce this issue without adaptive_theme and I've observed your code working when adaptive_theme is not used. Thanks for looking into this.

**Comment by vasilich6107** [comment]
Your welcome
