### ISSUE TITLE
Can't set default value to ReactiveDropdownField

### ISSUE THREAD

**Issue by izandona** [joanpablo/reactive_forms#183]
Hi everyone, 
I'm trying to initialize the **ReactiveDropdownField** with a default value but I can't find the parameter to do it. In the **DropdownButtonFormField** I used the "value" parameter.

![immagine](https://user-images.githubusercontent.com/42273815/126149067-0f1b9c0c-6e31-4442-9f97-538a259e4be4.png)

**Comment by joanpablo** [comment]
Hi @izandona,

You just need to initialize the FormControl that is bound to the ReactiveDropdownField.

**Comment by izandona** [comment]
So I have to create a "FormControl" with a value field, and that value was the "Default value" of the ReactiveDropdownField?

`FormGroup buildForm = fb.group(<String, dynamic>{
    TowTruckFields.veichleList: FormControl<String>(
      validators: [Validators.required],
      value: "DafaultValue"
    ),
});`

**Comment by joanpablo** [comment]
Hi @izandona,

Yes, you always need a FormGroup with at least a FormControl. That FormControl is bound to the widget. You can check the "example" folder with "complex example"

```dart
fb.group(<String, Object>{
        'rememberMe': false,
      });
```

```dart
ReactiveDropdownField<bool>(
                formControlName: 'rememberMe',
                decoration: const InputDecoration(
                  labelText: 'Want to stay logged in?',
                ),
                items: [
                  const DropdownMenuItem(value: true, child: Text('Yes')),
                  const DropdownMenuItem(value: false, child: Text('No')),
                ],
              )
```

**Comment by izandona** [comment]
Hi @joanpablo, perfect! Thanks

**Comment by joanpablo** [comment]
You're welcome @izandona
