### ISSUE TITLE
Consider adding readOnly flag to FormControl

### ISSUE THREAD

**Issue by kuhnroyal** [joanpablo/reactive_forms#184]
I think it would make sense to add a `readOnly` flag to `FormControl<T>`.

Most Flutter inputs have a readOnly flag, it would be nice if this could be bound directly to the `FormControl` just like the `enabled` flag.

I could probably create a PR if this is something that is interesting for more people.

**Comment by vasilich6107** [comment]
What is the significant difference between `disabled` and `readonly`?

**Comment by vasilich6107** [comment]
> Most Flutter inputs have a readOnly flag

This flutter inputs does not have `readonly` flag
- Checkbox
- CheckboxListTile
- DropdownButton
- Radio
- RadioListTile
- Slider
- Switch
- SwitchListTile

And many more...

I did bindings to all this widgets https://github.com/artflutter/reactive_forms_widgets and I did not notice any need of readonly for `FormControl`

**Comment by kuhnroyal** [comment]
You are right, only text input supports readOnly.
I am looking for a clean way to separate hidden/readOnly fields in the `FormControl`.

Basically there is 2 states that I need in the `FormControl`, but there is no way to do this currently, since there is only the `disabled` flag.
1. the input is displayed but readyOnly (not editable)
2. the input is not displayed

Not sure if that makes sense to solve in `FormControl` or in my code. Maybe I am the only one with this problem :)

**Comment by joanpablo** [comment]
Hi @kuhnroyal,

I'm not sure yet to understand your issue.

1. the input is displayed but readyOnly (not editable) (You could just use the **readOnly** property on the **ReactiveTextField**)
2. the input is not displayed (I guess you want to hide/show the ReactiveTextFIeld. Is that right? Why not just use a [Visibility](https://api.flutter.dev/flutter/widgets/Visibility-class.html) widget to show/hide the Text Widget or any other solution?)

Best regards

**Comment by kuhnroyal** [comment]
Hi @joanpablo,

yes, I can do all that. The problem is knowing when to do that. In large dynamics forms, visibility/read-only/disabled/validation state may depend on data entered in other inputs. And since it is dynamic with tons of fields it is hard to maintain the state myself. It would be best to communicate the state to other `FormControl`s via the `FormControl` itself.

I think a lot of people probably have similar problems but I agree that it is not a good solution to add more bool fields to `FormControl` or `AbstractControl`.

I would like `FormControl` to be the full (and only) state of some input.

**Comment by joanpablo** [comment]
Yeap, you are right, not all the cases are the same.

I will share with you one of my experiences, maybe not the best and it's not applicable to all cases, but it may help anyway.

I once used a FormControl that holds a *boolean* value and I changed this boolean value with a **ReactiveSwitch**. Then I had something like this:

 ```dart
@override
  Widget build(BuildContext context) {
    return ReactiveValueListenableBuilder<bool>(
      // bound to the boolean control
      formControl: viewModel(context).sendSms,
      builder: (context, control, child) {
        return Visibility(
          visible: control.value,
          child: ReactiveTextField(formControl: viewModel(context).smsRecipient)
       );
      }
   )
}
```

This is just a simple example of course.

Anyway, as always we are open to any suggestion. Feel free to think and let us know your thoughts.
