### ISSUE TITLE
Unable to change FormArray value

### ISSUE THREAD

**Issue by combi-35** [joanpablo/reactive_forms#185]
I am trying to update a FormArray value but it's behaving strange.

Flutter version:  2.0.6 
Reactive Form version: 10.2.0

```
FormGroup get formInterest => _form.control('interests') as FormGroup;

final _form = FormGroup({
  'general': FormGroup({
    'title': FormControl<String>(validators: [Validators.required]),
  }),
  'interests': FormGroup({
    'interests': FormArray<String>([], validators: [Validators.required, Validators.minLength(1), Validators.maxLength(3)]),
  }),
});

void setInterests(List<String?> interestsUuid){
  FormArray<String> interests = formInterest.control('interests') as FormArray<String>;
  //interests.reset(value: interestsUuid); // doesn't work
  //interests.updateValue(interestsUuid); // doesn't work
  interests.value = [];
  interests.value = interestUuid;
  notifyListeners();
}
```

I am able to assign values to FormArray but I can't update or reset it.
Even when I pass an empty List to setInterests() it's not resetting.
Am I misunderstanding something with FormArray?

**Comment by joaomantovani** [comment]
Facing the same problem here.

**Comment by joanpablo** [comment]
Hi @combi-35,

Have you tried to pass 
```dart
List<String>
``` 
instead of 
```dart
List<String?>
```
```dart
interests.reset(value: interestsUuid);
```
?

**Comment by joanpablo** [comment]
What exactly you mean with "//interests.reset(value: interestsUuid); // doesn't work"

Are you getting a runtime error? The widget doesn't update the value, or the FormControl doesn't update its value?

**Comment by combi-35** [comment]
Hi @joanpablo,
yes indeed changing from `List<String?>` to `List<String>` does work, but in my case the `List<String?>` I pass to `setInterests` is based on `formInterest.control('interests').value` and value is by defintion `T?`

So I am using something like:
```
void onSelect(Interest value) {
  AddActivityViewModel addActivityVM =
      Provider.of<AddActivityViewModel>(context, listen: false);

  List<String?> selected = addActivityVM.formInterest.control('interests').value;

  if(value.isSelected){
    selected.add(value.uuid);
  } else {
    // need to remove this interest from array
    selected.removeWhere((uuid) => uuid == value.uuid);
  }
  addActivityVM.setInterests(selected);
}
```

```
void setInterests(List<String?> interestsUuid){
  FormArray<String> interests = formInterest.control('interests') as FormArray<String>;
  interests.value = [];
  interests.value = interestUuid;
  notifyListeners();
}
```

Also there was no RuntimeError, the value just won't update.

**Comment by joanpablo** [comment]
Hi @combi-35,

This is a unit test from Reactive Form, and it run successfully. If you go to the folder *test/src/models/form_array_test.dart* you will see a lot of test for the **reset** method in a FormArray. So help me to understand the differences with your code. This is just an example of one of the tests:

```dart
test('Reset array with initial values', () {
      // Given: an array with items with default values
      final array = FormArray<int>([
        FormControl<int>(value: 1),
        FormControl<int>(value: 2),
        FormControl<int>(value: 3),
      ]);

      // And: reset array
      array.reset(value: [4, 5, 6]);

      //Then: items has change values
      expect(array.controls.length, 3);
      expect(array.control('0').value, 4);
      expect(array.control('1').value, 5);
      expect(array.control('2').value, 6);
    });
```

**Comment by combi-35** [comment]
Hi @joanpablo ,
I am sorry I found a bug in my code, I was duplicating everything when writing to `value`.
Thanks for your time!
