### ISSUE TITLE
ReactiveDropdownField select a specific DropdownMenuItem according to the selected value of another ReactiveDropdownField

### ISSUE THREAD

**Issue by jbt-cii** [joanpablo/reactive_forms#186]
Hello,

I have a problem which is near this topic:
https://github.com/joanpablo/reactive_forms/issues/183
But the answer does not help me in my case.

I have 2 ReactiveDropdownField.
When I select a value in the 1st ReactiveDropdownField I would like to select a specific DropdownMenuItem (value and child selected) of another ReactiveDropdownField.

That doesn't work when I change the value of the control of the 2nd ReactiveDropdownField:
```dart
form.control("my_second_field").value = specificValueOfDropdownMenuItem;
```

The value is changed but not the text which appears as selected (child widget of the DropdownMenuItem).
I tried several things but I can't find the way to do that.
Reading the issue #183 I was thinking that changing the value of a control will automatically change the selected text of the ReactiveDropdownField.
What is the good way to do such a thing?

Thank you in advance for any help. :-)

**Comment by vasilich6107** [comment]
@jbt-cii use `updateValue` instead

**Comment by jbt-cii** [comment]
Thank you @vasilich6107 
I have just tried:
```dart
form.control("my_second_field").updateValue(specificValueOfDropdownMenuItem);
```
That doesn't work in my case.
When I control "form.control("my_second_field").value" after, it's OK it has the good value.
But the text printed (selected) in this second field doesn't change.

**Comment by vasilich6107** [comment]
@jbt-cii 
try to react on changes in `buildForm`

I tested the behaviour before posting a suggestion

Here is my code

```dart
FormGroup buildForm() {
    final bottomSheet = FormControl<String>(value: 'Brazil');

    final menu = FormControl<String>(value: 'Tunisia')
      ..valueChanges.listen(
        (e) {
          if (e == 'Brazil') {
            bottomSheet.updateValue('Canada');
            print(e);
          }
        },
      );

    return fb.group(<String, Object>{
      'menu': menu,
      'bottomSheet': bottomSheet,
      'touchSpin': FormControl<double>(value: 10),
      'rate': FormControl<String>(value: 'a'),
      'date': FormControl<DateTime>(value: DateTime.now()),
      'time': FormControl<DateTime>(value: DateTime.now()),
      'dateTime': FormControl<DateTime>(value: DateTime.now()),
    });
  }
```

**Comment by jbt-cii** [comment]
Ok I found the problem.
In fact this way was enough:
```dart
form.control("my_second_field").value = specificValueOfDropdownMenuItem;
```

The problem came from the fact I did not put a specific format to my controls.
So for each field declared in my 'FormGroup' I hed to declare the control like:
```dart
    form = FormGroup({
      'my_first_field': FormControl<String>(),
      'my_second_field': FormControl<String>(),
    });
```

And also I had to declare my "DropdownMenuItem" like this:
```dart
...
        menuItems.add(DropdownMenuItem(
          // value: int.parse(key), => old declaration
          value: key.toString(),
          child: Text(
            v,
            style: TextStyle(
              fontSize: 20.0,
              color: Theme.of(context).accentColor,
            ),
          ),
          onTap: () => setState(() {
            // this._onChanged!(int.parse(key));
            this._onChanged!(key.toString());
          }),
        ));
...
```

With that it seems to be good!

Thanks for the help.
