### ISSUE TITLE
Documentation conflicts with reality

### ISSUE THREAD

**Issue by vasilich6107** [joanpablo/reactive_forms#192]
Hi @joanpablo 

In this chapter https://github.com/joanpablo/reactive_forms#reactiveform-vs-reactiveformbuilder-which-one
stated

```
The main differences are that ReactiveForm is a StatelessWidget
```

But in reality `ReactiveForm` is also `StatefullWidget`

https://github.com/joanpablo/reactive_forms/blob/master/lib/src/widgets/reactive_form.dart#L16

**Comment by joanpablo** [comment]
Hi @vasilich6107,

mmmm, at the beginning this widget was Stateless, and now it is Stateful, interesting!!!

I need to check why it is now Stateful.

Thanks for the warning.

**Comment by joanpablo** [comment]
Hi @vasilich6107 ,

I have release 10.6.2 with the ReactiveForm as a Stateless widget, please test any project or sample you have to validate that it works as expected. 

Thanks
