### ISSUE TITLE
How to run Validators for array group and for each form control item?

### ISSUE THREAD

**Issue by vasilich6107** [joanpablo/reactive_forms#200]
Hi @joanpablo 
I have a form with emails.
I can add infinite amount

I want to run validator at form array level to ensure that there is no duplicates in added items
Also I want to run an `emailValidator` to ensure that each field is valid email.

It does not seem that `reactive_forms` runs nested validators
Do you have any ideas how to solve this?

**Comment by vasilich6107** [comment]
i've found an answer
you need to manually run the validations addition tin `FormArray` validator

**Comment by joanpablo** [comment]
You can create a Custom Validator that evaluates the FormArray each time you add or remove an item. Inside the Custom Validator you can check that each item is unique and use the built-in EmailValidator to check that each control is a valid Email.

I guess that your code above will works fine if you place it inside a Custom validator and if you add the extra check of unique values.

**Comment by vasilich6107** [comment]
Yep - it already works)

**Comment by vasilich6107** [comment]
Hi @joanpablo quick question

I noticed that `FormArray` does not run validations of nested controls.

For example 

`FormGroup` of `FormGroup's` -> runs validations for all elements down to the last `FormControl`
If I have `FormArray` of `FormGroup's` or `FormArray` of `FormControl's` it runs only validations at `FormArray` level.

Do you need reproduction sample?

**Comment by joanpablo** [comment]
Hi @vasilich6107,

I don't understand your issue, could you give me an example? And I'm seen you have closed the issue, is that mean that you solved your issue?

**Comment by vasilich6107** [comment]
I will prepare demo for you.
I closed the issue cause I somehow solved it.
But while writing doc samples for generator I noticed that behaviour differs between `FormArray` of `FormGroups` and `FormGroup` of `FormGroups`

I will prepare sample and open new issue
