### ISSUE TITLE
Dynamic FormArray doesnt update valueChanges

### ISSUE THREAD

**Issue by DevNico** [joanpablo/reactive_forms#203]
I have a `FormArray` which dynamically gets added 1-2 `FormGroup`s as controls. The problem is that this FormArrays valueChanges stream doesn't update if a control in the FormGroup changes.

**Comment by vasilich6107** [comment]
@DevNico I suppose you have to remove and add back the new form group
It will be better if you prepare the working example to illustrate your issue

**Comment by DevNico** [comment]
I have fixed the issue by now I didn't implement a FormArray of FormGroup correctly as stated in the docs. Sorry about that.
