### ISSUE TITLE
SelectAll - how we can do?

### ISSUE THREAD

**Issue by carmas123** [joanpablo/reactive_forms#209]
Could anyone help me understand how to select all the text without being able to access the TextEditController?

Regards.

**Comment by vasilich6107** [comment]
@carmas123 you can pass your own controller into the text field. There is a prop for that. Then you’ll be able to do whatever you want

**Comment by carmas123** [comment]
@vasilich6107 ReactiveTextField don't have TextEditController

**Comment by vasilich6107** [comment]
@carmas123 ouch(
Will think about possible solutions

**Comment by vasilich6107** [comment]
@joanpablo is it bug or feature?

**Comment by carmas123** [comment]
I think that exposing TextEditingController is a bad idea. I think that the best solution is to make a custom controller to handle some functionality, like selection or other.

**Comment by vasilich6107** [comment]
Hi @carmas123 
I release standalone package for text field with exposed controller
https://pub.dev/packages/reactive_text_field

Check how to access the controller in example
https://github.com/artflutter/reactive_forms_widgets/blob/master/packages/reactive_text_field/example/lib/main.dart#L47

Does it looks suitable for your needs?

**Comment by carmas123** [comment]
Thank you so much now I try and let you know

**Comment by carmas123** [comment]
However I think that the best way to realize it (selectAll) is performing a simplified method like this: 

form.control('input').selectAll()

**Comment by vasilich6107** [comment]
@carmas123 not all inputs support selecting all
Basically only textfield siblings could have this functionality
So it will bring us into the case when we implement control specific actions in the form engine which is not a good practice

**Comment by joanpablo** [comment]
Hi @vasilich6107,

I like the way you have implemented the **ReactiveTextField.onControllerInit**. Could you please include it in the implementation of the ReactveTextField from Reactive Forms? And instead of having two ReactiveTextFields  (that may be confusing) Have just one, the original? I will merge it if you create a PR.

Thanks in advance.

**Comment by joanpablo** [comment]
After this change, I will also upgrade the version of Flutter for Reactive Forms and I will include all new properties that are new in this latest Flutter version.

**Comment by vasilich6107** [comment]
Ok, will include the implementation

**Comment by vasilich6107** [comment]
@joanpablo I did several PRs with controller exposure and props updates

**Comment by joanpablo** [comment]
Hi @carmas123,

We have just released version 11.0.0, which exposes the TextEditingController for selection purposes.
