### ISSUE TITLE
Didchange always rebuilds all child widgets

### ISSUE THREAD

**Issue by sokolej79** [joanpablo/reactive_forms#211]
ReactiveFormField and all form fields widgets that extends ReactiveFormField like  ReactiveTextField always rebuild its child widgets inside widget that extend ReactiveFormField .
Is there any option to prevent rebuild after calling didchange?
I worked with Angular reactive forms and is not working like that, on change only update form model and not rebuild widget. 
I  have complex custom form field inline webview, editor and plain text for view and edit html. This is one custom form field that I can swipe between view and edit mode. When I edit html I call didchange to sync form and it always rebuild my webview and editor.

**Comment by vasilich6107** [comment]
@sokolej79 I'm not 100% sure but it seems that redesigning you field will help you

Is it possible to move your WebView outside of the field to prevent rebuilds?
Then you can subscribe to the editor updates and use the field value whatever you want.

The demo code will be more helpful to understand your flow

**Comment by sokolej79** [comment]
Thank you very much for the reply and help.
I just wanted to know if the form  didChange  always rebuilds dependent widgets or is something  wrong with my code.
Apparently it rebuilts by default.
I'll find some work around.
Thanks, Im closing.
