### ISSUE TITLE
How to handle valueTransformer?

### ISSUE THREAD

**Issue by savandev17** [joanpablo/reactive_forms#212]

**Comment by vasilich6107** [comment]
@savandev17 more details please

**Comment by savandev17** [comment]
Thanks for response sir, the "reactive_forms" is very awesome plugin, my problem is when dropdown selected we can get only single value, how can we change to new object or other format
the below is example using [https://github.com/danvick/flutter_form_builder](url) plugin
![image](https://user-images.githubusercontent.com/34710166/132790556-bcaa4c8e-42a2-4bd5-94ac-c4a9d089a370.png)

And this is I tried with reactive_forms, look like it's isn't defined
![image](https://user-images.githubusercontent.com/34710166/132790789-3cbf8d9a-a5c7-4441-91c3-b13ec6b838e5.png)

Could you please add this property, Thanks in advance.

**Comment by vasilich6107** [comment]
We have a `valueAccessor` for this purposes but unfortunately `ReactiveDropdownField` is missing this property.
Will try to prepare PR asap. I hope @joanpablo will merge and release it quickly

**Comment by savandev17** [comment]
Thanks you very much.

**Comment by savandev17** [comment]
Is there an example for how to use valueAccessor?

**Comment by vasilich6107** [comment]
@joanpablo could you take a look into #213

**Comment by vasilich6107** [comment]
@savandev17 there is sample inside PR
https://github.com/joanpablo/reactive_forms/pull/213/files#diff-e8a1359e17238b19bba97f15afc3f0af61ecd3467fd0176de2b71c7a73581056R6

**Comment by vasilich6107** [comment]
@savandev17 any feedback?
