### ISSUE TITLE
How to implement multiple checkbox to get different checked value?

### ISSUE THREAD

**Issue by savandev17** [joanpablo/reactive_forms#214]
Hi everyone, I'm trying to customize original sample code to meet my purposes but still get failed, could you please suggest me  how to do that to get the result by image below?

![image](https://user-images.githubusercontent.com/34710166/132854618-2939192f-3c06-4299-814e-8fece7064d7d.png)

Thank you.

**Comment by vasilich6107** [comment]
@savandev17 there is no way of doing that)
After filling the form you need manually take from array of values only the items that corresponds to `true` indexes

**Comment by savandev17** [comment]
Is check box support only true or false value?

**Comment by vasilich6107** [comment]
Yes.
Also there is no possibility to use valueAccessor in checkboxfields.

**Comment by vasilich6107** [comment]
You can check standalone implementation of checkbox which supports value accessors
https://pub.dev/packages/reactive_checkbox

**Comment by joanpablo** [comment]
Hi @savandev17,

I'm closing the issue because of a lack of update on it. I hope you have solved your issue, don't hesitate to reopen it or create a new one.
