### ISSUE TITLE
File Picker Documentation

### ISSUE THREAD

**Issue by arcas0803** [joanpablo/reactive_forms#215]
Hi,
I'm using your library and it's great.
The Reactive file picker library it's not working and I can't find documentation or an example to guide me in the implementation.
Is it possible to update with an example of how to use it?
Thanks.

**Comment by vasilich6107** [comment]
![185E8971-CF3F-407C-952F-744F72CDE17E](https://user-images.githubusercontent.com/6721286/132988387-5e8283d2-83cf-42d8-b396-8ec194405ebc.jpeg)

**Comment by vasilich6107** [comment]
The package on pub.dev has a link to GitHub repository
https://github.com/artflutter/reactive_forms_widgets

**Comment by vasilich6107** [comment]
That link will lead you to the place where you can live your issues.
Also each package in flutter universe has `example` fielder with executable example

reactive file picker also has one
https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_file_picker/example

**Comment by arcas0803** [comment]
I found finally then example .

**Comment by BigGitWorld** [comment]
> That link will lead you to the place where you can live your issues. Also each package in flutter universe has `example` fielder with executable example
> 
> reactive file picker also has one https://github.com/artflutter/reactive_forms_widgets/tree/master/packages/reactive_file_picker/example

There is not any sample in the link.

**Comment by vasilich6107** [comment]
@BigGitWorld 
fixed
https://github.com/artflutter/reactive_forms_widgets/blob/master/packages/reactive_file_picker/example/lib/main.dart
