### ISSUE TITLE
ReactiveTextField not have builder: (context, form, child) {

### ISSUE THREAD

**Issue by zapiti** [joanpablo/reactive_forms#216]
Please add  builder: (context, form, child) { Widget } to ReactiveTextField for custom form listen changes

**Comment by vasilich6107** [comment]
@zapiti it seems that you can use `ReactiveFormConsumer` for this purposes

**Comment by vasilich6107** [comment]
@zapiti any feedback?

**Comment by joanpablo** [comment]
Closed because it has not been updated for a long time.

Please @zapiti don't hesitate to re-open it on create a new one if you have new questions.
