### ISSUE TITLE
ReactiveDropdownField should have borderRadius field in constructor

### ISSUE THREAD

**Issue by BenjaminFarquhar** [joanpablo/reactive_forms#225]
Hi there,

In the ReactiveDropdownField widget, we can actually edit the source code to add a BorderRadius to the drop down list, like so:

```
DropdownButton<T>(
                  value: effectiveValue,
                  items: items,
                  borderRadius: BorderRadius.circular(10),
```

This gives a BorderRadius to the drop down list. However, the borderRadius field is not available to pass in to a ReactiveDropdownField and it should be, to add more customization. I also wonder is there a way to align the drop down list to the bottom of the input field? 

Thank you!! :)

**Comment by joanpablo** [comment]
Hi @BenjaminFarquhar,

Thanks for the issue. I will take a look and include the missing properties to the ReactiveDropdownField

**Comment by joanpablo** [comment]
Hi again @BenjaminFarquhar,

COuld you please give more details? Where did you see the property **borderRadius**? Because in the definition of the class [DropdownButton](https://api.flutter.dev/flutter/material/DropdownButton-class.html) from Flutter, this property does not exist.

**Comment by vasilich6107** [comment]
Hi @BenjaminFarquhar I did the PR #236 but there is no clear understanding how long will it take @joanpablo to release...
So I released a separate version of the field into standalone package.
https://pub.dev/packages/reactive_dropdown_field

**Comment by vasilich6107** [comment]
Also try to use this package
It simplifies reactive_forms development
https://github.com/artflutter/reactive_forms_generator

**Comment by vasilich6107** [comment]
@BenjaminFarquhar I do not recommend you to wait until release of the whole form engine.
The issue is that your props are available only form 2.5.* version of the Flutter.
This means that the whole `reactive_forms` should be bumped to use `2.5.*` and this is a little bit complicated and will require new major release.

I'm not sure that this is a good idea...
Anyway. You have a separate package. You now what to do :-)

**Comment by BenjaminFarquhar** [comment]
@vasilich6107 Thanks!

**Comment by BenjaminFarquhar** [comment]
> Also try to use this package It simplifies reactive_forms development https://github.com/artflutter/reactive_forms_generator

This seems very nifty, thanks. Had a little play and the form.model wasn't updating when I typed. I must have missed something. I will have a proper attempt again later. My text fields are custom and extend `ReactiveFormField<String, String>`, and they also usually use `formControlName` but I added `formControl` to them so not sure what the issue was but I'm fairly sure it will be with my code not the package.

**Comment by vasilich6107** [comment]
@BenjaminFarquhar if you could provide a standalone git repo with reproduction sample I will try to help you

**Comment by vasilich6107** [comment]
@BenjaminFarquhar it seems that your issue is fixed
Could you close it?

**Comment by BenjaminFarquhar** [comment]
@vasilich6107 Thanks so much! I will get in touch if I have any issues when I get around to trying the generator again. Yes this is fixed now :)
