### ISSUE TITLE
Awesome Flutter

### ISSUE THREAD

**Issue by Solido** [joanpablo/reactive_forms#227]
Hello ! I manage https://github.com/Solido/awesome-flutter
and I would like to add Reactive Forms so more users can find it.
You can PR if you desire.

Also this point on the Readme

This part on fb is not working, need to replace `FormGroup` with `fb.group`

`'address': FormGroup({
    'street': ['', Validators.required],
    'city': ['', Validators.required],
    'zip': ['', Validators.required],
  }),`

Thank you !

**Comment by joanpablo** [comment]
Hi @Solido,

Thanks for your contribution to Flutter comunity, and thanks for this issue.

Best Regards

**Comment by vasilich6107** [comment]
Hi @Solido 
I checked the readme to find the issues which you described.

And I was not able to find anything.

There is a tricky moment of distinguishing between `FromGroup` and `fb.group`.

If you check the readme all the places with `'controlName': ['', ...]` notation are wrapped with `fb.group` which converts them into `FormGroup`.

All other places which are using `FormGroup` consists from variations of `AbstractControl`.

The two ways of achieving the same result could be missleading(I'm not a fan of this approach at all) but we have it)

**Comment by vasilich6107** [comment]
@Solido I created a package https://pub.dev/packages/reactive_forms_generator which helps to cover tricky parts of the `reactive_forms` with power of generators.
The motivation section from readme describes my intentions
https://github.com/artflutter/reactive_forms_generator#motivation

It would be great if you could try it and provide some feedback)

**Comment by Solido** [comment]
Hey @vasilich6107 
Thanks for looking at the report. 

It was my very first experience and a copy paste from the readme.
If all is OK then it is good for newcomers on-boarding. 
Confusing but not for long as it soon reveals its expressivity.

I hope to find some time to look at your generator in more details.
A nice addition, when patterns are identified it really helps with large project.
Also I noted the name FreezedFormWidget :) Nicely done demo.
