### ISSUE TITLE
Find focused control

### ISSUE THREAD

**Issue by carmas123** [joanpablo/reactive_forms#230]
Hi, please can you add the ability to FormGroup class to find what is the current focused control?

**Comment by vasilich6107** [comment]
Could you describe your workflow more verbose.
Maybe there is another way to solve it

**Comment by joanpablo** [comment]
Hi @carmas123,
 Do you have any updates on this? Could you give more details?

**Comment by carmas123** [comment]
Sorry man but for now no other news

**Comment by carmas123** [comment]
My question is this: I've a form with some controls and I need to know what of this have the focus

**Comment by vasilich6107** [comment]
@carmas123 the formgroup is a map with controls.
What you have to do is to iterate through the map recursively and call `hasFocus` on each control to find the one which has focus.

**Comment by joanpablo** [comment]
Hi @carmas123 

We are closing the issue due to a lack of updates on it. I hope you have solved your issue.
