### ISSUE TITLE
How can I access Validator dynamic value in ValidationMessage?

### ISSUE THREAD

**Issue by ebelevics** [joanpablo/reactive_forms#231]
The title says it all. How can I get from `validationMessages: (control)` control value in `ValidationMessage.minLength` usecase `requiredLength` value for dynamic validation messages?

**Comment by vasilich6107** [comment]
You can access the value from `control` item.
Just place the breakpoint inside validationMessages function and see the props of `control`.
It should be something like `control.value`

**Comment by vasilich6107** [comment]
@ebelevics does it solved your issue?

**Comment by ebelevics** [comment]
Yes, sorry for late response I did find, how to solve. Thanks.

**Comment by vasilich6107** [comment]
Also try to use this package
It simplifies reactive_forms development 
https://github.com/artflutter/reactive_forms_generator

**Comment by ebelevics** [comment]
I usually try to stay away from generators as it just boilers the project, and use it when it's totally necessary (like json_serializable), but I'll take a look.
Offtopic: Still don't understand why generated files are not separated from lib (similar like in Kotlin) 😄

**Comment by vasilich6107** [comment]
@ebelevics this is not the same case as any other generator.
You can quickly observe the improvements which code generator brings to reactive_forms from motivation section
https://github.com/artflutter/reactive_forms_generator#motivation
