### ISSUE TITLE
Validation not working

### ISSUE THREAD

**Issue by Murtoz-h** [joanpablo/reactive_forms#233]
Please  see my code below, Its validation always failing/not working

`showModalBottomSheet(
                                              context: context,
                                              builder: (BuildContext context) {
                                                var form = FormGroup({
                                                  'KeyFeature':
                                                      FormControl<String>(
                                                          validators: [
                                                        Validators.required
                                                      ]),
                                                  'KeyValue':
                                                      FormControl<String>(
                                                          validators: [
                                                        Validators.required
                                                      ]),
                                                });
                                                return ReactiveForm(
                                                  formGroup: form,
                                                  child: Column(
                                                    children: <Widget>[
                                                      ReactiveTextField(
                                                        decoration: InputDecoration(
                                                            label: Text(
                                                                "Key Features")),
                                                        formControlName:
                                                            'KeyFeature',
                                                      ),
                                                      ReactiveTextField(
                                                        decoration:
                                                            InputDecoration(
                                                                label: Text(
                                                                    " Values")),
                                                        formControlName:
                                                            'KeyValue',
                                                        obscureText: false,
                                                      ),
                                                      ReactiveFormConsumer(
                                                        builder: (context,
                                                            form2, child) {
                                                          return ElevatedButton(
                                                              child: Text(
                                                                  'Submit'),
                                                              onPressed: form2
                                                                      .valid
                                                                  ? () => print(
                                                                      "object")
                                                                  : null);
                                                        },
                                                      ),
                                                      //MySubmitButton(),
                                                    ],
                                                  ),
                                                );
                                              });
                                       `

**Comment by vasilich6107** [comment]
Start from copy pasting code from login example.
It should work.
Then adjust slightly according to your needs

**Comment by Murtoz-h** [comment]
Its working when using it as simple as you shown like the following code, But its not working when I use it under future builder=> Listview.builder=> ShowModalBootomsheet.

import 'package:flutter/material.dart';
import 'package:reactive_forms/reactive_forms.dart';

class Rform extends StatelessWidget {
  Rform({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final form = FormGroup({
      'KeyFeatures': FormControl<String>(validators: [Validators.required]),
      'KeyValues': FormControl<String>(validators: [Validators.required]),
    });
    return ReactiveForm(
      formGroup: form,
      child: Column(
        children: <Widget>[
          ReactiveTextField(
            decoration: InputDecoration(label: Text("Key Feature")),
            formControlName: 'KeyFeatures',
          ),
          ReactiveTextField(
            decoration: InputDecoration(label: Text("Key Values")),
            formControlName: 'KeyValues',
            obscureText: false,
          ),
          ReactiveFormConsumer(
            builder: (context, form, child) {
              return ElevatedButton(
                child: Text('Submit'),
                onPressed: form.valid
                    ? () => print(form.controls.keys.elementAt(0) +
                        " : " +
                        (form.controls.values.elementAt(1)
                                as FormControl<String>)
                            .value
                            .toString())
                    : null,
              );
            },
          ),
        ],
      ),
    );
  }
}

**Comment by Murtoz-h** [comment]
Problem solved, when I pass key to form widget from parrent, it's working.

 Thanks for this great package.

**Comment by Murtoz-h** [comment]
First I thought its working and also closed once, but its not working, confirmed. Situation described in above comment.

**Comment by vasilich6107** [comment]
You just doing your form wrong
https://github.com/joanpablo/reactive_forms/blob/master/example/lib/samples/login_sample.dart

**Comment by vasilich6107** [comment]
Refer to example and do the same as it is there.
Do no use `ReactiveForm` use `ReactiveFormBuilder` instead.

Everything works fine

**Comment by Murtoz-h** [comment]
Thanks for your kind reply. This solved my problem.

**Comment by vasilich6107** [comment]
Also try to use this package
It simplifies reactive_forms development 
https://github.com/artflutter/reactive_forms_generator

**Comment by Murtoz-h** [comment]
Thanks for informing.
