### ISSUE TITLE
Unable to correctly delete elements in a FormArray...

### ISSUE THREAD

**Issue by rsbichkar** [joanpablo/reactive_forms#234]
Hi Joan,

Thanks for this wonderful forms package! I have been using this library in my projects under development.

I am trying to implement a ReactiveForm for email list entry where I wish to add new email entries or remove existing ones. However, in spite of hundreds of possible changes in approach, I am not able to get a correct list output. In particular, the problem is in the deletion operation. It works fine for the deletion of the last email. However, if I delete any other email, always last entry in the form is removed (on the emulator). But in the 'emails' and 'person.emails' lists, the emails are removed correctly. Only the screen display is incorrect.

I have used the freezed and Flutter Hooks packages. But it does not work even while using a plane class or a stateful widget.

The program is slightly longer. So I have put it in a public git repo:
https://github.com/rsbichkar/reactive_from_test

I am sure I have missed out on something very important. But I am unable to make further progress. Will you please check if there is any problem in my code or the FormArray functionality in reactive_forms? (The details about the code are given below).

Thanks in advance.

Some details about the code:

The Person class has a name and emails fields defined in person.dart using 'freezed' annotation as
```dart
@freezed
class Person with _$Person {
  factory Person({
    required String name,
    List<String>? emails,
  }) = _Person;
}
```

The main form code is in 'form.dart' file. This file defines a class named PersonReactiveForm inherited from HookWidget. It uses two useState hooks:
```dart
    final _emailControls = useState(form.control('emails') as FormArray<String>);
    final _person = useState(person);
```
The Form uses a Column to display the email list:

```dart
  Column(
    children: <Widget>[
      ReactiveFormArray<String>(
        formArrayName: 'emails',
        builder: (context, formArray, child) => Column(
          children: [
            for (int i = 0; i < _person.value.emails!.length; i++)
              arrayElementEmailField(i, _person, _emailControls),
          ],
        ),
      ),
      ReactiveFormConsumer(
        builder: (context, form, child) {
          return ElevatedButton(
            // enable 'Add Email' button only if no email field is empty or
            // all fields have valid email values
            onPressed: _person.value.emails!.any((email) => email.isNotEmpty) &&
                    _emailControls.value.controls.every((control) => control.valid)
                ? () => _addEmail(_person, _emailControls)
                : null,
            child: const Text('Add Email'),
          );
        },
      ),
    ],
  ),
```
The addEmail and removeEmail functions are as follows:
```dart
  void _addEmail(ValueNotifier<Person> _person, ValueNotifier<FormArray<String>> _emailControls) {
    _person.value.emails!.add('');
    _emailControls.value.add(FormControl<String>(value: '', validators: [Validators.email]));
  }

  void _removeEmail(
      int index, ValueNotifier<Person> _person, ValueNotifier<FormArray<String>> _emailControls) {
    _person.value.emails!.removeAt(index);
    _emailControls.value.removeAt(index);
  }
```
The arrayElementEmailField() called in  for loop in Column is as follows:
```dart
  Widget arrayElementEmailField(
      int index, ValueNotifier<Person> _person, ValueNotifier<FormArray<String>> _emailControls) {
    // print('index: $index, Add email control: ${_person.value.emails![index]}');
    return Row(
      mainAxisSize: MainAxisSize.min,
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Expanded(
          child: ReactiveTextField(
            formControlName: index.toString(),
            keyboardType: TextInputType.emailAddress,
          ),
        ),
        const SizedBox(width: 10),

        // display email deletion icon only if we have more than 1 emails
        if (_person.value.emails!.length > 1)
          IconButton(
            icon: const Icon(Icons.remove_circle_outline),
            onPressed: () => _removeEmail(index, _person, _emailControls),
          )
      ],
    );
  }
```

**Comment by vasilich6107** [comment]
Hi @rsbichkar 
I tried to get along with your sample.
But it is too verbose and I had no time to get along with it

Instead I improved the existing array sample to include delete button so everyone could benefit from it
Check the https://github.com/joanpablo/reactive_forms/pull/235

**Comment by rsbichkar** [comment]
Hi Vasiliy, (@vasilich6107),
Thanks a lot. I will check the delete functionality from your example.

**Comment by vasilich6107** [comment]
Also try to use this package
It simplifies reactive_forms development
https://github.com/artflutter/reactive_forms_generator

**Comment by rsbichkar** [comment]
Thanks for your inputs and the package for forms_generatos. I have downloaded the package and your approach is interesting.

I have also independently developed a forms generator for my own use so far. The generator generates forms, FormFields class and handles all the validations of ReactiveForms. In addition, it also generates the controllers and repos for FieStore and views (Markdown as well as Yaml). In future I wish to use the other forms packages (e.g. flutter_form_builder) so that any type of Form and the entire associated functionality can be generated just by using the class definition with annotations.

**Comment by vasilich6107** [comment]
Hi @rsbichkar 
Is there any possibility to share your implementation in order to inspire new features in reactive_forms_generator?

**Comment by rsbichkar** [comment]
Hi Vasili (@vasilich6107),

Yes sure. However, the code is not well organized and properly documented. So I will share, in the meantime, the generated code file and the class with annotations. My approach has a lot of similarities in the use of annotations but a different implementation (I suppose). Please let me know if this type of code generation output will be helpful.

I am currently developing an app (mobile, web, desktop) for a large application involving probably thousands of classes. So it will be difficult to manually write all the code for forms, generators, views, repositories, controllers, and much more. So the plan is to write only the classes with annotation and generate as much code as possible using code generation. I am still working on the code generation. 

I also wish to write generics-based code for controllers and repositories so that it is not to be generated for each class. However, I have not started with it.

[person.zip](https://github.com/joanpablo/reactive_forms/files/7533577/person.zip)

**Comment by vasilich6107** [comment]
@rsbichkar thanks a lot!
Will try to play around with it

**Comment by vasilich6107** [comment]
@rsbichkar if your issue is solved - do not forget to close the issue

**Comment by rsbichkar** [comment]
@vasilich6107
Thanks a lot for your valuable support
