### ISSUE TITLE
ReactiveTextField Multiline with Enter

### ISSUE THREAD

**Issue by kfchengkf** [joanpablo/reactive_forms#238]
Hello,

I can't get 'Enter' to work for the ReactiveTextField on a real phone (Samsung Model)
The code being used is like this:
ReactiveTextField(
            formControlName: 'Remarks',
            maxLines: null,
            keyboardType: TextInputType.multiline,
            focusNode: _focusNode),
      )

The Remarks field is supposed to allow 'real' multiline inputs (not just autowrap)

Any idea why it is not working ?
(Note: It works on the simulator)

Thanks.

**Comment by vasilich6107** [comment]
@kfchengkf I would suggest to start testing with simple `TextField` from `flutter`
`ReactiveTextField` just passes through all the pros to `TextField` 

It could be the `flutter` bug related to `Samsung` platform specific.

**Comment by vasilich6107** [comment]
If you will reproduce your bug on `TextField` it will be better to create issue in flutter repo(do not forget close this one in this case)

**Comment by kfchengkf** [comment]
OK.  Thanks.
