### ISSUE TITLE
ReactiveFormArray does not update when calling `updateValue()` or `reset()`

### ISSUE THREAD

**Issue by jrmallorca** [joanpablo/reactive_forms#240]
What I am trying to do is replace the contents of a `FormArray` and have the changes appear on a `ReactiveFormArray`. I do this as I don't know how to just replace an element in the `FormArray` with another element.

My `ReactiveFormArray` widget does not update when the `FormArray` is updated through `updateValue()` or `reset()` (I have to hot reload to see the changes). However, the widget is updated when I call either `add()`, `addAll()`, or `clear()`

Due to this, instead of doing something like:
```
exerciseArray.updateValue(updatedExercises);
```
where `updatedExercises` is a `List<ExerciseEntity>`,

I use:
```
exerciseArray.clear(updateParent: false, emitEvent: false);
exerciseArray.addAll(updatedExercises);
```
where `updatedExercises` is a `List<AbstractControl<ExerciseEntity>>`

While the functionality is working as I wanted it, I feel as if using `updateValue()` would feel more appropriate instead.

This issue may be related with #185.

**Comment by joanpablo** [comment]
Hi @jrmallorca,

Could you please write a code sample that reproduces the error, or give more details?

- Are you sure you are not passing an empty array to **updateValue**?
- BTW you can simple use:
```dart
exerciseArray.value = updatedExercises;
```
- Is the **FormArray** updating the value and not the **ReactiveFormArray**, or none of them are updating the value?

**Comment by jrmallorca** [comment]
I'll try to write a code sample reproduce the error, but I will answer your questions now.

- I am definitely not passing an empty array to `updateValue()`.
- The `FormArray` is updated. The `ReactiveFormArray` is not. I do not see the **visual** update to the `FormArray`. I have to hot reload to see the changes.

**Comment by joanpablo** [comment]
Hi @jrmallorca,

Thanks for responding to the questions.

In the demo folder called **example**, there is an example of using the **ReactiveFormArray**. The sample demo works correctly, have you taken a look at it and compared it with your code, to see if there are any differences?

Best regards

**Comment by vasilich6107** [comment]
Hi @jrmallorca 
I updated array sample in `example` folder in https://github.com/joanpablo/reactive_forms/pull/245

Check how to updateAll, reset and update exact control

**Comment by vasilich6107** [comment]
@jrmallorca any feedback?

**Comment by jrmallorca** [comment]
Sorry, I had been occupied with an issue that wouldn't let me even test this issue. However, I do believe that I used it in a similar fashion. I'll get back to you once my side has been fixed.

**Comment by joanpablo** [comment]
Hi @jrmallorca,

Are you using Flutter **Keys** for each of your children of the  **ReactiveFormArray**?

Any Update? 
Can you place a sample Code? Just copy-paste the code you have to have a better understanding of your issue.

Thanks in advance

**Comment by jrmallorca** [comment]
Hello,
Sorry for taking so long, I believe I finally created an example that illustrates my problem.

1. Input `flutter create bug`
2. Copy the following files into the **lib** folder:

<details>
<summary>exercise_entity.dart</summary>

```
import 'package:uuid/uuid.dart';

class ExerciseEntity {
  final String uuid;
  final String name;

  ExerciseEntity({
    required this.name,
  }) : uuid = const Uuid().v4();
}
```

</details>

<details>
<summary>workout_entity.dart</summary>

```
import 'exercise_entity.dart';

class WorkoutEntity {
  final List<ExerciseEntity> exercises;

  WorkoutEntity({
    required this.exercises,
  }) : assert(exercises.isNotEmpty);
}
```

</details>


<details>
<summary>workout_form.dart</summary>

```
import 'package:reactive_forms/reactive_forms.dart';

import 'exercise_entity.dart';
import 'workout_entity.dart';

class WorkoutForm {
  late final FormGroup formGroup;

  WorkoutForm(WorkoutEntity? workout) {
    final exerciseArray = FormArray<ExerciseEntity>(
      workout == null
          ? []
          : workout.exercises
              .map((exercise) => FormControl<ExerciseEntity>(value: exercise))
              .toList(),
    );

    final exerciseGroup = FormGroup(
      {
        'uuid': FormControl<String>(),
        'name': FormControl<String>(
          value: '',
        ),
      },
    );

    formGroup = FormGroup({
      'exercises': exerciseArray,
      'exercise': exerciseGroup,
    });
  }
}
```

</details>

<details>
<summary>main.dart</summary>

```
import 'package:flutter/material.dart';
import 'package:reactive_forms/reactive_forms.dart';

import 'exercise_entity.dart';
import 'workout_entity.dart';
import 'workout_form.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatelessWidget {
  late final WorkoutForm example;

  MyHomePage({Key? key}) : super(key: key) {
    example = WorkoutForm(WorkoutEntity(exercises: [
      ExerciseEntity(name: 'derp'),
    ]));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Flutter Array Sample'),
      ),
      body: ReactiveForm(
        formGroup: example.formGroup,
        child: Column(
          children: [
            ReactiveFormArray<ExerciseEntity>(
              formArrayName: 'exercises',
              builder: (_, formArray, __) {
                final exercises = formArray.value!;

                return exercises.isEmpty
                    ? const Center(child: Text('No exercises'))
                    : ListView.builder(
                        shrinkWrap: true,
                        itemCount: exercises.length,
                        itemBuilder: (_, index) =>
                            _buildListItem(context, exercises[index]!),
                      );
              },
            ),
            ReactiveTextField(
              decoration: const InputDecoration(labelText: 'Name'),
              formControlName: 'exercise.name',
            ),
            _ExerciseSubmitButton(
              exerciseForm: example.formGroup.control('exercise') as FormGroup,
              exerciseArray: example.formGroup.control('exercises')
                  as FormArray<ExerciseEntity>,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildListItem(BuildContext context, ExerciseEntity exercise) {
    final Text title = Text(exercise.name);

    return ListTile(
      title: title,
      onTap: () => _handleEditExercise(context, exercise),
    );
  }

  void _handleEditExercise(BuildContext context, ExerciseEntity exercise) {
    // Get exercise form to fill in values
    final FormGroup exerciseForm =
        example.formGroup.control('exercise') as FormGroup;

    // Fill in exercise form values with this exercise
    exerciseForm.value = {
      'uuid': exercise.uuid,
      'name': exercise.name,
    };
  }
}

class _ExerciseSubmitButton extends StatelessWidget {
  final FormGroup exerciseForm;
  final FormArray<ExerciseEntity> exerciseArray;

  const _ExerciseSubmitButton({
    Key? key,
    required this.exerciseForm,
    required this.exerciseArray,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return ElevatedButton(
      child: const Text('Submit'),
      onPressed: _onPressed,
    );
  }

  void _onPressed() {
    final String? uuid = exerciseForm.control('uuid').value;
    final String name = exerciseForm.control('name').value;

    // Convert values in exerciseForm to [ExerciseEntity]
    final ExerciseEntity exercise = ExerciseEntity(name: name);

    // Add or update exercise, depending if UUID is null or not
    uuid != null
        ? _updateExerciseInFormArray(
            uuid: uuid,
            exercise: exercise,
          )
        : _addExerciseToFormArray(exercise);

    // Reset the form and empty the name field
    exerciseForm.reset(value: {
      'name': '',
    });
  }

  void _updateExerciseInFormArray({
    required String? uuid,
    required ExerciseEntity exercise,
  }) {
    // Create a new list of exercises with the replaced exercise
    // final updatedExercises = exerciseArray.controls
    // .map((exerciseControl) => exerciseControl.value!.uuid == uuid
    // ? FormControl<ExerciseEntity>(value: exercise)
    // : exerciseControl)
    // .toList();

    // // Set the new list of exercises
    // exerciseArray.clear(updateParent: false, emitEvent: false);
    // exerciseArray.addAll(updatedExercises);

    // DEBUG PURPOSES BELOW

    final updatedExercises = exerciseArray.value!
        .map((e) => e!.uuid == uuid ? exercise : e)
        .toList();

    exerciseArray.value = updatedExercises;

    // print(exerciseArray.value);
  }

  void _addExerciseToFormArray(ExerciseEntity exercise) {
    exerciseArray.add(
      FormControl<ExerciseEntity>(value: exercise),
    );
  }
}
```

</details>

3. Run the app.
4. Click on "derp" and wait until "derp" appears in the `ReactiveTextField`.
5. Change "derp" in `ReactiveTextField` into another string.
6. Click "Submit" button.
7. Hot reload.

On step 6, I would've expected it to change, but it is not until hot reloading that I see it visually change. I know it's not a `StatelessWidget` issue as I made a `StatelessWidget` version of the array sample that @vasilich6107 had shown me (thank you, btw).

**Comment by vasilich6107** [comment]
@jrmallorca do not hesitate to make ready-for-use reproduction repo next time

**Comment by joanpablo** [comment]
Hi @jrmallorca,

The widget **ReactiveFormArray** was intentionally implemented to listen when the *collection* of controls change. That means you add or remove items from the collection. It is not implemented to listen for changes in the **value** of the array.

So you have two options:

1- Use **ReactiveValueListenable** bound with the FormArray, instead of using the ReactiveFormArray.
2- Use the **ReactiveFormArray** but **wrap** each ListTile with a **ReactiveValueListenable** that is bound with the control.

Note:
It is also a good practice to set a **key** to each ListTile, for example, you can use an **ObjectKey**.

That will solve your issue.

**Comment by jrmallorca** [comment]
Hi @joanpablo and @vasilich6107,
I'm trying to do the first option, but I'm having trouble casting `AbstractControl<ExerciseEntity>` into `FormArray<ExerciseEntity>` in the `ReactiveValueListenableBuilder`. Would you know how to do so?

<details>
<summary>Example of what I'm trying to do</summary>

```
  Widget build(BuildContext context) {
    return ReactiveValueListenableBuilder<ExerciseEntity>(
      formControlName: 'exercises',
      builder: (_, control, __) {
        final formArray = control as FormArray<ExerciseEntity>;
        final exercises = formArray.value!;

        return exercises.isEmpty
            ? const MessageDisplay(text: 'No exercises')
            : ReorderableListView.builder(
                onReorder: (oldIndex, newIndex) {
                  // Check whether we have to do the operation
                  if (newIndex != oldIndex) {
                    // Reorder list
                    if (newIndex > oldIndex) {
                      newIndex -= 1;
                    }
                    exercises.insert(newIndex, exercises.removeAt(oldIndex));

                    // Update value
                    formArray.updateValue(exercises);
                  }
                },
                itemCount: exercises.length,
                itemBuilder: (_, index) => Dismissible(
                  key: ValueKey(index),
                  child: ExerciseTile(exercise: exercises[index]!),
                  onDismissed: (direction) => exercises.removeAt(index),
                ),
              );
      },
    );
  }
```
</details>

<details>
<summary>What the method was before</summary>

```
  Widget build(BuildContext context) {
    return ReactiveFormArray<ExerciseEntity>(
      formArrayName: 'exercises',
      builder: (_, formArray, __) {
        final exercises = formArray.value!;

        return exercises.isEmpty
            ? const MessageDisplay(text: 'No exercises')
            : ReorderableListView.builder(
                onReorder: (oldIndex, newIndex) {
                  // Check whether we have to do the operation
                  if (newIndex != oldIndex) {
                    // Reorder list
                    if (newIndex > oldIndex) {
                      newIndex -= 1;
                    }
                    exercises.insert(newIndex, exercises.removeAt(oldIndex));

                    // Update value
                    formArray.updateValue(exercises);
                  }
                },
                itemCount: exercises.length,
                itemBuilder: (_, index) => Dismissible(
                  key: ValueKey(index),
                  child: ExerciseTile(exercises[index]!),
                  onDismissed: (direction) => exercises.removeAt(index),
                ),
              );
      },
    );
  }

```
</details>

**Comment by joanpablo** [comment]
Hi @jrmallorca,

Have you tried:

**ReactiveValueListenableBuilder<List<ExerciseEntity>>**

or

**ReactiveValueListenableBuilder<dynamic>**

Please let me know which one works because I don't remember right now, what method I used when testing your solution.
I don't solve your casting issue let me know and I will implement again your solution to see which one was the one that works.

**Comment by jrmallorca** [comment]
Thank you so much for all your help @joanpablo and @vasilich6107, especially for me taking long. I tried your first option, but with a nullable list and it finally worked.
