### ISSUE TITLE
Display custom validation messages in SnackBar

### ISSUE THREAD

**Issue by xsamurai** [joanpablo/reactive_forms#241]
I would like to display my custom error messages in a SnackBar, instead of the  displaying under the input field.

      formControlName: 'password',
      validationMessages: (control) => {
        ValidationMessage.required: 'Password is required',
        ValidationMessage.minLength: 'Minimum of 5 characters',
      },
      showErrors: (control) => control.disabled, 

I am able to access the default errors messages but can't figure out how to access the custom errors messages.

            pressed: () {
              var _list = form.errors.toString();
              form.valid
                  ? funcCall()
                  : ScaffoldMessenger.of(context)
                      .showSnackBar(SnackBar(content: Text(_list)));
            });

**Comment by vasilich6107** [comment]
Use getErrorText for specific control 
https://github.com/joanpablo/reactive_forms/blob/master/lib/src/widgets/reactive_form_field.dart#L104

**Comment by xsamurai** [comment]
@vasilich6107 Thank you, the getter you referenced does not show up for my control.  I'm very new to flutter, maybe its a prob

**Comment by vasilich6107** [comment]
@xsamurai according to the method implementation it will not help you  as far as it takes `showErrors` callback into consideration.

```dart
  String? get errorText {
    if (_showErrors()) {
      final validationMessages = _getValidationMessages(control);
      return validationMessages.containsKey(control.errors.keys.first)
          ? validationMessages[control.errors.keys.first]
          : control.errors.keys.first;
    }

    return null;
  }
```

**Comment by vasilich6107** [comment]
You'll have to implement you own helper for this purposes - just omit the `if` check

**Comment by vasilich6107** [comment]
Hi @xsamurai everything is a little bit different.

You can access to only map of the errors with
`form.errors` or to specific control errors - `form.controls['email']?.errors`

![image](https://user-images.githubusercontent.com/6721286/144580248-00e91ed0-67d5-4606-bd3d-4a9075506dea.png)

**Comment by vasilich6107** [comment]
The second thing is you have to map the error keys on to message texts manually

**Comment by xsamurai** [comment]
@vasilich6107 Thank you, I was under the impression that the ValidationMessages would map to the respective field:

return ReactiveTextField(
      formControlName: 'email',
      validationMessages: (control) => {
        'required': 'Email is required',
        'email': 'Enter a valid email',
      },

Shouldn't this map to the error keys and override the default messages ?

**Comment by joanpablo** [comment]
Hi @xsamurai,

Yes the **validationMessages** of the **ReactiveTextField** overrides the *error's key* with the custom message, but only for that ReactiveTextField widget not globally. You need to apply the same concept to your global notification error widget. You need to map each *key* with a message.

you create your  SnackBar and show errors if the form is invalid, and map each error of each field with a message.

**Comment by xsamurai** [comment]
@joanpablo Thank you for clarifying!
