### ISSUE TITLE
ReactiveDropdownField loss selected value when unfocus

### ISSUE THREAD

**Issue by YisusOnDev** [joanpablo/reactive_forms#246]
Hi, i'm trying to build a reactive form with Text and Dropdowns and i have encountered a problem, when you tap on text field and later you try to select a value from the dropdown sometimes value appears as selected and sometimes not, but always when u switch from the dropdown to other field (change focus) dropdown selected value dissapear.

Example GIF:
![DropDownErrorGif](https://user-images.githubusercontent.com/52821987/145083049-6a684b81-7ffb-4433-b2fb-bff36436b0ab.gif)

How to reproduce:
Just create a reactiveform and combine it with textfield and dropdowns...

FYK: i'm new to flutter and i'm trying my best but i can't find a solution for this... Maybe the error is caused by me so there is some code:

```dart
 TextFieldContainer(
                      child: ReactiveTextField(
                    formControlName: 'city',
                    validationMessages: (control) => {
                      'required': 'The city field must not be empty',
                    },
                    decoration: Util.formDecoration(Icons.apartment, 'City'),
                  )),
                  FutureBuilder(
                    future: _provinceService.getAll(),
                    initialData: const [],
                    builder: (BuildContext context, AsyncSnapshot snapshot) {
                      if (snapshot.hasData) {
                        return TextFieldContainer(
                            child: ReactiveDropdownField<Province>(
                          formControlName: 'province',
                          isExpanded: true,
                          validationMessages: (control) => {
                            'required': 'The province field must not be empty',
                          },
                          decoration: Util.formDecoration(
                              Icons.location_city_rounded, 'Province'),
                          items: getProvinceList(snapshot.data),
                        ));
                      } else {
                        return const CircularProgressIndicator();
                      }
                    },
                  ),
```

Also sorry for my english.

**Comment by YisusOnDev** [comment]
Add: If you fill all text-other fields and then select on all dropdownfield and it works...

Demo:
![DropDownErrorGif2](https://user-images.githubusercontent.com/52821987/145084837-78ae5e83-31e6-4941-b8ac-bb04a4317fe5.gif)

**Comment by vasilich6107** [comment]
Hi @YisusOnDev 
It seems that the issue is in your implementation.

You can run the `example` folder sample app to ensure that the mix of Dropdown and TextField works fine

**Comment by vasilich6107** [comment]
Here is a small proff video

https://user-images.githubusercontent.com/6721286/145212797-cec30b32-2df2-49bf-9eff-f45c4b84ad53.mov

**Comment by YisusOnDev** [comment]
> Hi @YisusOnDev It seems that the issue is in your implementation.
> 
> You can run the `example` folder sample app to ensure that the mix of Dropdown and TextField works fine

Can you send me link to that complex example?

**Comment by YisusOnDev** [comment]
@vasilich6107 Seems like the problem is happening when i use custom object like "Province" and not simple ones like bool, String and so...
![DropDownErrorGif3](https://user-images.githubusercontent.com/52821987/145274599-111f2b99-418e-4fb2-8966-2a0c902c5c33.gif)

How i fill province list:
```dart
ReactiveDropdownField<Province>(
                          formControlName: 'province',
                          isExpanded: true,
                          validationMessages: (control) => {
                            'required': 'The province field must not be empty',
                          },
                          decoration: const InputDecoration(
                            labelText: 'Select a province',
                          ),
                          items: getProvinceList(snapshot.data),
                        );

List<DropdownMenuItem<Province>> getProvinceList(data) {
    final List<DropdownMenuItem<Province>> provinceList = [];
    for (Province p in data) {
      provinceList.add(DropdownMenuItem(child: Text(p.name), value: p));
    }
    return provinceList;
  }
```

Form group:
```dart
final profileForm = FormGroup({
    'name': FormControl<String>(validators: [Validators.required]),
    'rememberMe': FormControl<bool>(validators: [Validators.required]),
    'surname': FormControl<String>(validators: [Validators.required]),
    'birthdate': FormControl<DateTime>(validators: [Validators.required]),
    'province': FormControl<Province>(validators: [Validators.required]),
    'city': FormControl<String>(validators: [Validators.required]),
    'fpgrade': FormControl<FPGrade>(validators: [Validators.required]),
    'fpfamily': FormControl<FPFamily>(validators: [Validators.required]),
    'fpname': FormControl<FP>(validators: [Validators.required]),
    'calification': FormControl<double>(
      validators: [
        Validators.required,
        Validators.min(0.0),
        Validators.max(10.0)
      ],
    )
  });
```

I don't know what i'm doing wrong.

**Comment by YisusOnDev** [comment]
Okay, today i tried to fix my widget and...

Instead of saving the whole object, I have saved the unique id to make an int dropdown instead of an "Object" dropdown. And, it works.

So I don't know what the problem is with using DropDownItem with custom classes.

**Comment by vasilich6107** [comment]
@YisusOnDev you can check the updated example
https://github.com/joanpablo/reactive_forms/pull/247/files

There is no issues with dropdown and complex objects.

**Comment by YisusOnDev** [comment]
> @YisusOnDev you can check the updated example https://github.com/joanpablo/reactive_forms/pull/247/files
> 
> There is no issues with dropdown and complex objects.

Maybe i'm missing methods on my class/object?
```dart
@override
  bool operator ==(Object other) => other is Complex && name == other.name;

  @override
  int get hashCode => hashValues(name, name);
```

**Comment by vasilich6107** [comment]
@YisusOnDev only you can check)

**Comment by YisusOnDev** [comment]
> @YisusOnDev only you can check)

That was the problem or thatrwas the fix haha x), thank you for helping me.

**Comment by YisusOnDev** [comment]
Hi, today i encountered a new problem, now i have the same problem when i put default values to the form. (If form has no values no error happens).

So i'm putting default values:
```dart
_fillForm(user) {
    profileForm.control('name').value = user.name;
    profileForm.control('surname').value = user.lastName;
    profileForm.control('birthdate').value = user.birthDate;
    profileForm.control('province').value = user.province;
    profileForm.control('city').value = user.city;
    profileForm.control('fpgrade').value = user.fp?.fpGrade;
    profileForm.control('fpfamily').value = user.fp?.fpFamily;
    profileForm.control('fpname').value = user.fp;
    profileForm.control('calification').value = user.fpCalification;
  }
```

So when i'm trying to changed a dropdown value this happens: 
![DropDownEditErrorGif1](https://user-images.githubusercontent.com/52821987/146640520-ceccd743-4047-4d60-8fb5-ecc6d2a53a61.gif)


The first problem got fixed just overriding this methods on dropdown class types:
```dart
@override
  bool operator ==(Object other) => other is Province && id == other.id;

  @override
  int get hashCode => hashValues(id, id);
```

**Comment by vasilich6107** [comment]
@YisusOnDev it seems to be the same issues as previous - in your implementation
Check the `complex` sample in `example` folder. It has default form values.
You can enter values in any field and change them without resetting other fields.
Try to use `updateValue` to update the form state.

**Comment by YisusOnDev** [comment]
> @YisusOnDev it seems to be the same issues as previous - in your implementation Check the `complex` sample in `example` folder. It has default form values. You can enter values in any field and change them without resetting other fields. Try to use `updateValue` to update the form state.

Okay, fixed. Thank you again.

**Comment by SaddamMohsen** [comment]
> Here is a small proff video
> 
>  Screen.Recording.2021-12-08.at.15.01.37.mov

how do you implement this when change dropdownvalue the switch button enabled or disabled based on the selected value in dropdown
