### ISSUE TITLE
ReactiveCheckbox does not accept shape property

### ISSUE THREAD

**Issue by samuzaffar99** [joanpablo/reactive_forms#257]
The ReactiveCheckbox widget does not expose the built in shape property of Checkbox to allow for customization of the box.
The following example explains the situation:
ReactiveCheckbox(
    formControlName: 'formName',
	// shape property to make the box rounded
    // shape: RoundedRectangleBorder(
    //   borderRadius: BorderRadius.circular(4), 
    // ),
    activeColor: myColor,
  ),
  currently, I am unable to achieve a rounded checkbox due to this.

**Comment by vasilich6107** [comment]
Check the PRs section
There is one waiting to be merged)

**Comment by vasilich6107** [comment]
For now - you can just copy the code from pr
After PR is merged you'll be able remove it

**Comment by joanpablo** [comment]
Hi @samuzaffar99 

We have released version 11.0.0 that includes that property. Please update to the latest version of Reactive Forms
