### ISSUE TITLE
ReactiveCheckboxListTile: Relation FormControl and FormArray<bool>

### ISSUE THREAD

**Issue by jbt-cii** [joanpablo/reactive_forms#269]
Hello,

I have a form which contains several fields and for one "field" I want to print several checkbox to check or not.
And then I would like to get all the checked elements into one ```FormControl```.
For example like this in HTML:
```
<label for="option_1">Option 1:</label><br>
<input type="checkbox" name="option_1[]" value="1" checked="checked">Choice 1<br>      
<input type="checkbox" name="option_1[]" value="2">Choice 2<br>      
<input type="checkbox" name="option_1[]" value="3">Choice 3<br>
<br>
<label for="option_2">Option 2:</label>
<br>
<input type="checkbox" name="option_2[]" value="1">Choice 1<br>      
<input type="checkbox" name="option_2[]" value="2" checked="checked">Choice 2<br>      
<input type="checkbox" name="option_2[]" value="3" checked="checked">Choice 3<br>
```

In HTML, we get array variables "option_1" and  "option_2" containing all checkboxes and we can verify which checkboxes are checked.
Here a link to another example of what I try to do in Flutter:
https://www.dyn-web.com/tutorials/forms/checkbox/same-name-group.php

In the file "array_sample.dart" I see an example to use ```ReactiveCheckboxListTile```.
But I don't really understand the relationship between a ```FormControl``` element and a ```FormArray<bool>``` element.
Other than the "array_sample.dart" example, are there any other explanations elsewhere in the documentation?

At the end I would like to get a string field (FormControl<String>) containing all the values of the checkboxes checked separated by a comma.
Is there a "simple" way to do that?

**Comment by vasilich6107** [comment]
@jbt-cii you have to have FormControlArray the same as it is in `array_sample`
at the end of the form filling you will have to make something like `form.values['yourArray'].join(', ')`.
Basicaly you'll have to convert list of bools to comma separated string manually.

Otherwise you will have to create your own `Reactive*Control` which will manage all the internals and supply `string` value of concatenated booleans to `FormControl`

**Comment by jbt-cii** [comment]
Thank you for your answer.

```FormControlArray```?
I can't find that in ```array_sample.dart```.

What is the way to declare several ```ReactiveCheckboxListTile``` attached to one ```FormControl```? 
In ```array_sample.dart``` I understand that each ```ReactiveCheckboxListTile``` must have a unique specific ```formControlName```.
So for me they are independent, aren't they?

In fact I try to implement something like a ```ReactiveDropdownField``` with several items in which we can select multiple items... so I try to do with ```ReactiveCheckboxListTile``` (or ```ReactiveSwitchListTile```).

**Comment by vasilich6107** [comment]
@jbt-cii 
https://github.com/joanpablo/reactive_forms/blob/master/example/lib/samples/array_sample.dart#L13

**Comment by vasilich6107** [comment]
> What is the way to declare several ReactiveCheckboxListTile attached to one FormControl?
No way

**Comment by jbt-cii** [comment]
> @jbt-cii https://github.com/joanpablo/reactive_forms/blob/master/example/lib/samples/array_sample.dart#L13

OK! You talk about the same thing I talked about: ```FormArray<bool>```

OK... I continue to search how to use this example to do what I try to do.
Certainly It would be helpful to see the result of the examples in an emulator... but for the moment I can't succeed :-)

**Comment by jbt-cii** [comment]
@vasilich6107 Thank you for your help in the issue #270
Now I can see the "array sample" in action, it certainly will help me :-)

**Comment by vasilich6107** [comment]
@jbt-cii any updates?

**Comment by jbt-cii** [comment]
@vasilich6107 
Sorry I couldn't answer earlier.
For the moment I had to move on to another more urgent project.
But before moving on to another project, the first tests were good, I was able to implement several Checkbox elements and a variable containing all the values (checked and unchecked).
Now I have to deal with them to get what I wanted, but I think I can close this issue.
