### ISSUE TITLE
This is not the issue you are looking for

### ISSUE THREAD

**Issue by Ch4rl3B** [joanpablo/reactive_forms#27]
Hi @joanpablo 

This library really gives me goosebumps. It is the work of a genius !!!

I would like to know if there is the possibility of adding a ValueListenable to the FormGroup for when one is "submitting" the result to be able to block the button.

Recently in one of my apps I had to do this since when the user tapped the button more than once, two or N instances of the model were saved.

Thanks in advance!!

As soon as I have a chance I will pay you a coffee!

**Comment by joanpablo** [comment]
Hi @Ch4rl3B,

Thanks for the issue. I'm very glad that you enjoy using Reactive Forms, and thanks in advance for the coffee hahaha!!!

You have two ways for controlling the SubmitButton action:

1- Enable/Disable button depending of the state of the Form.
2- IF expression to control the validity of the Form when Tab on Button.

Let see both aprouches:

#### Enable/Disable button depending on the state of the Form.
```dart
Future<void> _onPressed(BuildContext context) async {
  // gets view model
  final viewModel = Provider.of<SignInViewModel>(context, listen: false);
  
  // this checks can be also moved to view model signIn() method.
  if (!viewModel.isLoading) {
    await viewModel.signIn();
  }
}

@override
Widget build(BuildContext context) {
  // gets the form and listen form state changes
  final form = ReactiveForm.of(context);

  return RaisedButton(
    // disabled/enabled button deppending on form validity
    onPressed: form.valid ? () => _onPressed(context) : null,
    child: Text('Submit')
  );
}
```
.
#### IF expression to control the validity of the Form when Tab on Button.
```dart
Future<void> _onPressed(BuildContext context) async {
  // gets view model
  final viewModel = Provider.of<SignInViewModel>(context, listen: false);
  
  // this checks can be also moved to view model signIn() method.
  if (viewModel.form.valid && !viewModel.isLoading) {
    await viewModel.signIn();
  } else {
    // this will display errors in not touched controls
    viewModel.form.markAllAsTouched();
  }
}

@override
Widget build(BuildContext context) {
  return RaisedButton(
    onPressed: () => _onPressed(context),
    child: Text('Submit')
  );
}
```

**Comment by Ch4rl3B** [comment]
great!.
I see you are using a Provider on the view so it helps with the work because you can refresh the isLoading variable and the whole view gets it.
That´s an interesting way of doing.... 
Thanks a lot!
