### ISSUE TITLE
Custom reactive widget wiki tutorial outdated

### ISSUE THREAD

**Issue by CharlVS** [joanpablo/reactive_forms#271]
Hi everyone,

I've created an image uploader field widget that returns the uploaded image's bucket path (String) and would like to implement it as a reactive widget. The wiki guide [here](https://github.com/joanpablo/reactive_forms/wiki/Custom-Reactive-Widgets) is not up to date with the current API [here](https://pub.dev/documentation/reactive_forms/latest/reactive_forms/ReactiveFormFieldState-class.html), for ReactiveFormFieldState, which requires a view data type and model data type.

I'd appreciate any help with this.

**Comment by vasilich6107** [comment]
Hi @CharlyZA-2 
Here is a ton of widgets implemented

https://github.com/artflutter/reactive_forms_widgets/tree/master/packages

you can use any of them as reference

**Comment by vasilich6107** [comment]
At the beginning you can set both types to the save value - String in your case

**Comment by CharlyZA-2** [comment]
Thanks a lot. That's great.

**Comment by joanpablo** [comment]
Hi @CharlVS,

The [Custom Reactive Widget](https://github.com/joanpablo/reactive_forms/wiki/Custom-Reactive-Widgets) documentation has been updated.

Please let me know if you find any other outdated documentation.
