### ISSUE TITLE
ReactiveCheckboxListTile: OnChanged Property

### ISSUE THREAD

**Issue by clockwork189** [joanpablo/reactive_forms#273]
Hello,

I was wondering if it was possible to check when an option is selected in a ReactiveCheckboxListTile? In my use case, I got a question with 5 checkboxes such as below:

**What is your favorite color?**
- [ ] Red
- [ ] Blue
- [ ] Green
- [ ] Orange
- [ ] None

A user may select any and all of the checkboxes BUT, if they select "None" I want to un-select all the other checkboxes, and only keep "None" selected. Vice-versa, if "None" is selected and the user selects "Red", I want to unselect "None". The CheckboxListTile has a "onChanged" property: https://api.flutter.dev/flutter/material/CheckboxListTile/onChanged.html. I noticed that the ReactiveCheckboxListTile does not have this. Is there a different way to accomplish this? Below is what my widget looks like:

```
class MultipleChoiceField extends StatelessWidget {
  const MultipleChoiceField({
    Key? key,
  }) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Column(
          children: [
            ReactiveCheckboxListTile(
              controlAffinity: ListTileControlAffinity.leading,
              title: const Text("Red"),
              formControlName: "colors.red",
            ),
            ReactiveCheckboxListTile(
              controlAffinity: ListTileControlAffinity.leading,
              title: const Text("Blue"),
              formControlName: "colors.blue",
            ),
            ReactiveCheckboxListTile(
              controlAffinity: ListTileControlAffinity.leading,
              title: const Text("Green"),
              formControlName: "colors.green",
            ),
            ReactiveCheckboxListTile(
              controlAffinity: ListTileControlAffinity.leading,
              title: const Text("Orange"),
              formControlName: "colors.orange",
            ),
            ReactiveCheckboxListTile(
              controlAffinity: ListTileControlAffinity.leading,
              title: const Text("None"),
              formControlName: "colors.none",
            ),
          ]
        ),
      ],
    );
  }
}
```

Thank you very much for this plugin!

**Comment by vasilich6107** [comment]
@clockwork189 
you need to listen to control value changes
there is a stream to listen to
something like this
https://github.com/joanpablo/reactive_forms/blob/master/lib/src/widgets/reactive_value_listenable_builder.dart#L65

**Comment by clockwork189** [comment]
Got it! That makes sense! Thank you for clarifying and the quick response!

**Comment by BigGitWorld** [comment]
I think you can use ```ReactiveFormConsumer```.
its builder method is called whenever something changes in the form.

```
ReactiveFormConsumer(
                    builder: (context, form, child) {
                     //do something with your form
                      return ElevatedButton(
                        onPressed: form.valid ? () => print(form.value) : null,
                        child: Text('save'),
                      );
                    },
                  ),
```
