### ISSUE TITLE
[Feature Request] Suppress error

### ISSUE THREAD

**Issue by jasonlaw** [joanpablo/reactive_forms#275]
Hi,

I would like all my forms to have validation only on submission (#205), but it would be too tedious to override the showError function for each control. 

Can we have a suppress error method to not show the error? 
My idea is to instantiate the FormControl with suppress error enabled, upon form submission, will reinstate the error (suppress error disabled) for all controls.

With this simple change, it really helps a lot!

Thanks in advance.

**Comment by joanpablo** [comment]
Hi @jasonlaw,

So you want to hide all errors in the UI, and only show them after the user clicks on the Submit method?

**Comment by joanpablo** [comment]
Are you using a State Management Library or just declaring the FormGroup inside a Stateful widget?

**Comment by jasonlaw** [comment]
> Hi @jasonlaw,
> 
> So you want to hide all errors in the UI, and only show all of them after the user clicks on the Submit button?

Yes

**Comment by jasonlaw** [comment]
> @jasonlaw Are you using a State Management Library or just declaring the FormGroup inside a Stateful widget?

I am using GetX.

**Comment by joanpablo** [comment]
Hi @jasonlaw,

The idea is to suppress validation of FormGroup and FormControls or...
that they can still validate as valid or invalid but only hide error messages from the UI until the Submit button clicked?

**Comment by joanpablo** [comment]
don't you like the idea of using **showErrors** and a *flag* in your Controller like *formSubmitAttempt* to manage the show/hide errors? Something like:

```dart
ReactiveTextField(
   formControlName: 'name',
   showErrors: _showErrors
)
...

bool _showErrors(AbstractControl<dynamic> control) {
    return controller.formSubmitAttempt || control.invalid && control.touched;
}
```

and in Submit button you set True or False to the flag *formSubmitAttempt*

Have you tried this?

What other idea do you propose?

**Comment by jasonlaw** [comment]
Hi @joanpablo ,

I have tested with the suggested solution but it is not working, please refer to the video below.

![showErrors](https://user-images.githubusercontent.com/107820/178625361-447aa9f8-2dbd-46e1-9009-ed6b05a4f0cf.gif)

~~~dart
// replace || with &&
return formSubmitAttempt && control.invalid && control.touched;
~~~
![showErrors2](https://user-images.githubusercontent.com/107820/178626843-5ac581d3-fc7c-4a5d-a5f3-6438ef9eabef.gif)

Nevertheless, it would be too tedious to override the showErrors for each controls. I wish there is a more simpler way to achieve  this behavior, which is quite a common standard behavior I guess.

Thanks in advance.

**Comment by joanpablo** [comment]
Hi @jasonlaw 

thanks for sharing the screens. I cannot see your full implementation only a small portion of your code but I believe you are not rebuilding the ReactiveTextFields after clicking the Submit form.

You need to tell the ReactiveTextFields that they need to rebuild again in order to Draw the Red borders and the Error Message.

Below is a simple implementation using a StatefulWidget (with a state management library it works the same), you only need to rebuild the text fields again when setting the `formSubmitAttempt` to true.

```dart
class ValidationSample extends StatefulWidget {
  const ValidationSample({Key? key}) : super(key: key);

  @override
  State<ValidationSample> createState() => _ValidationSampleState();
}

class _ValidationSampleState extends State<ValidationSample> {
  FormGroup get form => fb.group({
        'name': ['', Validators.required],
        'password': ['', Validators.required],
      });

  bool formSubmitAttempt = false;

  @override
  Widget build(BuildContext context) {
    return SampleScreen(
      title: const Text('Validation sample'),
      body: ReactiveFormBuilder(
        form: () => form,
        builder: (context, form, child) {
          return Column(
            children: [
              ReactiveTextField<String>(
                formControlName: 'name',
                decoration: const InputDecoration(
                  labelText: 'Name',
                ),
                validationMessages: {
                  ValidationMessage.required: (_) => 'Field must not be empty',
                },
                showErrors: showErrors,
              ),
              const SizedBox(height: 20),
              ReactiveTextField<String>(
                formControlName: 'password',
                decoration: const InputDecoration(
                  labelText: 'Password',
                ),
                validationMessages: {
                  ValidationMessage.required: (_) => 'Field must not be empty',
                },
                showErrors: showErrors,
              ),
              const SizedBox(height: 20),
              ElevatedButton(
                child: const Text('SUBMIT'),
                onPressed: onSubmit,
              ),
            ],
          );
        },
      ),
    );
  }

  bool showErrors(AbstractControl<dynamic> control) {
    return control.invalid && control.touched && formSubmitAttempt;
  }

  void onSubmit() {
    if (!formSubmitAttempt) {
      setState(() {
        formSubmitAttempt = true;
      });
    }
  }
}
```
![chrome-capture-2022-6-13](https://user-images.githubusercontent.com/37339180/178675336-7e4e8ddb-2bf2-4aef-8970-2889b3e9c3c5.gif)

**Comment by joanpablo** [comment]
I have used a StatefulWidget and ReactiveFormBuilder for simplicity. You don't need to do the same in order to get the same result. You can just use your state management library and a normal ReactiveForm. But remember to rebuild ReactiveTextFields when you set `formSubmitAttempt ` to `true`.

**Comment by jasonlaw** [comment]
Hi @joanpablo ,

It is working now with the rebuild suggestion, thanks!
The solution is working for me, just a bit tedious since I need to override the showErrors for every single control.

Thanks!

**Comment by joanpablo** [comment]
Hi @jasonlaw,

It's good to hear that you solved the issue.

I'm working right in a new version in which you will be able to configure the **showErrors** and **validationMessages** at **ReactiveForm** level and Main App level. That way there is no need to set these properties on each Reactive Child Widget.

**Comment by DumbDev168** [comment]
I wrote a function based on logs below to force validate like below. it works pretty well. hope it helps.

FormGroup controls logs

```
flutter: │ 💡 {
flutter: │ 💡   "first_name": "Instance of 'FormControl<String>'",
flutter: │ 💡   "last_name": "Instance of 'FormControl<String>'",
flutter: │ 💡   "first_phone_number": "Instance of 'FormControl<PhoneNumber>'",
flutter: │ 💡   "second_phone_number": "Instance of 'FormControl<PhoneNumber>'",
flutter: │ 💡   "username": "Instance of 'FormControl<String>'",
flutter: │ 💡   "password": "Instance of 'FormControl<String>'",
flutter: │ 💡   "email": "Instance of 'FormControl<String>'",
flutter: │ 💡   "address": "Instance of 'FormGroup'"
flutter: │ 💡 }
```

a Function to force the validate trigger

```
/// force validate invalid fields 
void validateFormGroup(FormGroup formGroup) {
  final controls = formGroup.controls;
  if (controls.isNotEmpty) {
    controls.forEach((key, value) {
      if (controls[key] is FormControl) {
        if (controls[key]!.invalid) {
          controls[key]!.markAsDirty();
        }
      } else if (controls[key] is FormGroup) {
        validateFormGroup(controls[key] as FormGroup);
      }
    });
  }
}
```
 
 When you call  controls[key]!.markAsDirty() textField will be re-render.

**Comment by joanpablo** [comment]
Hi @DumbDev168, Thanks for share with us your solution. I just want to bring also some other comments:

I see that you are iterating over all controls of the `FormGroup` and marking them as dirty, and then you have overridden the `showErrors` so you show the error if controls are invalid and `dirty`.  While this is OK and will works I want you to know that you can just get the same behavior using just default build-in implementations.

If you use the method `markAllAsTouched` from the `FormGroup` you will get the same results:

```dart
FormGroup formGroup;
// This will mark all children as touched recursively and will force them to show errors.
formGroup.markAllAsTouched();
```

the default implementation of the `showErrors()` methods is to show errors if `control.invalid && touched` so you don´t need to override this method and definitely no need to implement a loop to mark all children as `dirty`.

Thanks for continue supporting of Reactive Forms.

**Comment by DumbDev168** [comment]
> Hi @DumbDev168, Thanks for share with us your solution. I just want to bring also some other comments:
> 
> I see that you are iterating over all controls of the `FormGroup` and marking them as dirty, and then you have overridden the `showErrors` so you show the error if controls are invalid and `dirty`. While this is OK and will works I want you to know that you can just get the same behavior using just default build-in implementations.
> 
> If you use the method `markAllAsTouched` from the `FormGroup` you will get the same results:
> 
> ```dart
> FormGroup formGroup;
> // This will mark all children as touched recursively and will force them to show errors.
> formGroup.markAllAsTouched();
> ```
> 
> the default implementation of the `showErrors()` methods is to show errors if `control.invalid && touched` so you don´t need to override this method and definitely no need to implement a loop to mark all children as `dirty`.
> 
> Thanks for continue supporting of Reactive Forms.

@joanpablo Thanks for this great library. 

Actually I tried to use `markAllAsTouched()` before, but i have to change the `showErrors()` props to validate input while typing. Now I just realized i can just use `markAsTouched()` of current each input when `onChanged ` is called and i don't need to change `showErrors()`. Somehow it seems like Input not `markAsTouched` directly while user is typing until i unfocused the input. I still new with this package maybe i have missed something out.

Again thanks for great library :)

**Comment by joanpablo** [comment]
Hi @DumbDev168,

Thanks again for sharing your experience with us. 

As you mentioned correctly, the control is considered `Touched` once the user interacts with the widget and then removes the focus from it (for example tap/click on another widget). 

Do you think that if the package has a built-in implementation of a method like `markAllAsDirty()` (the same that you manually implemented) will improve your solution? Or do you think that the already built-in methods are enough?

 Looking forward to hearing from you.

**Comment by joanpablo** [comment]
Hi @vasilich6107 what do you think about it?

**Comment by DumbDev168** [comment]
@joanpablo Yes, i think the package should have built-in method like `markAllAsDirty()`, `markAllAsDirtyAndTouched()`, and also should have additional props like `bool enableTouchedOnChanged ` or `bool enableTouchedOnUserInteracted` or whatever name. 

Thanks in advance.

**Comment by joanpablo** [comment]
Thanks, @DumbDev168 for the suggestions.

I will include `markAllAsDirty()` in the next soon release and I will think about the other methods you suggested.
