### ISSUE TITLE
Set field validation state

### ISSUE THREAD

**Issue by haoyuant** [joanpablo/reactive_forms#277]
Hello, I'm migrating my forms to reactive forms, but for the phone number input field, I use https://pub.dev/packages/intl_phone_number_input to handle country code selection and phone number validation. I created a custom reactive form control to wrap this input field, but don't know how to bind the internal validation state to the reactive form control, so I wonder if there is a way for me to directly set if the control is validated or not?

I current solution is 
```
class ReactiveInternationalPhoneNumberInput
    extends ReactiveFormField<PhoneNumber, PhoneNumber> {
  final PhoneNumber? phoneNumber;

  ReactiveInternationalPhoneNumberInput(
      {required String formControlName, this.phoneNumber})
      : super(
            formControlName: formControlName,
            builder: (field) {
              return InternationalPhoneNumberInput(
                // initialValue: phoneNumber ??
                //     PhoneNumber(
                //         isoCode:
                //             WidgetsBinding.instance!.window.locale.countryCode),
                onInputValidated: (validated) {
                  field.control.setValidators([
                    (control) {
                      return validated ? null : {'invalidInput': true};
                    }
                  ]);
                  field.control.updateValueAndValidity();
                },
               ....
)
```

It works but feels not elegant as it keeps resetting the validator as typing. Does anyone have a better solution?

**Comment by vasilich6107** [comment]
Hi @haoyuant 
Here is an example of similar phone field
https://github.com/artflutter/reactive_forms_widgets/blob/master/packages/reactive_phone_form_field/lib/reactive_phone_form_field.dart

Long story short - let the reactive_forms to manage the validation and push the result into decoration manually
https://github.com/artflutter/reactive_forms_widgets/blob/master/packages/reactive_phone_form_field/lib/reactive_phone_form_field.dart#L180

Or even shorter path - use existing input 
https://pub.dev/packages/reactive_phone_form_field

**Comment by vasilich6107** [comment]
@haoyuant any update?

**Comment by joanpablo** [comment]
Closing this issue because no updates received.
