### ISSUE TITLE
Add 'markAsDirty' parameter to AbstractControl.updateValue()

### ISSUE THREAD

**Issue by MBulli** [joanpablo/reactive_forms#278]
As far as I can tell calling `updateValue()` on a `FormControl` programmatically does not mark the control as dirty.
It would be helpful if `updateValue()` had a bool parameter 'markAsDirty' which marks the control as dirty after updating the value.

My use case is a button where I want to reset the value of a `ReactiveDropdownField` with the following handler:

```dart
onClearPressed: form.control('status').value != null
	? () {
		form.control('status').updateValue(null);
		form.control('status').markAsDirty();
	  }
	: null,
```

If `updateValue()` had a parameter to set the control as dirty I could rewrite my code like that:

```dart
onClearPressed: form.control('status').value != null
	? () => form.control('status').updateValue(null, markAsDirty: true)
	: null,
```

I use the dirty state to decide if I have to reload a list, thus, clearing a value needs to trigger a reload.
The default value of the new parameter should be false to avoid a breaking change.

```dart
void updateValue(T? value, {bool updateParent = true, bool emitEvent = true, bool markAsDirty = false});
```

**Comment by joanpablo** [comment]
Hi @MBulli,

I understand that in your specific use case it is nicer to have just 1 line of code:
```dart
form.control('status').updateValue(null, markAsDirty: true);
``` 
instead of 2 lines of code:
```dart
form.control('status').updateValue(null);
form.control('status').markAsDirty();
``` 

But what if somebody on the contrary wants to mark them as Pristine?
```dart
form.control('status').updateValue(null, markAsPristine: true);
``` 

And what about if somebody wants it to be **touched**?
```dart
form.control('status').updateValue(null, markAsTouched: true);
``` 

But, wait and if somebody wanted as **untouched**?
```dart
form.control('status').updateValue(null, markAsUntouched: true);
``` 

And what about the **Focus**?
```dart
form.control('status').updateValue(null, focused: true);
``` 

And remove the **Focus**?
```dart
form.control('status').updateValue(null, unfocused: true);
``` 

So there could be several use cases. How would you imagine the arguments of the **updateValue** method if you want to satisfy all the use cases?

**Comment by MBulli** [comment]
Hi @joanpablo,

sorry for not given a complete example but my focus at work was shifted away from flutter for now.

Yes, a one-liner is temping, given the lean arrow syntax dart allows for lambdas. Plus, I was kinda surprised that the updateValue() method does not mark the field as changed (dirty).

However, I got your point. If my feature request does not fit to the way you want to see your framework evolve I'm totally fine with it. In that case this issue can be closed.
