### ISSUE TITLE
JSON configuration 

### ISSUE THREAD

**Issue by vasilich6107** [joanpablo/reactive_forms#28]
Currently form highly relies on configuration.
It will be great to move to some kind of model which describes the state

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Thanks for the issue. Could you argument a little more the issue so I can completely understand it?
I can deduce that you have the description of a Form in a JSON format, maybe you have the description of the fields of a Product in a Online Shop application, and you want to dinamically create the form based on that JSON? I'm correct? Could you please give me an example for a better understanding?

**Comment by vasilich6107** [comment]
Here is some thoughts
I look at `example` - https://tppr.me/qz275
It requires me to define `email` name 3 times. In simple string format. I tried to make name as enum.name.toString() but form crashes with error. The main concern in this case that I need to precisely control the naming/renaming to avoid errors or apply some workaround that guaranties naming consistency.

If I make try `test.control('email').updateValue(true);` - there is no warning about type mismatch.

Under the `model` approach I ment some way to give full type safety while using the form engine.

**Comment by joanpablo** [comment]
I understand now your issue, I understand your concern and you're right about it, you can make a typo mistake in control names.

There is another way to *bind* widgets with controls, but it is better when using with a state management library or when using in a StateFullWidget. For example:

```dart
/// Represents the Sign In controller/viewModel/bloc/etc
class SignInViewModel {
  final form = fg.group({
    'email': ['', Validators.required, Validators.email],
    'password': ['', Validators.required],
  });

  FormControl<String> get email => this.form.control('email');

  FormControl<String> get password => this.form.control('password');

  Future<void> signIn() async {
    // business logic to sign in
  }
}
```

```dart
class MyWidget extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    final viewModel = Provider.of<SignInViewModel>(context, listen: false);
    viewModel.email.value = true;

    return ReactiveForm(
      formGroup: viewModel.form,
      child: Column(
        children: [
          ReactiveTextField(
            formControl: viewModel.email,
          ),
          ReactiveTextField(
            formControl: viewModel.password,
          ),
          ReactiveStatusListenableBuilder(
            formControl: viewModel.email,
            builder: (context, control, child) => Text('email status changed'),
          ),
        ],
      ),
    );
  }
}
```

This can also be achive if you define the FormGroup within a StatefulWidget.

What do you think about? I you have any other suggestion about how to achive the same results in any other way please let me know?

**Comment by joanpablo** [comment]
Another solution could by define the *Name of the Controls* as **dynamic** instead of **String**.

Actually the *Map* that defines a group is a **Map<String, dynamic>** so names are String and value could be FormControl, FormArray or FormGroup (in case of the FormBuilder the value can be anything that define the type of the control)

```dart
final form = fb.group({
  'email': '', // defines a FormControl<String>
});
```

**fb.group** receives a **Map<String, dynamic>**, it could by changed to **Map<dynamic, dynamic>** so you can define a fb like

```dart
enum SignInFields {
  email,
  password,
}

final form = fb.group({
  SignInFields.email: '',
});
```
But that change will impact all Reactive Forms, it requires to chage all widgets and model. Even the variable names should changed instead of *formControlName* it should by something like *formControlKey*. It will requires a big breaking changes.

Let me know your suggestions please.

**Comment by joanpablo** [comment]
> Here is some thoughts
> I look at `example` - https://tppr.me/qz275
> It requires me to define `email` name 3 times. In simple string format. I tried to make name as enum.name.toString() but form crashes with error. The main concern in this case that I need to precisely control the naming/renaming to avoid errors or apply some workaround that guaranties naming consistency.
> 
> If I make try `test.control('email').updateValue(true);` - there is no warning about type mismatch.
> 
> Under the `model` approach I ment some way to give full type safety while using the form engine.

If you steel want to use some king of *enum* I some times use (in other problems not related to Reactive Forms) a class that defines constants like:

```dart
abstract class SignInFields {
  static const String email = 'email';
  static const String password = 'password';
}

/// Form definition
final form = fg.group({
  SignInFields.email: ['', Validators.required, Validators.email],
  SignInFields.password: ['', Validators.required],
});
```

In fact if you see the code of Reactive Forms the **ValidationMessages** use this aprouch to define the names fro different kind of *validation messages*.

**Comment by joanpablo** [comment]
> Here is some thoughts
> I look at `example` - https://tppr.me/qz275
> It requires me to define `email` name 3 times. In simple string format. I tried to make name as enum.name.toString() but form crashes with error. The main concern in this case that I need to precisely control the naming/renaming to avoid errors or apply some workaround that guaranties naming consistency.
> 
> If I make try `test.control('email').updateValue(true);` - there is no warning about type mismatch.
> 
> Under the `model` approach I ment some way to give full type safety while using the form engine.

In the case of the [example](https://tppr.me/qz275) you can use another strategy.

```dart
/// Defines the form view model
class FormViewModel {
  FormGroup form = fb.group({
    'email': FormControl<String>(
      validators: [Validators.required, Validators.email],
      asyncValidators: [_uniqueEmail],
    ),
    'password': ['', Validators.required, Validators.minLength(8)],
    'passwordConfirmation': '',
    'rememberMe': false,
    'progress': [50.0, Validators.min(50.0)],
    'dateTime': DateTime.now(),
    'time': TimeOfDay.now(),
  }, [
    Validators.mustMatch('password', 'passwordConfirmation')
  ]);

  /// Gets the email
  FormControl<String> get email => this.form.control('email');

  /// Gets the email
  FormControl<String> get password => this.form.control('password');
}
```

```dart
  @override
  Widget build(BuildContext context) {
    final viewModel = FormViewModel();

    return SampleScreen(
      body: ReactiveFormBuilder(
        form: () => viewModel.form,
        builder: (context, form, child) {

          viewModel.email.value = 'some initial value';

          return Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              ReactiveTextField(
                formControl: viewModel.email,
                validationMessages: {
                  ValidationMessage.required: 'The email must not be empty',
                  ValidationMessage.email: 'The email value must be a valid email',
                  'unique': 'This email is already in use',
                },
                onSubmitted: () => viewModel.password.focus(),
                textInputAction: TextInputAction.next,
                decoration: InputDecoration(
                  labelText: 'Email',
                  suffixIcon: ReactiveStatusListenableBuilder(
                    formControl: viewModel.email,
                    builder: (context, control, child) => Visibility(
                      child: ProgressIndicator(),
                      visible: control.pending,
                    ),
                  ),
                ),
              ),
```

**Comment by joanpablo** [comment]
This sample is using a StatefulWidget

```dart
class SignInSample extends StatefulWidget {
  @override
  _SignInSampleState createState() => _SignInSampleState();
}

class _SignInSampleState extends State<SignInSample> {
  final form = fb.group({
    'email': ['', Validators.required, Validators.email],
    'password': ['', Validators.required],
  });

  FormControl<String> get email => this.form.control('email');

  FormControl<String> get password => this.form.control('password');

  @override
  Widget build(BuildContext context) {
    return ReactiveForm(
      formGroup: this.form,
      child: Column(
        children: [
          ReactiveTextField(
            formControl: this.email,
            onSubmitted: () => this.password.focus(),
          ),
          ReactiveTextField(
            formControl: this.password,
            obscureText: true,
          ),
          ReactiveStatusListenableBuilder(
            formControl: this.email,
            builder: (context, control, child) => Text('email status changes'),
          ),
        ],
      ),
    );
  }
}
```

**Comment by marcos930807** [comment]
@joanpablo I use this aproach(class with static const ControlsNameKey) to avoid typo mistakes and for a better looking code.

**Comment by joanpablo** [comment]
Hi @marcos930807,

Thanks for the comment. I am very glad to know that the package is useful for you too. I also use that approach to avoid typo mistakes in control's names.

**Comment by joanpablo** [comment]
> This sample is using a StatefulWidget
> 
> ```dart
> class SignInSample extends StatefulWidget {
>   @override
>   _SignInSampleState createState() => _SignInSampleState();
> }
> 
> class _SignInSampleState extends State<SignInSample> {
>   static const String EMAIL = 'email';
>   static const String PASSWORD = 'password';
> 
>   final form = fb.group({
>     EMAIL: ['', Validators.required, Validators.email],
>     PASSWORD: ['', Validators.required],
>   });
> 
>   FormControl<String> get email => this.form.control(EMAIL);
> 
>   FormControl<String> get password => this.form.control(PASSWORD);
> 
>   @override
>   Widget build(BuildContext context) {
>     return ReactiveForm(
>       formGroup: this.form,
>       child: Column(
>         children: [
>           ReactiveTextField(
>             formControl: this.email,
>             onSubmitted: () => this.password.focus(),
>           ),
>           ReactiveTextField(
>             formControl: this.password,
>             obscureText: true,
>           ),
>           ReactiveStatusListenableBuilder(
>             formControl: this.email,
>             builder: (context, control, child) => Text('email status changes'),
>           ),
>         ],
>       ),
>     );
>   }
> }
> ```

I updated this sample with another possible solution :)

**Comment by tgbarker** [comment]
I wanted to approach this problem more or less, this is what I have come to so far. I haven't explored if it fills all the cases, but it satisfies my needs for the moment and maybe can inspire others.

This is class used in the form config object to encapsulate the form control for each element and also a function to take the value from the Reactive Form Field and assign it to my model object so I don't have to do model.element1 = form.controls('element1').value every time and risk forgetting a line, nor model.fromJson(form.value.toJson()) etc.
```
class FormElement<MODEL, TYPE> {
  final AbstractControl<TYPE> control;
  final MODEL Function(MODEL, TYPE) variableAssign;
  const FormElement({this.control, this.variableAssign});
}
```

This is the base class for any 'form config' object, taking the hash map of FormElement and the generated FormGroup.
```
abstract class BaseFormConfig {
  final Map<String, dynamic> formElements;
  final FormGroup form;
  BaseFormConfig(this.formElements, this.form);
}
```

The subclassing of the form config, with static const identifiers used as keys in the map and also in the flutter widgets. Using freezed on my models hence the copyWith. Each view model that is of type "base form view model" must provide a BaseFormConfig object.
```
class EditHuntForm extends BaseFormConfig {
  static const String title = 'title';
  static const String description = 'description';
  static const String locality = 'locality';

  static Map<String, dynamic> _formElements = {
    title: FormElement<HuntModel, String>(
      control: FormControl<String>(
        validators: [Validators.required],
      ),
      variableAssign: (model, value) => model.copyWith(title: value),
    ),
    description: FormElement<HuntModel, String>(
      control: FormControl<String>(
        validators: [Validators.required],
      ),
      variableAssign: (model, value) => model.copyWith(description: value),
    ),
    locality: FormElement<HuntModel, String>(
      control: FormControl<String>(validators: [], disabled: true),
      variableAssign: null,
    ),
   };

  static FormGroup _form =
  fb.group(_formElements.map((key, value) => MapEntry(key, value.control)));

  EditHuntForm() : super(_formElements, _form);
}
```

The UI code, self explanatory.
```
  ReactiveTextField(
              formControlName: EditHuntForm.title,
              decoration: InputDecoration(
                labelText: tr('title'),
              ),
              validationMessages: (control) =>
                  {ValidationMessage.required: tr('title_not_empty')},
            ),
            ReactiveTextField(
                formControlName: EditHuntForm.description,
                decoration: InputDecoration(
                  labelText: tr('description'),
                )),
            ReactiveTextField(
                formControlName: EditHuntForm.locality,
                decoration: InputDecoration(
                  labelText: tr('locality'),
                )),
```

The submit function of my base form view model class. As you can see, sometimes I want to use the reactive form to display data without assigning values to my model as in this case locality is a derived informative value based on a marker on a map.
```
 Future<bool> submit() async {
    logger.d("FormData : ${formConfig.form.value.toString()}");
    formConfig.formElements.forEach((key, value) {
      if (value.variableAssign != null)
        formModel =
            value.variableAssign(formModel, value.control.value);
      logger.d("$key -> ${value.control.value}");
    });
}
```

Anyways, hope it's clear and you get the 'idea', not perfect as I just did it and haven't reflected, just thought I'd share the general direction that I took to configure my forms and view model in a more structured way. Disclaimer, dart code written by a c++/java/kotlin programmer who is unsure how to adapt to dartiness.

Thanks for the lib @joanpablo , top work.

**Comment by joanpablo** [comment]
Hi @tgbarker,

Thank you for sharing your approach and for your kind words. Your implementation looks very interesting. I will definitely study it very closely, and try to compare it with the different approaches I've been applying in my projects to learn new ways of coding.

Thanks.
