### ISSUE TITLE
Creating Date Picker or Time Picker

### ISSUE THREAD

**Issue by ahmedabdelhafez** [joanpablo/reactive_forms#280]
hello dears,
i cannot create a date picker or time picker

**Comment by vasilich6107** [comment]
@ahmedabdelhafez 
See the example


https://github.com/artflutter/reactive_forms_widgets/blob/master/packages/reactive_date_time_picker/example/lib/main.dart

**Comment by vasilich6107** [comment]
@ahmedabdelhafez any feedback?

**Comment by ahmedabdelhafez** [comment]
Yes I was trying the example in the demo of the package and it's working now
