### ISSUE TITLE
[Feature request] reactive file input field

### ISSUE THREAD

**Issue by chahineaoun** [joanpablo/reactive_forms#282]
Hi,

Most registration forms require an image input at a certain point, so it would be great to be able to integrate that field in the reactive form.

Thanks in advance.

**Comment by vasilich6107** [comment]
@chahineaoun check

https://github.com/artflutter/reactive_forms_widgets

Or leave request for wrapper

https://github.com/artflutter/reactive_forms_widgets/issues/16
