### ISSUE TITLE
Validation dependency

### ISSUE THREAD

**Issue by CripyIce** [joanpablo/reactive_forms#284]
Hi there,
I would like to know how can I make some `FormControl`s validation depends on another 'FormControl' value.
An example from my project:
I have a form that the first `FormControl` is a `ReactiveRadioListTile` the asks the user for family status - `Married` or `Single`.
In case of choosing `Married` a form will be displayed asking for both of the parent's email address.
In case of choosing `Single` a form will be displayed asking for only one of the parent's email address.

In my case I want the second parent email address to be validated only if `Married` is the chosen value

For the meanwhile, I've made two separated forms and added `if` statements on form's validation button.

Here is something I've tried to do but it didn't worked for me:
```dart
 _myForm = FormGroup({
      'parents_family_status': FormControl<int?>(
        validators: [
          Validators.required,
        ],
      ),
      'parent1_email': FormControl<String>(
        validators: [
          Validators.required, // Simple 'required' validation just for testing
        ],
      ),
      'parent2_email': FormControl<String>(),
    }, validators: [
      _familyStatusValidation('parent2_email', 'parents_family_status'),
    ]);


 ValidatorFunction _familyStatusValidation(
      String controlName, String dependencyControlName) {
    return (AbstractControl<dynamic> control) {
      final form = control as FormGroup;

      final formControl = form.control(controlName);
      final dependencyFormControl = form.control(dependencyControlName);

      if (dependencyFormControl.value == null) {
        return null;
      }

      if (dependencyFormControl.value == 1 &&
          formControl.value == null) {
        formControl.setErrors({'required': true});
      } else {
        formControl.removeError('required');
      }

      return null;
    };
  }
```

I hope it's understandable.
Thanks!

**Comment by vasilich6107** [comment]
@CripyIce 
you can also use https://github.com/joanpablo/reactive_forms#reactivevaluelistenablebuilder-to-listen-when-value-changes-in-a-formcontrol
to dynamically add/remove validators to the fields depending on the `parents_family_status` value

**Comment by vasilich6107** [comment]
also you seems to forget

```dart
    // force messages to show up as soon as possible
      matchingFormControl.markAsTouched(); 
```

**Comment by vasilich6107** [comment]
@CripyIce any feedback?

**Comment by CripyIce** [comment]
@vasilich6107 Thanks for the snippets!
I would have to create a new Flutter project and try to solve my issue because it’s hard for me to try it in my current project.
For the meanwhile I replaced the validation dependency with a simple if checks…

I will post a new comment when I’ll create the new project.

**Comment by joanpablo** [comment]
Hi @CripyIce 

Any update on this??

**Comment by joanpablo** [comment]
Closing the issue because we don't have any update on it
