### ISSUE TITLE
How to  prevent a from entering text in Reactive Text Input with number validation 

### ISSUE THREAD

**Issue by krista30** [joanpablo/reactive_forms#286]
Hi Pablo, apart from showing an error message, is there a way I can prevent a person from entering text in the ReactiveTextInput when validating a field for only numbers. Thanks

**Comment by vasilich6107** [comment]
Subscribe on field changes, save prev value and in case if next value is not valid reset back to prev

**Comment by krista30** [comment]
Thanks @vasilich6107 .

**Comment by joanpablo** [comment]
Hi @krista30,

Another way to prevent input from the user in a Text Field is using [TextInputFormatter](https://api.flutter.dev/flutter/services/TextInputFormatter-class.html)
