### ISSUE TITLE
Simple FormArray example

### ISSUE THREAD

**Issue by krista30** [joanpablo/reactive_forms#288]
Hi Pablo,

Is there a simple example of FormArray which doesn't use inherited Widgets.

**Comment by vasilich6107** [comment]
What's the issue with inherited widgets?

**Comment by krista30** [comment]
Inherited Widgets don't solve my problem. I just want some thing simple that uses stateless widgets because at a later stage am going to use bloc to handle the statement

**Comment by krista30** [comment]
I have found the solution of what I wanted to accomplish. I will mark this as closed
