### ISSUE TITLE
Error text display approach

### ISSUE THREAD

**Issue by vasilich6107** [joanpablo/reactive_forms#29]
Currently `ReactiveFormField` has `String get errorText` in which specifies in which cases control should show error message(INVALID && TOUCHED).

I would like to have an ability to control precisely when error is shown.
The are varieties of strategies how to display errors. The INVALID && DIRTY is a good example.
There could be a case when I want to show errors only on INVALID && TOUCHED && DIRTY.

In any case I would be great to have an ability to override default behaviour.

**Comment by joanpablo** [comment]
Thanks @vasilich6107 

I will think about the issue and let you know a solution. Maybe could be a callback in Reactive Widgets (like ReactiveTextField) that returns a *bool* and receives the control something like:

```dart
ReactiveTextField(
  formControlName: 'email',
  showErrors: (control) => control.invalid && control.touched && control.dirty,
),
```

What do you think about that approach?

**Comment by joanpablo** [comment]
Do you think it should be a custom handler that manages all errors or one handler by type of error?? Something like:

````dart
ReactiveTextField(
  formControlName: 'email',
  validationMessages: {
    ValidationMessages.required: {
       'message': 'The email must not be null',
       'visible': (control) => control.invalid && control.touched && control.dirty,
    },
    ValidationMessages.email: {
       'message': 'The email must be a valid email',
       'visible': (control) => control.invalid && control.touched,
    }
  }
),
```

**Comment by vasilich6107** [comment]
I think first solution is more reasonable

**Comment by joanpablo** [comment]
> Currently `ReactiveFormField` has `String get errorText` in which specifies in which cases control should show error message(INVALID && TOUCHED).
> 
> I would like to have an ability to control precisely when error is shown.
> The are varieties of strategies how to display errors. The INVALID && DIRTY is a good example.
> There could be a case when I want to show errors only on INVALID && TOUCHED && DIRTY.
> 
> In any case I would be great to have an ability to override default behaviour.

Hi @vasilich6107 ,

I have just release Reactive Forms 5.0.4

- Add optionally argument *showErrors* to **ReactiveTextField** and **ReactiveDropdownField** 
to customize when to show up validations messages. Validation messages by default change to visible 
when control is *invalid* and *touched*. With *showErrors* function this default behavior can be 
customized.

Customize when to show up validation messages.
```dart
ReactiveTextField(
  formControlName: 'email',
  showErrors: (control) => control.invalid && control.touched && control.dirty,
),
```
