### ISSUE TITLE
How to Track Radio List Tile Value

### ISSUE THREAD

**Issue by krista30** [joanpablo/reactive_forms#291]
How can I track the Id value when I select the Reactive Radio List option

**Comment by joanpablo** [comment]
Hi @krista30

Could you give more details about the issue? Sorry, but I did not get your question.

**Comment by krista30** [comment]
Thank you @joanpablo for the swift response.  I wanted to track the value e.g an id of  an option that is selected from the list of Reactive Radio List options
 on a screen. I tried to do this with a native flutter Radio Tile List widget and it worked. Is there a way I can do the same thing with the Reactive Radio Tile List.
