### ISSUE TITLE
Remove control doesn't work as intended

### ISSUE THREAD

**Issue by JSBmanD** [joanpablo/reactive_forms#292]
I have function that removes control when I need - `formSettings.formGroup.removeControl(openFieldName);`

When I call this function - it throws an exception that control not found but removes field successfully.

Plugin - ^13.0.0
```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.0, on macOS 12.3.1 21E258 darwin-arm, locale en-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 13.4)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.3.3)
[✓] VS Code (version 1.67.2)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

! Doctor found issues in 2 categories.
```

**Comment by vasilich6107** [comment]
If you create a copypastable and runable main.dart I'll try to help you

**Comment by joanpablo** [comment]
Hi @JSBmanD,

Thanks for the issue. Would you mind giving us more details, for example, 
- the structure of your FormGroup
- The name of the FormControl you want to remove
- Are you adding dynamically the FormControl or not

with more details, we can have a better understanding of the situation.

Thanks in advance

**Comment by joanpablo** [comment]
Close the issue due to lack of update. Don't hesitate to reopen it or create a new one.
