### ISSUE TITLE
Multi select selects all the options at once

### ISSUE THREAD

**Issue by krista30** [joanpablo/reactive_forms#294]
Hi team,

Thanks for this great library. Am trying to parse data to a reactive checkbox list tile. Am able to parse the data and the list gets displayed. How do I make sure that when I select one of the options from the checkbox list, all the other options don't get selected automatically ?
```
for (int i = 0; i < questions.options.length; i++)
              ReactiveCheckboxListTile(
                activeColor: PrimaryColor,
                controlAffinity: ListTileControlAffinity.leading,
                formControlName: questions.key,
                title: Text('${questions.options[i]['value']}',
                  style: TextStyle(color: Colors.white),),
              ),
```

**Comment by vasilich6107** [comment]
If you create a copypastable and runable main.dart I'll try to help you

**Comment by krista30** [comment]
`import 'package:flutter/material.dart';
import 'package:reactive_forms/reactive_forms.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final form = FormGroup({});



  List answerOptions = [
      {
        'id': 'hjdhjdh',
        'value': 'Option 1'
      },
      {
        'id': 'hjdhjdh',
        'value': 'Option 2'
      },
      {
        'id': 'hjdhjdh',
        'value': 'Option 3'
      },
      {
        'id': 'hjdhjdh',
        'value': 'All'
      }
    ];

  @override
  Widget build(BuildContext context) {

    form.addAll({
      'questionAnswers': FormControl<bool>(),
    });

    return  Scaffold(
      body: SafeArea(
        child: Column(
            children: [
              ReactiveForm(
                  formGroup: form,
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      const Text('Question !'),
                      for (int i = 0; i < answerOptions.length; i++)
                        ReactiveCheckboxListTile(
                          activeColor: Colors.greenAccent,
                          controlAffinity: ListTileControlAffinity.leading,
                          formControlName: 'questionAnswers',
                          title: Text('${answerOptions[i]['value']}',
                            style: const TextStyle(color: Colors.black),),
                        ),
                    ],
                  )
              )
            ]
        ),
      ),
    );
  }
}
`

**Comment by vasilich6107** [comment]
Thanks
Will take a look
