### ISSUE TITLE
ControlValueAccessor

### ISSUE THREAD

**Issue by zl910627** [joanpablo/reactive_forms#30]
I am going to trim input values before validation.
To do that, I am trying to use `ReactiveTextField.valueAccessor`
i.e
```Dart
class TrimAccess extends ControlValueAccessor<String, String> {
String viewToModelValue(String viewValue) => viewValue.trim();
String modelToViewValue(String modelValue) => modelValue;
}
```

But whenever trim, cursor will move to begin of text.
* How can I resolve this properly?
* Is my solution right one?

Thank you

**Comment by joanpablo** [comment]
Hi @zl910627,

I've tried your TrimAccess class and it works fine for me. Could you please give a full example of your code?
form example this is what I have tested:

```dart
class TrimValueAccessor extends ControlValueAccessor<String, String> {
  @override
  String modelToViewValue(String modelValue) => modelValue;

  @override
  String viewToModelValue(String viewValue) => viewValue.trim();
}
```

```dart
ReactiveTextField(
   formControlName: 'email',
   valueAccessor: TrimValueAccessor(),
)
```

when I write in Text Field everything works fine.

**Comment by zl910627** [comment]
I am sorry, I may sleep a bit when test this code.
thank you for your quick support!
