### ISSUE TITLE
Should form.dispose() method need to be called?

### ISSUE THREAD

**Issue by kavienanj** [joanpablo/reactive_forms#308]
I have `form = FormGroup(...)` as a final variable in my stateless widget `MyFormGroup()`. I provide the form object to the `ReactiveForm(...)` widget in the build method. Will the `ReactiveForm` widget takes care of disposing of the form object or should I turn my stateless widget into a stateful widget so that I can include `form.dispose()` in the `dispose()` method.

**Comment by kavienanj** [comment]
> I suppose that the reason why builder and consumer does not call dispose is that there could be high chance that they are not owners of form object.
> So it would be strange to dispose someone else’s property)))

My biggest concern is the FormGroup dispose method cancels subscriptions made to each form control stream object. It's always recommended to cancel the stream subscriptions at the end right to protect from memory leaks? Does the documentation mention anything about this?

**Comment by joanpablo** [comment]
Hi @kavienanj,

It is up to you to call the **dispose()** on an **AbstractControl** (FormGroup, FormControl, FormArray). 

The dispose method in an AbstractControl basically removes all stream subscriptions.

All Reactive widgets like for example **ReactiveValueListenableBuilder** and **ReactiveStatusListenableBuilder** unsubscribe from the corresponding Streams so no need to directly call the dispose on a Control. 

But it is always up to the developer to determine when to dispose of a FormGroup.

**Comment by kavienanj** [comment]
Thanks for the valuable information @joanpablo and @vasilich6107. And thank you for this amazing package!.
