### ISSUE TITLE
Validation message for all validators

### ISSUE THREAD

**Issue by shabanov-krl** [joanpablo/reactive_forms#311]
please, add validationMessage parametr for all validators, like as pattern validator

**Comment by joanpablo** [comment]
Hi @shabanov-krl 

We have released version `14.1.0` of **Reactive Forms**, in which we can define validation messages Globally. You can find documentation [here](https://github.com/joanpablo/reactive_forms#2-globalapplication-level).

Please give it a look and don´t hesitate to create a new issue if you have new suggestions or issues.

Thanks once again for your support.

Please let me know if the new version covers all your needs.
