### ISSUE TITLE
BloC Integration

### ISSUE THREAD

**Issue by vicenterusso** [joanpablo/reactive_forms#317]
What would be a realistic integration with bloc? Documentation mention it but there is no example anywhere

**Comment by joanpablo** [comment]
Hi @vicenterusso,

Thanks for asking. Reactive Forms is not a substitute for any State Management Library (SML), all the contrary, it is best suitable when using an SML. Reactive Forms is a way to get, set, and validate Forms in Flutter much easier that doing the same things natively.

If you have any experience working in Angular you would know that you still need a Controller(Component/Bloc/Provider) that handles the business logic and host the FormGroup definition, and then you bind this FormGroup with a View/UI. The FormGroup will give you access to all data and validation of the Form without directly interacting with the UI.

I can try to implement a simple example here in this issue. A future plan is to have a more robust documentation website and blog for the library. It is still in progress.

But feel free to post any implementation here and we will help you to guide you in the best practices of the integration.

Best regards

**Comment by joanpablo** [comment]
Hi @vicenterusso in [this](https://github.com/joanpablo/reactive_forms/issues/318) post you can read a simple implementation using Bloc (Cubit) and Reactive Forms.

**Comment by vicenterusso** [comment]
Tks for the example, @joanpablo .

But I was thinking something more integrated. there is no BloC/Cubit integration in your code, something like changing cubit states on every form changes. I could use cubit for custom validation rules.

I think thats the way I need to do, use FormGroup for basic/individual input validation and more complex rules inside cubit, (or anywhere), but in that case, I need to replicate all values to the cubit state. Or even the while FormGroup in just one property, I don't know :D

**Comment by joanpablo** [comment]
Hi @vicenterusso 

In the simple example that I show you I have used the  Bloc/Cubit/Provider/Controller/ViewModel to handle the state of loading (and possibly submit) data to the server. And The responsibility for collecting and validating data from the user to the Form (Reactive Form). Bothe responsibilities were separated.

You can always listen to FormGroup changes if you subscribe to `FormGroup.valueChange` and trigger more complex states of your Provider/Bloc. 
You can also have the possibility to create custom validators with complex logic, if which you will have access to all the Form data, no need to replicate anything.

You have serveral options to build your solution based on requeriments.

Would you mind to give me a more specific example of what you would like to achieve?

**Comment by vicenterusso** [comment]
I think I got it! Found some examples on "Migration-Guide". IMO the it's the best feature, hidden!

**Comment by joanpablo** [comment]
Thanks @vicenterusso 

I want to release a better and dedicated documentation website. With examples tutos and a blog. I'm working right now in the next release of the library and then I will focus on this idea. And also I would like to create a logo.

It will requires effort and time but I committed on it.

Thanks for the support. And don't hesitate to create another issue if you have more questions
