### ISSUE TITLE
Question: Is it possible to have Validator and keep field optional?

### ISSUE THREAD

**Issue by leonidlist** [joanpablo/reactive_forms#333]
I have a field that should contain only numbers, I use `Validators.number` for that, but the whole form is not valid if I don't input that field with number validator. So is it possible to have that validator and keep number field optional?

**Comment by joanpablo** [comment]
Hi @leonidlist,

Thanks for using **Reactive Forms** and for the issue. You are right, the `Validators.number` validates that the control is not null and complies with a sequence of digits.

A solution is to create a composition of validators (i.e: control can be `null` or `number`):

```dart
final control = FormControl<String>(
    validators: [
        Validators.composeOR([
            Validators.composeOR([Validators.equals(''), Validators.equals(null)]),
            Validators.number,
        ]),
    ],
);
```

Let me know if this solution solves your issue.

**Comment by joanpablo** [comment]
Thanks to you for your kind words @leonidlist, Have a nice day.

**Comment by samderlust** [comment]
> ```dart
> final control = FormControl<String>(
>     validators: [
>         Validators.composeOR([
>             Validators.composeOR([Validators.equals(''), Validators.equals(null)]),
>             Validators.number,
>         ]),
>     ],
> );
> ```

@joanpablo But this only works when i use `FormControl<String>`. If I want to use `FormControl<double>` it failed to work. Do you have any idea?
