### ISSUE TITLE
Please update the intl package to v0.18.0

### ISSUE THREAD

**Issue by chunghha** [joanpablo/reactive_forms#348]
Please update the intl package to v0.18.0 so we can avoid this error on resolving dependencies:

`Because reactive_forms >=9.1.0 depends on intl ^0.17.0`

https://pub.dev/packages/intl/changelog

**Comment by chunghha** [comment]
thanks, @limenote135.

@joanpablo would you review the PR for a merge?

**Comment by limenote135** [comment]
@joanpablo, could you please release new version including this fix?

**Comment by joanpablo** [comment]
I want to let you know that a new version has been deployed with the latest intl package: version 14.2.0.
Thanks for the issue.

Please let me know if you have any other issues with this last update.
