### ISSUE TITLE
Form values are not updating in  fromarray of formgroup

### ISSUE THREAD

**Issue by techaks** [joanpablo/reactive_forms#35]
**form values Listeners is working **

`
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:reactive_forms/reactive_forms.dart';
import 'package:voopik_seller/data/models/physical_condition.dart';
import 'package:voopik_seller/pages/common/bloc/common_bloc.dart';
import 'package:voopik_seller/ui/widgets/form_row.dart';
import 'package:voopik_seller/ui/widgets/input/checkbox_group.dart';
import 'package:voopik_seller/ui/widgets/input/radio_group.dart';
import 'package:voopik_seller/ui/widgets/input/reactive_input.dart';
import 'package:voopik_seller/ui/widgets/lr_row.dart';
import 'package:voopik_seller/ui/widgets/widgets.dart';

class NewProductForm extends StatefulWidget {
  final GlobalKey<FormState> formkey;
  NewProductForm({@required this.formkey});

  @override
  _NewProductFormState createState() => _NewProductFormState();
}

class _NewProductFormState extends State<NewProductForm> {
  final form = FormGroup({
    'title': FormControl(validators: [Validators.required]),
    'author': FormControl(validators: [
      Validators.required,
    ]),
    'publication': FormControl(validators: [
      Validators.required,
    ]),
    'isbn': FormControl(validators: [
      Validators.required,
    ]),
    'edition': FormControl(validators: [
      Validators.required,
    ]),
    'physicalConditionId': FormControl(validators: [
      Validators.required,
    ]),
    'bindingFormatId': FormControl(validators: [
      Validators.required,
    ]),
    'packaging': FormGroup({
      'width': FormControl(validators: [
        Validators.required,
      ]),
      'height': FormControl(validators: [
        Validators.required,
      ]),
      'weight': FormControl(validators: [
        Validators.required,
      ]),
      'length': FormControl(validators: [
        Validators.required,
      ]),
    }),
    'deliveryCharges': FormGroup({
      'local': FormControl(validators: [
        Validators.required,
      ]),
      'zonal': FormControl(validators: [
        Validators.required,
      ]),
      'national': FormControl(validators: [
        Validators.required,
      ]),
    }),
    'inventories': FormArray<Map<String, dynamic>>([]),
  });

  FormArray<Map<String, dynamic>> get selectedInventories =>
      form.control('inventories') as FormArray;

  @override
  void initState() {
    super.initState();
  }

  _onValidate() {
    // if (formkey.currentState.validate()) {
    //   print(formkey.currentState.validate());
    //   formkey.currentState.save();
    // }

    print(form.valid);
    print(form.value);
  }

  @override
  Widget build(BuildContext context) {
    return ReactiveForm(
      formGroup: this.form,
      child: IContainer(
        child: Column(
          children: [
            _buildBookDetail(),
            _buildBindingFormat(),
            _buildBookCondition(),
            _buildPackagingDetail(),
            _buildDeliveryCharge(),
            SizedBox(
              height: 30,
            ),
            VRaisedButton(
              title: 'Start Selling',
              onPressed: _onValidate,
            ),
            SizedBox(
              height: 30,
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildBookDetail() {
    return FormRow(
      title: 'Book Details',
      children: [
        ReactiveInput(
          formControlName: 'title',
          labelText: 'Title',
        ),
        ReactiveInput(
          formControlName: 'author',
          labelText: 'Author',
        ),
        ReactiveInput(
          formControlName: 'publication',
          labelText: 'Publication',
        ),
        ReactiveInput(
          formControlName: 'isbn',
          labelText: 'ISBN no.',
          helperText:
              'You can find it at the back side of the book with barcode',
        ),
        ReactiveInput(
          formControlName: 'edition',
          labelText: 'Edition',
        ),
      ],
    );
  }

  Widget _buildPackagingDetail() {
    final packagingForm = form.control('packaging');

    return ReactiveForm(
      formGroup: packagingForm,
      child: FormRow(
        title: 'Packaging Details',
        children: [
          LRRow(
            left: ReactiveInput(
              formControlName: 'weight',
              labelText: 'Weight',
              suffixText: 'gm',
              keyboardType: TextInputType.number,
            ),
            right: ReactiveInput(
              formControlName: 'height',
              labelText: 'Height',
              suffixText: 'cm',
              keyboardType: TextInputType.number,
            ),
          ),
          LRRow(
            left: ReactiveInput(
              formControlName: 'width',
              labelText: 'Width',
              suffixText: 'cm',
              keyboardType: TextInputType.number,
            ),
            right: ReactiveInput(
              formControlName: 'length',
              labelText: 'Length',
              suffixText: 'cm',
              keyboardType: TextInputType.number,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildDeliveryCharge() {
    final _deliverForm = form.control('deliveryCharges');

    return ReactiveForm(
      formGroup: _deliverForm,
      child: FormRow(
        title: 'Delivery Charges',
        children: [
          ReactiveInput(
            formControlName: 'local',
            labelText: 'Local Delivery charges',
            suffixText: 'INR',
          ),
          ReactiveInput(
            formControlName: 'zonal',
            labelText: 'Zonal Delivery Charges',
            suffixText: 'INR',
          ),
          ReactiveInput(
            formControlName: 'national',
            labelText: 'National Delivery Charges',
            suffixText: 'INR',
          ),
        ],
      ),
    );
  }

  Widget _buildBookCondition() {
    return BlocBuilder<CommonBloc, CommonState>(
      builder: (context, state) {
        final conditions = state.conditions;

        final conditionFg = conditions.map((e) => FormGroup({
              'condition': FormControl(value: e.id),
              'quantity': FormControl(value: 'dasds'),
              'sellingPrice': FormControl(),
              'isSelected': FormControl(value: true),
            }));

        selectedInventories.clear();
        selectedInventories.addAll(conditionFg);

        print('===== bUILDING====');

        return FormRow(
            title: 'Book Condition & Selling Price',
            child: ReactiveFormArray(
              formArrayName: 'inventories',
              builder: (BuildContext context, FormArray<dynamic> formArray,
                  Widget child) {
                final cities = selectedInventories.controls
                    .map((control) => control as FormGroup)
                    .map((currentform) {
                  final index =
                      selectedInventories.controls.indexOf(currentform);
                  final selectedCondition = conditions.elementAt(index);

                  // currentform.valueChanges.listen((event) {
                  //   // selectedInventories.controls
                  //   //     .elementAt(index)
                  //   //     .updateValue(event);

                  //   // print(currentform.value);
                  //   // form.updateValueAndValidity();
                  //   setState(() {
                  //     currentform.updateValue(event,
                  //         updateParent: true, emitEvent: true);
                  //   });
                  // });

                  return ReactiveForm(
                      formGroup: currentform,
                      child: Container(child: getCheckbox(selectedCondition)));
                });

                return Wrap(
                  runSpacing: 20,
                  children: cities.toList(),
                );
              },
            ));
      },
    );
  }

  Widget _buildBindingFormat() {
    return BlocBuilder<CommonBloc, CommonState>(
      builder: (context, state) {
        return FormRow(
          title: 'Binding Format',
          child: ReactiveRadioGroup(
            formControlName: 'bindingFormatId',
            data: state.formats
                .map(
                  (e) => RadioGroupItem(id: e.id, name: e.name),
                )
                .toList(),
          ),
        );
      },
    );
  }

  Widget getCheckbox(PhysicalCondition e) {
    return CheckboxGroupItem(
      formControlName: 'isSelected',
      name: e.name,
      child: Column(
        children: [ReactiveInput(formControlName: 'quantity')],
      ),
    );
  }
}
`

**Comment by joanpablo** [comment]
Hi @techaks,

Thanks for the issue and thanks for using Reactive Forms.

I have carefully study your code. To solve your issue put **.toList()** and the end of the **conditionFg**. When you do a mapping the created type form variable **conditionFg** is:

```dart
MappedListIterable<PhysicalCondition, FormGroup>
```

but the **array.addAll** method is expected a:

```dart
Iterable<FormGroup>
```

So due type missmatch the ReactiveForm and children are not correctly binded.

To solve the issue just replace this:

```dart
final conditionFg = conditions.map((e) => FormGroup({
          'condition': FormControl(value: e.id),
          'quantity': FormControl(value: 'dasds'),
          'sellingPrice': FormControl(),
          'isSelected': FormControl(value: true),
        }));

    selectedInventories.clear();
    selectedInventories.addAll(conditionFg);
```

with this:

```dart
final conditionFg = conditions.map((e) => FormGroup({
          'condition': FormControl(value: e.id),
          'quantity': FormControl(value: 'dasds'),
          'sellingPrice': FormControl(),
          'isSelected': FormControl(value: true),
        }));

    selectedInventories.clear();
    selectedInventories.addAll(conditionFg.toList()); // notice '.toList()' here
```

**Comment by joanpablo** [comment]
Hi @techaks,

I've just release v6.0.3 that force all arguments to be of type **List**, instead of type **Iterable**. That change will help to mitigate issues like the one you have presented.

Thanks

**Comment by joanpablo** [comment]
Hi @techaks 

If you allow me I can make a suggestion about your code.

Looking at the way you are adding elements to the array of groups, you don't need to use the **ReactiveFormArray** widget.

You should use **ReactiveFormArray** when you want to be notified every time the **FormArray** changes and you want to rebuild the view. But in your example you are already being notified by a **BlocBuilder** and you are directly filling in the array. So in that case the **ReactiveFormArray** is usless to you, and you can directly return your **Wrap** of **ReactiveForm**.

**Comment by joanpablo** [comment]
Hi again @techaks 

I've release a version 6.0.4 that may also help you.

If you pretend to call **clear()** and then insert new items in a array you can call:
```dart
array.clear(emitEvent: false, updateParent: false);
array.addAll(items);
```

that way you improve a little the performance since you don't need to emit events or update the array's parent (group) until you add the items in the line of code below.

**Comment by techaks** [comment]
@joanpablo Thanks, man it is working now.
