### ISSUE TITLE
Ignore Field Validation if field not touched

### ISSUE THREAD

**Issue by sagnik-sanyal** [joanpablo/reactive_forms#373]
How to ignore validation if field is not touched, let's say we have a formgroup under which there is a login method toggle of email and mobile. Whenever I have selected email i need to validate email and ignore mobile and similarly vice versa. How is this achievable using this package? Any help would be great

**Comment by joanpablo** [comment]
Hi @sagnik-sanyal,

In order to accomplish this, you may implement 2 approaches:

- Create a validator at FormGroup level.
- Create 2 different validators, one for email and another for phone number field.

Let's start with the second approach. You may create a validator for the email field that takes into account the mentioned boolean value (the one that defines if the user registration is by email or phone).

The custom validator should looks like the following code:

```dart
Map<String, dynamic> _isRequiredEmail(AbstractControl<dynamic> control) {
  return (isEmailRegistration && Validators.email(control)) || isPhoneRegistration
  ? null
  : {ValidationMessage.email: control.value};
}
```

**Comment by sagnik-sanyal** [comment]
Hi thanks for your reply, I will surely try this one out !! Closing this issue as of now,

**Comment by sagnik-sanyal** [comment]
Hi @joanpablo i tried doing this but this is the scenario i have a boolean _isEmail, if true then email registration and if false mobile registration and this is my form group code

_form = FormGroup(
      <String, AbstractControl<dynamic>>{
        'email': FormControl<String>(
          validators: <FormControlValidators>[_emailValidator],
        ),
        'mobile': FormControl<String>(
          validators: <FormControlValidators>[_mobileValidator],
        ),
        'password': FormControl<String>(
          validators: <FormControlValidators>[
            Validators.required,
            Validators.minLength(8),
          ],
        ),
        'isRemembered': FormControl<bool>(value: false),
      },
 );


Meanwhile these are the validators , 
//Validate Email
  Map<String, dynamic>? _emailValidator(AbstractControl<dynamic> control) {
    if (!_isEmail) return null;
    return Validators.compose(<FormControlValidators>[
      Validators.required,
      Validators.email
    ])(control);
  }

  //Validate Mobile
  Map<String, dynamic>? _mobileValidator(AbstractControl<dynamic> control) {
    if (_isEmail) return null;
    return Validators.compose(<FormControlValidators>[
      Validators.required,
      Validators.number
    ])(control);
  }

And in the toggle method , i am calling the below method

void toggle() {
    _isEmail = !_isEmail;
    if (_isEmail) {
      form.controls['mobile']?.reset();
      form.controls['mobile']?.updateValueAndValidity();
    } else {
      form.controls['email']?.reset();
      form.controls['email']?.updateValueAndValidity();
    }
    notifyListeners();
  }

But this doesn't seem to work, can you suggest me where the approach is going wrong because i am having the keys in a single formGroup.

**Comment by joanpablo** [comment]
Hi @sagnik-sanyal 

 This following code that you posted has some issues:
```
void toggle() {
 _isEmail = !_isEmail;
if (_isEmail) {
form.controls['mobile']?.reset();
form.controls['mobile']?.updateValueAndValidity();
} else {
form.controls['email']?.reset();
form.controls['email']?.updateValueAndValidity();
}
notifyListeners();
}
```

First: you want to `reset()` both FormControls
always, no matter what type of login it is.

Second: No need to call 
`updateValueAndValidity()` if you are calling the reset() method. The reset() method will set the default value for the control, and will mark it as untouched and pristine.
