### ISSUE TITLE
Great support, And...

### ISSUE THREAD

**Issue by zl910627** [joanpablo/reactive_forms#4]
Hello @joanpablo 
I am going to build form dynamically.
But when build `ReactiveForm` inside `ValueListenableBuilder` or `StreamBuilder`, I got below error.

Here is my widget.
```Dart
StreamBuilder<FormGroup>(
  stream: _formGroup.subject.stream,
  builder: (ctx, snapshot) {
    if (!snapshot.hasData) {
      return Container(
        color: Colors.red,
      );
    }

    final group = snapshot.data;
    return ReactiveForm(
      formGroup: group,
      child: ListView(
        physics: BouncingScrollPhysics(),
        children: [
          ReactiveTextField(
            formControlName: 'name',
            decoration: InputDecoration(
              labelText: 'Train Name',
            ),
          ),
          ReactiveTextField(
            formControlName: 'durationSeconds',
            decoration: InputDecoration(labelText: 'Duration in Second'),
            inputFormatters: [
              FilteringTextInputFormatter.digitsOnly,
            ],
          ),
        ],
      ),
    );
  },
)
```

Here is my form group.
```Dart
final Rx<FormGroup> _formGroup;
//...
_formGroup.value = FormGroup({
  'name': FormControl<String>(
    defaultValue: train?.name,
    validators: [Validators.required],
  ),
  'durationSeconds': FormControl<int>(
    defaultValue: train?.durationSeconds,
    validators: [Validators.required],
  ),
});
```

Here is error log
```
packages/flutter/src/widgets/framework.dart 4737:11                                                                        performRebuild
...
════════════════════════════════════════════════════════════════════════════════
Error: notifyClients for FormControlInheritedStreamer was called at an inappropriate time.
It may only be called while the widgets are being built.
A possible cause of this error is when notifyClients is called during one of:
 * network I/O event
 * file I/O event
 * timer
 * microtask (caused by Future.then, async/await, scheduleMicrotask)
    at Object.throw_ [as throw] (http://localhost:53485/dart_sdk.js:4334:11)
    at http://localhost:53485/packages/flutter/src/widgets/widget_span.dart.lib.js:22802:21
    at inherited_streamer._InheritedNotifierElement.new.[_debugCheckOwnerBuildTargetExists] (http://localhost:53485/packages/flutter/src/widgets/widget_span.dart.lib.js:22805:24)
    at inherited_streamer._InheritedNotifierElement.new.notifyClients (http://localhost:53485/packages/flutter/src/widgets/widget_span.dart.lib.js:23813:61)
    at inherited_streamer._InheritedNotifierElement.new.notifyClients (http://localhost:53485/packages/reactive_forms/src/widgets/inherited_streamer.dart.lib.js:82:13)
    at inherited_streamer._InheritedNotifierElement.new.updated (http://localhost:53485/packages/flutter/src/widgets/widget_span.dart.lib.js:23754:12)
    at inherited_streamer._InheritedNotifierElement.new.updated (http://localhost:53485/packages/flutter/src/widgets/widget_span.dart.lib.js:23809:71)
    at inherited_streamer._InheritedNotifierElement.new.update (http://localhost:53485/packages/flutter/src/widgets/widget_span.dart.lib.js:23748:12)
    at inherited_streamer._InheritedNotifierElement.new.[update] (http://localhost:53485/packages/reactive_forms/src/widgets/inherited_streamer.dart.lib.js:90:20)
    at inherited_streamer._InheritedNotifierElement.new.update$ (http://localhost:53485/packages/reactive_forms/src/widgets/inherited_streamer.dart.lib.js:69:21)
    at update$.next (<anonymous>)
    at http://localhost:53485/dart_sdk.js:37603:33
    at _RootZone.runUnary (http://localhost:53485/dart_sdk.js:37457:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:53485/dart_sdk.js:32441:29)
    at handleValueCallback (http://localhost:53485/dart_sdk.js:32988:49)
    at Function._propagateToListeners (http://localhost:53485/dart_sdk.js:33026:17)
    at async._AsyncCallbackEntry.new.callback (http://localhost:53485/dart_sdk.js:32752:27)
    at Object._microtaskLoop (http://localhost:53485/dart_sdk.js:37718:13)
    at _startMicrotaskLoop (http://localhost:53485/dart_sdk.js:37724:13)
```

Could you please take a look and solve?
Thank you.
Zheng

**Comment by joanpablo** [comment]
Thanks, Zheng, I will test your code and see how to resolve the issue.

As I understand by your code you want to notify the view each time you create a new FromGroup. And that's because the group changes dinamically.

**Comment by zl910627** [comment]
Yes, exactly!
Form fields will be fixed, but `defaultValue` could be changed in dynamically.

**Comment by joanpablo** [comment]
> Yes, exactly!
> Form fields will be fixed, but `defaultValue` could be changed in dynamically.

I will see the problem and I also planing to implement a way to add and remove controls from FormGroup, so you can just have the same group instance but add and remove controls and notify the view to rebuild. What do you think about it?

**Comment by zl910627** [comment]
Umm, two kinds of use case for dynamic form.
- change only `defaultValue` of controls inside `FormGroup`.
in this case, form group will contain fixed controls.
- dynamic add/remove controls.
It means form will contains dynamic controls inside formgroup.

For now, I am saying about first case, but second case is also very useful.
Thank you.

**Comment by zl910627** [comment]
In my case, the best example is master / detail panel.
![image](https://user-images.githubusercontent.com/53897531/91376582-f9d88b00-e84f-11ea-83cf-4f35c1541aad.png)
this is sample for second case.
https://i.stack.imgur.com/oN3Ez.png

**Comment by joanpablo** [comment]
> Umm, two kinds of use case for dynamic form.
> 
> * change only `defaultValue` of controls inside `FormGroup`.
>   in this case, form group will contain fixed controls.
> * dynamic add/remove controls.
>   It means form will contains dynamic controls inside formgroup.
> 
> For now, I am saying about first case, but second case is also very useful.
> Thank you.

So you want to change the "defaultValue" instead of the actual value? In a master/details you change the value of the control to reflect the value of the current selected item. Is that the case or you really need to set the defaultValue (initial value)?

**Comment by joanpablo** [comment]
If you want to set the initial value (defaultValue) then I can implement the actual Angular solution:

In the FormGroup.reset() and FormControl.reset() you can set the initial value (defaultValue) something like:

```dart
final group = FormGroup({
'name': FormControl<String>(
    defaultValue: '',
  ),
});

group.reset({'name': 'someInitialValue'});
```

**Comment by zl910627** [comment]
Your suggest is very neat!

**Comment by zl910627** [comment]
I got your hint, and solved my issue temporary
i,e, whenever item changed, I used to set value by `formGroup.value = ~~~`.
Thank you for your great hint.

But I think this feature is still useful.
Anyway, thank you!

**Comment by zl910627** [comment]
btw, I can't find `reset` method with parameter.
![image](https://user-images.githubusercontent.com/53897531/91418821-4094a800-e885-11ea-8053-d6171db2ca74.png)

> If you want to set the initial value (defaultValue) then I can implement the actual Angular solution:
> 
> In the FormGroup.reset() and FormControl.reset() you can set the initial value (defaultValue) something like:
> 
> ```dart
> final group = FormGroup({
> 'name': FormControl<String>(
>     defaultValue: '',
>   ),
> });
> 
> group.reset({'name': 'someInitialValue'});
> ```

**Comment by joanpablo** [comment]
No it isn't implemented yet, I was just suggesting that implementation as a solution to reset the group's value and set the defaultValue to controls at the same time.

**Comment by zl910627** [comment]
I think reset with new initial values is good mechanism.
It would be very helpful.

**Comment by zl910627** [comment]
I am getting started to love this library than `flutter_form_builder`!

**Comment by joanpablo** [comment]
> I am getting started to love this library than `flutter_form_builder`!

Thanks Zheng,

I'm working on the feature of reset, but I'm also including other features in the same release. I think I will release it by the weekend.

**Comment by joanpablo** [comment]
> I think reset with new initial values is good mechanism.
> It would be very helpful.

Hi Zheng,

I have just release the version 4.0.0 of Reactive Forms.

Now you can reset a FormGroup with initial value for children as follow:

### Resets the values of a group 
```dart
final form = FormGroup({
    'first': FormControl(value: 'first name'),
    'last': FormControl(value: 'last name'),
});

print(form.value);   // output: {first: 'first name', last: 'last name'}

form.reset(value: { 'first': 'John', 'last': 'last name' });

print(form.value); // output: {first: 'John', last: 'last name'}

 ```

**Comment by zl910627** [comment]
I will check and let you know soon!
