### ISSUE TITLE
Error not visible with one form control in formGroup

### ISSUE THREAD

**Issue by techaks** [joanpablo/reactive_forms#40]
Error text Not working when only one form control within formGroup. it only works when you move to another text field.  

```dart

class LoginPage extends StatefulWidget {
  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  final form = FormGroup({
    'mobile':
        FormControl<int>(validators: [Validators.required, Validators.number]),
    // 'mobile1': FormControl(validators: [Validators.required, Validators.email]),
  });

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: BlocProvider<LoginBloc>(
          create: (_) => _loginBloc,
          child: AuthContainer(
            title: 'Its a book\nMarketplace',
            subtitle: 'To get started',
            children: [
              ReactiveForm(
                  formGroup: form,
                  child: Expanded(
                    child: Column(
                      children: [
                        ReactiveInput(
                          formControlName: 'mobile',
                          keyboardType: TextInputType.number,
                          // errorText: state.mobileNumber.error.toString(),
                          maxLength: 10,
                          labelText: 'ENTER YOUR MOBILE NUMBER',
                          hintText: 'Ex. 9999999999 ( without contry code)',
                          prefixIcon: Icons.phone_android,
                          key: const Key('loginForm_mobileInput_textField'),
                          // onChanged: (mobileNumber) => context
                          //     .bloc<LoginBloc>()
                          //     .add(LoginMobileNumberChanged(mobileNumber)),
                        ),
                        // ReactiveInput(
                        //   formControlName: 'mobile1',
                        //   keyboardType: TextInputType.number,
                        //   // errorText: state.mobileNumber.error.toString(),
                        //   maxLength: 10,
                        //   labelText: 'ENTER YOUR MOBILE NUMBER',
                        //   hintText: 'Ex. 9999999999 ( without contry code)',
                        //   prefixIcon: Icons.phone_android,
                        //   key: const Key('loginForm_mobileInputw_textField'),
                        //   // onChanged: (mobileNumber) => context
                        //   //     .bloc<LoginBloc>()
                        //   //     .add(LoginMobileNumberChanged(mobileNumber)),
                        // )
                      ],
                    ),
                  )),
            ],
          )),
    );
  }
}
```

**Comment by joanpablo** [comment]
Hi @techaks,

Reactive Forms by default only show errors when the control is **invalid** and **touched**. A control is **touched** if the user tap on it (the control gets focus) and then remove focus by tapping other control like other for example other text field.

If you only have one control is quite possible that you have no way to remove focus from it, and you will not see the errors, even if the control is invalid.

But if that is your case, fortunately Reactive Forms have something for you. You have two different options to handle this:
1-) Override default behavior on when to show up errors messages.
2-) Mark control as touched programatically.

### Override default behavior
Provide the **showErrors** function in the **ReactiveTextField**:

```dart
ReactiveTextField(
   formControlName: 'mobile',
   showErrors: (control) => control.invalid && control.dirty,
),
```
In the previous example the errors will show up when the control is **invalid** and **dirty**. A dirty control is a control that has change the value in the UI (the user changes the value). This way when the user see the UI by the first time the error is not showwing, but once he start writing, if the control is invalid the errors will come up.

### Mark control as touched programatically.
You can always call **markAsTouched** to mark a control as touched, for example when the user taps a button you can check if the Form is invalid. If the form is invalid then you can call **form.markAllAsTouched()** to mark all child controls as **touched** and in that case the errors will show up.

**Comment by joanpablo** [comment]
Another suggestion @techaks qhen you use 

```dart
FormControl<int>(),
```
you don't need the **Validators.number**, the value is already a number. You can also include some input formatters in the ReactiveTextField to force only numbers like:

```dart
ReactiveTextField(
   formControlName: 'mobile',
   showErrors: (control) => control.invalid && control.dirty,
   inputFormatters: [
      WhitelistingTextInputFormatter.digitsOnly,
   ],
),
```

**Comment by techaks** [comment]
@joanpablo Thanks for your support and suggestion.
