### ISSUE TITLE
ReactiveFormSelector to select/filter rebuilds in widgets

### ISSUE THREAD

**Issue by sagnik-sanyal** [joanpablo/reactive_forms#406]
Hi there is there any existing way to filter rebuilds or select a particular property just like what Provider context.select() or the Selector Widget does ? This will help to cater unecessary rebuilds in widgets where we want to watch only a particular paramter of the FormGroup.

**Comment by joanpablo** [comment]
Hi @sagnik-sanyal  @vasilich6107,

I'm planning to add the listeners (and not builders) as part of the core of Reactive Forms. I remember you talked to me about this in the past @vasilich6107 but at that time I didn't understand a real use case, sorry about that. WHat do you think about it? I will let you know when it is included.  Thanks to both of you.

**Comment by sagnik-sanyal** [comment]
With the latest version of reactive form >= 17.0.0 the reactive_forms_lbc library doesnt work and there is a dependency conflict 
Because reactive_forms_lbc >=2.0.0 depends on reactive_forms ^16.0.0
So we cant use the latest version

**Comment by sagnik-sanyal** [comment]
Is there any way we can use this with the latest version of the plugin, or when we can expect an update of the dependencies of the lbc package ?

**Comment by sagnik-sanyal** [comment]
Fixed with the newer version of lbc package
