### ISSUE TITLE
listen to change of ReactiveDropdownField outside the stepper widget class

### ISSUE THREAD

**Issue by SaddamMohsen** [joanpablo/reactive_forms#407]
Hello, everyone i need help 
I have a multiple reactive_form fields inside a stepper a number of form controls inside step1 and  step2 and step3,
so the first step contains a ReactiveDropdownField with default value as null no item selected 
what i need is disable next button in the stepper when there is no selected item in the dropdown after user select item it should be enabled i know i can to do that when all the steps inside the widget class that contains stepper but the problem is i get the steps from a function outside the widget class so when i select item in dropdown the next button in stepper doesn't enabled because  the change of dropdown item doesn't rebuild the widget immediately 
so i hope you undestand the problem and sorry for my weakness in English language

**Comment by joanpablo** [comment]
Hi @SaddamMohsen

Thanks for the question. Would you mind to elaborate more on the question? Is the Dropdown bound to a control of the FormGroup? Do you have only one FormGroup or a FormGroup for each step?

I also described when to use one FormGroup or several FormGroup within a parent ForGroup in here: [issue 401](https://github.com/joanpablo/reactive_forms/issues/401#issuecomment-1676449312)

**Comment by SaddamMohsen** [comment]
> Hi @SaddamMohsen
> 
> Thanks for the question. Would you mind to elaborate more on the question? Is the Dropdown bound to a control of the FormGroup? Do you have only one FormGroup or a FormGroup for each step?
> 
> I also described when to use one FormGroup or several FormGroup within a parent ForGroup in here: [issue 401](https://github.com/joanpablo/reactive_forms/issues/401#issuecomment-1676449312)

hello, thank you for response and sorry for my late response 
I am using one FormGroup
 i solve it already with ReactiveValueListenableBuilder

**Comment by joanpablo** [comment]
Thanks @SaddamMohsen for letting us know. Then I believe we can close this issue. Don't hesitate to create a new one if you have any other questions.
