### ISSUE TITLE
ReactiveDatePicker 

### ISSUE THREAD

**Issue by bunphithak** [joanpablo/reactive_forms#42]
Hi  i can set format ReactiveDatePicker ? 

ReactiveTextField(
                        formControlName: 'birthday',
                                            decoration: InputDecoration(
                                              border: InputBorder.none,
                                              suffixIcon: ReactiveDatePicker(
                                                formControlName: 'birthday',
                                                firstDate: DateTime(1985),
                                                lastDate: DateTime.now(),
                                                builder:
                                                    (context, picker, child) {
                                                  return IconButton(
                                                    onPressed:
                                                        picker.showPicker,
                                                    icon:
                                                        Icon(Icons.access_time),
                                                  );
                                                },
                                              ),
                                            ),
                                          ),

**Comment by joanpablo** [comment]
Hi @bunphithak,

Thanks for using **Reactive Forms** and for the issue.

You can set a custom **Control Value Accessor** to the ReactiveTextField to format the date time.

[Here](https://github.com/joanpablo/reactive_forms/wiki/Control-Value-Accessors) you can find Documentation about how to create a custom **DateTimeValueAccessor** to accomplish the task.

**Comment by Zacharias02** [comment]
What about in timepicker? @joanpablo

**Comment by joanpablo** [comment]
Hi @Zacharias02,

It's exactly the same. ReactiveTextField by default try to figure out wish Control Value Accessor to use depending of the data type of the control. 

There is a default implementation for DateTime and TimeOfDay: DateTimeValueAccessor and TimeOfDayValueAccessor. This value accessors comes with default formats to String.

I don't want to include intl package into the plug-in in case of incompatibility with others plugins. But you can use it to create you own DateTimeValueAccesor and TimeOfDayValueAccessor, it's quite easy just to override two methods in the class.

[Here](https://github.com/joanpablo/reactive_forms/wiki/Control-Value-Accessors) I describe how to implement a custom value accessor.

**Comment by Zacharias02** [comment]
![Capture](https://user-images.githubusercontent.com/52057825/96953641-28a77080-1524-11eb-9b74-a98a0734bb28.PNG)

**Comment by joanpablo** [comment]
Hi @Zacharias02,

This is the current implementation of TimeOfDayValueAccessor:

```dart
/// Represents a control value accessor that convert between data types
/// [TimeOfDay] and [String].
class TimeOfDayValueAccessor extends ControlValueAccessor<TimeOfDay, String> {
  @override
  String modelToViewValue(TimeOfDay modelValue) {
    return modelValue == null ? '' : '${modelValue.hour}:${modelValue.minute}';
  }

  @override
  TimeOfDay viewToModelValue(String viewValue) {
    if (viewValue == null) {
      return null;
    }

    final parts = viewValue.split(':');
    if (parts.length != 2) {
      return null;
    }

    return TimeOfDay(
      hour: int.parse(parts[0].trim()),
      minute: int.parse(parts[1].trim()),
    );
  }
}
```

As you can see I do a simple **split** and string **concatenations**. But you can use the same **DateFormat** with some workaround to format the time something like:

```dart
String formatTimeOfDay(TimeOfDay time) {
    final now = new DateTime.now();
    final dateTime = DateTime(now.year, now.month, now.day, time.hour, time.minute);
    final format = DateFormat.jm();  //"6:00 AM"
    return format.format(dateTime);
}
```

**Comment by joanpablo** [comment]
I am closing the topic because there are no new comments.

Thank you
