### ISSUE TITLE
ReactiveTextField does not set a default brightness

### ISSUE THREAD

**Issue by chillbrodev** [joanpablo/reactive_forms#434]
While it is nice that the ReactiveTextField supports overriding the keyboardAppearance, the default should not be null and instead match the theme's primaryBrightness. 

Having the default be null, leads to needing to set the keyboardAppearance manually to `MediaQuery.platformBrightnessOf(this)`. The ReactiveTextField should utilize this value by default while still providing the ability to accept an override.

**Comment by joanpablo** [comment]
Hi @chillbrodev,

Thanks for the feedback. I will take a look at this property.

**Comment by joanpablo** [comment]
Hi @chillbrodev,

I have checked the native [TextFormField](https://github.com/flutter/flutter/blob/ef1af02aead6fe2414f3aafa5a61087b610e1332/packages/flutter/lib/src/material/text_form_field.dart#L147C17-L147C35) widget from Flutter Team, and they don't provide a default keyboardAppearance. The `ReactiveTextField` tries to mimic the same experience that anyone can have with native widgets, and add the extra layer of reactivity. Maybe this is something you can suggest to the Flutter Team.

Thanks again for using Reactive Form, and for your feedback.

**Comment by chillbrodev** [comment]
> Hi @chillbrodev,
> 
> I have checked the native [TextFormField](https://github.com/flutter/flutter/blob/ef1af02aead6fe2414f3aafa5a61087b610e1332/packages/flutter/lib/src/material/text_form_field.dart#L147C17-L147C35) widget from Flutter Team, and they don't provide a default keyboardAppearance. The `ReactiveTextField` tries to mimic the same experience that anyone can have with native widgets, and add the extra layer of reactivity. Maybe this is something you can suggest to the Flutter Team.
> 
> Thanks again for using Reactive Form, and for your feedback.

Hey @joanpablo,

That sounds good, I can raise the feedback with the Flutter Team. I'll go ahead and close this.

Thanks for building Reactive Form, my team loves it and we use it on all our projects.
