### ISSUE TITLE
Custom reactive form input builders

### ISSUE THREAD

**Issue by CDDelta** [joanpablo/reactive_forms#45]
Have you explored allowing people to provide their own builders for controls like `ReactiveTextField` as opposed to piping each parameter on `TextField` etc?

The api for a `ReactiveTextField` alternative could look something like this:
```dart
ReactiveTextField(
   formControlName: 'password',
   builder: (context, controller) =>
      TextField(
           controller: controller,
           decoration: decoration: const InputDecoration(labelText: 'Password'),
       ),
),
```

For `ReactiveDropdownField` the api could be:
```dart
 ReactiveDropdownField(
    formControlName: 'privacy',
    decoration: const InputDecoration(labelText: 'Privacy'),
    builder: (context, controller) =>
        DropdownButton<T>(
              focusNode: controller.focusNode,
              items: const [
                 DropdownMenuItem(
                     value: 'public',
                     child: Text('Public'),
                 ),
                 DropdownMenuItem(
                     value: 'private',
                     child: Text('Private'),
                  )
              ],
       ),
), 
```
The `ReactiveDropdownField` example is a bit weird because the `controller` is provided through `focusNode` but it does make everything a lot more flexible. All of this also introduces an extra level of nesting to the widget code but I don't think its too problematic for forms since they are mostly in lists.

I'm guessing it would have to be a breaking change or be implemented as different widgets. An api like this would fix #41 and make this package incredibly powerful and extensible for the future.

**Comment by CDDelta** [comment]
I should've taken a closer look before writing this 😅. `ReactiveTextField` is more complex than a single `controller` binding so a custom builder will probably be too complex. Closing.

**Comment by joanpablo** [comment]
> I should've taken a closer look before writing this 😅. `ReactiveTextField` is more complex than a single `controller` binding so a custom builder will probably be too complex. Closing.

Hi @CDDelta,

I'm planning to release the autofill, but for now you can create your custom reactive textfield (you can copy paste the reactive text field code) and add the missing autofill poperties, while the new release is comming.

Thanks
