### ISSUE TITLE
[label question] Form and FormControl statuses: pristine, dirty

### ISSUE THREAD

**Issue by sokolej79** [joanpablo/reactive_forms#5]
Great package, thanks for your  good work.
Questions:
1.) s there any plan to add  other control statuses for form control and form itself like in Angular: dirty, pristine?
2.) Is it possible to control form individual error messages that will appear only when form field is in focus and  has error,  but not others, other error messages only on submit button? It is little strange use case and behavior, but sometimes customers wants something like this.

**Comment by joanpablo** [comment]
Hi @sokolej79 

About the first question, the answer is Yes. I'm planning to add **dirty** and **pristine** so you can evaluate if the control value has chaged or not. In the [Repo Project](https://github.com/users/joanpablo/projects/1) you can see the features I'm planning to release as soon as posible. You can also read the questions in dev.to https://dev.to/joanpablo/why-use-reactive-forms-in-flutter-ea1 .

About the second question, sorry I didn't understand very well the issue, could you please give an example so I can get a better understanding. 

Thanks for the issue.

**Comment by sokolej79** [comment]
About the second question it's some weired use case from one of our customers. It is not  much important for now.
Thanks for reply.

**Comment by joanpablo** [comment]
Hi @sokolej79 

I'm almost done with the implementation of states dirty and pristine, I'm also included some others minor features, so I soon will release a new version. I steel testing the code.

**Comment by joanpablo** [comment]
Hi @sokolej79 

I've just release a new version with the states 'pristine' and 'dirty'.

Thanks

**Comment by vasilich6107** [comment]
@joanpablo you have 
`String get errorText` which specifies in which cases control should show error message.
Is there a possibility to override that behaviour?

**Comment by joanpablo** [comment]
> @joanpablo you have
> `String get errorText` in `ReactiveFormField` which specifies in which cases control should show error message.
> Is there a possibility to override that behaviour?

Hi @vasilich6107 ,

Thanks for the question. As I understand you want to control whe the error messages show up un the UI?

Right now Reactive Widgets (for example ReactiveTextField) show validation errors when the FormControl is *INVALID* and *TOUCHED* (a control is touched when the user clicks on it and then clicks on other widget: remove the focus on the text field or when you programatically call **control.markAsTouched()**). That's the default behavior.

Do you want to override that default behavior? for example show the errors if the control is INVALID && DIRTY ??

Could you please give an example of what do you want to archive?

**Comment by vasilich6107** [comment]
You are correct. I would like to have an ability to control precisely  when error is shown.
The are varieties of strategies `how to display errors`. The INVALID && DIRTY is a good example.
There could be a case when I want to show errors only on INVALID && TOUCHED && DIRTY.
In any case I would be great to have an ability to override default behaviour.

**Comment by joanpablo** [comment]
> You are correct. I would like to have an ability to control precisely when error is shown.
> The are varieties of strategies `how to display errors`. The INVALID && DIRTY is a good example.
> There could be a case when I want to show errors only on INVALID && TOUCHED && DIRTY.
> In any case I would be great to have an ability to override default behaviour.

I think you are right @vasilich6107, thanks again. Could you please open a new differrent Issue about it? I will comment to you my proposed solution before release it, so we can disscuss about it and find the solution that really fit your needs.

**Comment by vasilich6107** [comment]
read more in #29
