### ISSUE TITLE
Expose focus node of text field

### ISSUE THREAD

**Issue by naamapps** [joanpablo/reactive_forms#54]
Hello again,
I'm trying to add a keyboard action bar with this [package](https://pub.dev/packages/keyboard_actions).
The package is demanding a focus node to know when the text field is focused or not to show the action bar of the keyboard.
I don't think there is a way to get the focus node from the formControl associated with the text field.
And there is no way to add a custom focus node to the reactive text field either.
Please advise,
Thank you

**Comment by joanpablo** [comment]
Hi @naamapps,

You'r right about the fact that there is no way right now to get the focus node of a ReactiveTextField so I will implement a way to provide a FocusNode to ReactiveTextField.

Thanks for the issue

**Comment by kuhnroyal** [comment]
Maybe you can attach a `FocusNodeController` to your `FormControl`.

**Comment by naamapps** [comment]
Hi @joanpablo,
Thanks for the reply!
Looking forward to the new update 👍

**Comment by joanpablo** [comment]
> Maybe you can attach a `FocusNodeController` to your `FormControl`.

That's a good idea, or maybe the FocusNodeController to the ReactiveTextField. I will think what could be the better way, and I will bring a solution in the next couple of days.

Thanks again

**Comment by naamapps** [comment]
Hey @joanpablo,
Is there progress on this?
Don't want to rush you or anything, just want to know how it's doing
Thanks

**Comment by joanpablo** [comment]
Hi @naamapps,

Sorry for not having a solution implemented yet, I've been very busy and this is the must complex issue of all, because it requires a complete new implementations in Reactive Forms, I will do it, but I need some more time. This is an issue that is really important to me.

Sorry the inconvenient.

**Comment by naamapps** [comment]
@joanpablo 
I appreciate it !
Take your time 💯

**Comment by joanpablo** [comment]
Hi @naamapps and @kuhnroyal,

Finally I have release v7.5.0 that include an argument *focusNode* to **ReactiveTextField** that allow to provide a custom **FocusNode** to the widget. 

With this improvement you can provide a custom FocusNode to use in both widgets: ReactiveTextField and KeyboardActionsConfig from this [package](https://pub.dev/packages/keyboard_actions).

Sorry for waiting so long for this release.

**Comment by naamapps** [comment]
Hey @joanpablo, 
Thank you very much for your hard work!
I was hoping that the focus node will be available by a getter in a `FormControl`.
Like any form control has a function `focus()`, I am wondering if it's possible for you to implement a getter (and a setter maybe).
That way,
1. There is no need to manage the focus nodes (disposing)
2. It is the reactive way to personalize the form controls (passing a focusNode to a widget is the flutter way, but I do prefer to do this by code in the business logic)
3. It's also more convenient in my opinion

Either way, thanks a lot!

**Comment by joanpablo** [comment]
Hi @naamapps,

Thanks for your quick reply. You're definitely right and you have proposed a solution that I haven't see before. 
Do you think that exposing the **focusController** of the **FormControl** will resolve your issue?

```dart
final email = form.control('email');

// get the FocusNode of a control
FocusNode emailFocusNode = email.focusController.focusNode;
```

That way, you don't have to create a * StatefulWidget * to create your own * FocusNode * and you don't have to *dispose* it when you dispose the widget. You do not need to set the FocusNode either. Do you think that solution will work well for you?

**Comment by naamapps** [comment]
Hi @joanpablo,
Yes, this is exactly what I meant.
It would be perfect if you could implement this solution as well.
Thanks for your understanding, I really appreciate it 🥇

**Comment by joanpablo** [comment]
I'm working on that right now, let me implement it and see how it looks. I will let you know soon.

**Comment by joanpablo** [comment]
Hi @naamapps,

If I just expose the **focusController** of the **FormControl** class like this:

```dart
/// Gets the focus controller registered to this control.
  FocusController get focusController => _focusController;
```

then you could get the **FocusNode** like this:

```dart
FormControl control = form.control('email');

final focusNode = (control.focusController as FocusNodeController).focusNode
```

That's because **FocusNodeController** is actually the child class that inherited from **FocusController** and uses the FocusNode to maintains sync between control and UI.

**Comment by naamapps** [comment]
@joanpablo 
I think it's fine and manageable enough for me.
Although it's not as minimalistic as this
`final focusNode = control.focusController.focusNode;`

If it's not possible to implement the minimal one, definitely go for this
`final focusNode = (control.focusController as FocusNodeController).focusNode; `

**Comment by joanpablo** [comment]
Well @naamapps, 

The actual implementation separates the Model and UI classes that is why I have two classes the parent and abstract class **FocusControll** that doesn't includes anything of the UI and a child one **FocusNodeController** that is more tight to UI and is the one hold the **FocusNode**.

Even when a I think that separation is a cleaner design, I also think that includes a bit of verbosity. So I think I will mix both classes parent and child and define only one.

Give some more minutes to make some tests and complete the solution.

**Comment by joanpablo** [comment]
@naamapps,

I have just release v7.6.0 in that version you can access **FocusNode** like:

```dart
FormControl email = form.control('email');

// get the FocusNode of a control
FocusNode emailFocusNode = email.focusController.focusNode;
```

Thanks for your patience and all your comments.

Please test the solution with this (plugin)[https://pub.dev/packages/keyboard_actions] and let me know the result as soon as possible, you have been waiting for this issue  to long, and I don't want another day to go by without you having a solution.

**Comment by naamapps** [comment]
@joanpablo 
I thank you for your time, effort and kindness :)
You have done above and beyond my expectations 💯 

It's almost night time at my place so I'll test this tomorrow, and write to you here with my results.

Thanks again!

**Comment by naamapps** [comment]
Hi @joanpablo,
I worked on implementing the focus node with the keyboard actions package and I have stumbled into a problem.
The focus controller is not initialized when creating a new form control like so:

```
FormControl<double> control = FormControl<double>();
FocusNode node = control.focusController.focusNode; // Error, Because the focus controller is null.
```

I need the focus node right away because I want to add a listener to the focus node.

I actually succeeded making this work by creating focus nodes manually and passing them onto the `ReactiveTextField` like so:

```
FocusNode node = FocusNode();
node.addListener(listenerFunc);

disposeLaterList.add(node); // A list of focus nodes to dispose when the widget is disposed

FormGroup group = FormGroup({
   "control": FormControl(),
   "controlFocusNode": node,
});
```
After the init, In the `ReactiveTextField`, I pass the focus node:
```
ReactiveTextField(
   ...
   focusNode: group.control("controlFocusNode").value,
   ...
),
```

It's not ideal but it works. I also created a list of focus nodes and add every node I create to the list.
So when disposing the widgets I go through that list of focus nodes and remove the listener and dispose them.

I am not expecting you to make another solution, because my use case is really unique.
But if you do want to go deeper with this, I'm here to help :)

**Comment by joanpablo** [comment]
Hi @naamapps,

If you want to listen for focus changes, then you just subscribe to **FormControl.focusChanges**, you don't need the FocusNode. Try to use only FocusNode in case some other widget require the FocusNode of the control, but don't use it for listen focus changes, to set focus or remove focus on a control use **FormControl.focus()** or **FormControl.unfocus()**.

**Comment by naamapps** [comment]
@joanpablo ,
Yes you're right!
Didn't notice I have the `focusChanges` property.
Everything is working great now 👍 

By the way, I wanted to use the `ReactiveSwitchListTile` widget, but you didn't export it in the library file `reactive_forms.dart`.
Please export it :)

Thanks for everything!

**Comment by joanpablo** [comment]
Hi @naamapps,

I have release v7.6.2, and now ReactiveSwitchListTile is public. I'm glad that everything else is working great. Thanks.

**Comment by joanpablo** [comment]
Hi @naamapps,

Sorry for the late answer, right now I'm moving from city and I'm still finding accommodation. So I will be busy the next couple of weeks. 

This is maybe because thats the default behavior of TextEditController when setting a text to it. maybe I need to change the way I set the value to TextEditingController of the Input.

Think I should change this in code:
```dart
@override
  void onControlValueChanged(dynamic value) {
    _textController.text = (value == null) ? '' : value.toString();
    super.onControlValueChanged(value);
  }
```

by something similar to this:
```dart
@override
  void onControlValueChanged(dynamic value) {
    String effectiveValue = (value == null) ? '' : value.toString();
    _textController.value = _textController.value.copyWith(
      text: effectiveValue,
      selection: const TextSelection.collapsed(offset: effectiveValue.lenght),
      composing: TextRange.empty,
    ); 
    super.onControlValueChanged(value);
  }
```

**Comment by naamapps** [comment]
Hi @joanpablo,
That seems right.
I will wait for you to implement this.

Take your time, it's not urgent for me.
Thanks 👍

**Comment by joanpablo** [comment]
Hi @naamapps ,

I have release v7.6.3 that solve the issue. Thanks for your patient.

**Comment by naamapps** [comment]
Hey @joanpablo,
It works perfectly, Thank you for your time

**Comment by developerSoluzione1** [comment]
Hi every one I've a got a problem with this functionatlity on `reactive_forms: ^16.1.1` because I cannot get the `FocusNode` of a `ReactiveTextField`. In particluar in a code like this: 

```dart
import ...

class RiversaHuPage extends StatelessWidget {
  RiversaHuPage({Key? key}) : super(key: key);

  final _myForm = FormGroup({
    'first_name': FormControl<String>(),
  });
  final FocusNode _focusFirstName = FocusNode();

  @override
  Widget build(BuildContext context) {
    void testCallback() {
       _myForm.controls.values.forEach((element) {
        FocusNode thisFocusNode = element.focusController.focusNode; //<------ THIS LINE HERE
      });
    }

    return Scaffold(
      appBar: AppBar(...),
      body: ReactiveForm(
        formGroup: _myForm,
        child: Column(
          children: [
            ...,
            ReactiveTextField(
              focusNode: _focusFirstName,
              decoration: InputDecoration(
                suffixIcon: IconButton(
                  onPressed: onPressed,
                  icon: const Icon(Icons.barcode_reader),
                ),
              ),
              formControlName: 'first_name',
            ),
            ...
          ],
        ),
      ),
    );
  }
}
```

throws me an error on the line with: 

```dart
FocusNode thisFocusNode = element.focusController.focusNode; 
```
> The getter 'focusController' isn't defined for the type 'AbstractControl<Object?>'.
Try importing the library that defines 'focusController', correcting the name to the name of an existing getter, or defining a getter or field named 'focusController'.

I think because `element` is of type `AbstractControl<Object?>` and not `FormControl`.

How can I solve the issue?

Thanks
