### ISSUE TITLE
How to ensure the validation is valid?

### ISSUE THREAD

**Issue by rebaz94** [joanpablo/reactive_forms#56]
Hello, Thanks for your library.

I have a problem when validating fields, when using ```ReactiveFormConsumer``` sometime ```formGroup.valid``` return false but the form contains invalid field and also tried to delay checking but also not working.

Is there anyway to wait until all fields is checked again and ensure all fields valid?

please see this
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/11982812/99199114-ed5c3280-27ad-11eb-814b-4bd8bf5cafa1.gif)

Thanks

**Comment by joanpablo** [comment]
Hi @rebaz94,

Thanks for using Reactive Forms and for the issue.

The form has several status

VALID, INVALID, PENDING, DISABLED.

Each time the status of the Form changes, the **ReactiveFormConsumer** widget call the builder function to rebuild UI.

If the Form is PENDING then the **form.valid** returns **false**. So maybe you want to validate with (form.invalid || form.pending) or !form.valid

```dart
ReactiveFormConsumer(
   builder: (context, form, child) {
      return RaisedButton(
         onPressed: form.valid ? _onPressed : null
      );
   }
);

void _onPressed() {}

```

**Comment by rebaz94** [comment]
Hi, Thanks for your quick reply.
I checked the same way you mentioned above but the problem is that before form builded and user tap quickly it will bypass the validation and in the Gif you can see that the error not showing and Button is active. after snackbar shown then error visible.

I want to validate all controls before sending data to server so that catch invalid fields

**Comment by joanpablo** [comment]
Hi @ rebaz94, I am trying to understand the problem, but the gif is not enough to understand it clearly. Please could show me the code you are using to enable/disable the button? Also I would like to see the definition of the Form and also to see if the validations you are doing if you have any custom validation?

**Comment by rebaz94** [comment]
OK, Here How I do it.
I have a simple FormControl just for showing error message like ```final logoInput = FormControl(touched: true)```
```dart
 FormGroup(
        {
          'logoInput': logoInput,
       },
        validators: [
          ValidatorsX.imagesOperator(
            'logoInput',
            operatorFn: () {
              final images = logoManager?.images;
              if (images == null) return true;
              return images.isNotEmpty && images.first.value.image.isNotEmpty;
            },
          )
        ],
      ),
```

Validator
```dart
class ImageOperatorValidator extends Validator<dynamic> {
  ImageOperatorValidator(this.controllerName, {@required this.operatorFn, this.operatorName});

  String controllerName;
  bool Function() operatorFn;
  String operatorName;

  @override
  Map<String, dynamic> validate(AbstractControl<dynamic> control) {
    final form = control as FormGroup;
    if (form == null) {
      return null;
    }

    final controllerInput = form.control(controllerName);
    final bool imagesValid = operatorFn();

    if (!imagesValid) {
      controllerInput.setErrors({operatorName ?? ValidationMessageX.imagesOperator: true});
    } else {
      controllerInput.setErrors({});
    }
    controllerInput.markAsTouched();
    return null;
  }
}
```

validator function is basically provide a function and check image is valid or not. 
the **logoManager** inside the function is just a ```ChangeNotifier``` which contain the images data and manage adding or removing data, whenever any operation happen it will call the provided controller which in case is ```logoInput``` like that
```dart
void removeImageForIndex(int index) {
    images.removeAt(index);
    notifyListeners();
    notifyFormControl();
}

void notifyFormControl(){
    formControl.updateValueAndValidity();
 }
```

And I have custom widget that listen to ```logoInput``` and shows error if any
```dart
ReactiveValueListenableBuilder(
  formControlName: controllerName,
  builder: (context, control, child) {
    String msg = '';
    if (control.hasErrors) {
      msg = validationMessages?.containsKey(control.errors.keys.first) == true
          ? validationMessages[control.errors.keys.first]
          : control.errors.keys.first;
    }
    return Text(
      msg,
      style: _errorStyle(context),
      maxLines: errorMaxLine,
      overflow: TextOverflow.ellipsis,
    );
  },
)
```

and finally the update button
```dart
ReactiveFormConsumer(                                                                  
  builder: (context, form, child) {                                                    
    final formInvalid =  form.invalid || form.pending;                                 
    return RaisedButton(                                                               
      onPressed: isLoading || formInvalid ? null : () => _defaultUpdateButton(context),
      child: Text('Update'),                                                           
    );                                                                                 
  },                                                                                   
);                                                                                     
```

Note: This way It work, but sometime rebuilding button is delayed and if user tap quickly, it will submit invalid form.

**Comment by joanpablo** [comment]
Hi @rebaz94,

I see two possible solutions to your issue:
1. Not using FormControl to just show messages.
2. Use the FormControl to actually hold the logo image and put required validator and implement a Custom Reactive Widget that binds to that FormControl. You can use a FormArray to create a collection of FormControls that hold logo images. So the FormArray will be valid if all FormControls are valid (all controls must has image data).

1-)
You don't necessary need to create a **FormGroup** or use a **ReactiveFormConsumer** if you are using the FormControl just to show errors (I will even think in not using Reactive Forms at all for that use case). But have you tried  to use a **ReactiveValueListenableBuilder** to enable/disable the button instead of using a FormGroup and ReactiveFormConsumer?

```dart
ReactiveStatusListenableBuilder(
  formControl: logoInput,
  builder: (context, control, child) {                                                              
    return RaisedButton(                                                               
      onPressed: control.valid ? () => _defaultUpdateButton(context) : null,
      child: Text('Update'),                                                           
    );                                                                                 
  },                                                                                   
); 
```

I will recommend not using FormControl or FormGroup just to show errors, but using normal ValueNotifier and ValueListenableBuilder.

2-)
If I understood your issue you have a collection of logo images, and all logo require to have a picture data (image is required).
For example:

```dart
final form = fb.group({
   'logos': fb.array<Uint8List>(),
});

FormArray<Uint8List> get logos => this.form.control('logos');

void addImage(Uint8List imageData) {
   this.logos.add(fb.control<Uint8List>(imageData, [Validators.required]))
}

void removeImage(FormControl<Uint8List> control) {
   this.logos.remove(control);
}
```

```dart
ReactiveStatusListenableBuilder(
  // binds to FormArray
  formControl: logos,
  builder: (context, array, child) {                                 
    return RaisedButton(                                     
      onPressed: array.valid ? () => _defaultUpdateButton(context) : null,
      child: Text('Update'),
    );                                                                                 
  },                                                                                   
); 
```

Create a custom Widget that binds to the control (maybe a control that picks files from file system or network)

**Comment by rebaz94** [comment]
Thanks for your detailed explanation.

I will try to use second solution but I don't thinks its the main issue because in the example above is a custom widget but the problem also exist for ```ReactiveTextField```.

I will let you know if thats works.
Thanks again

**Comment by joanpablo** [comment]
Thanks @rebaz94, please let me know as soon as possible if you solve the issue with second solution, I'll be very glad to help you.

**Comment by rebaz94** [comment]
Hi @joanpablo ,

I implemented using ```FormArray``` and work perfectly even if you click on Update button before ui shows error and later form return invalid which is what I want.

I will be great if we can able to force validation for a ```FormGroup``` and wait until finished, something like this
```dart
await formGroup.forceRerunValidation();
final valid = formGroup.valid;
```
I know maybe its expensive but it will ensure that all data is correct.

Thanks so much

**Comment by joanpablo** [comment]
Hi @rebaz94, 

Thanks to you for your comments, I'm glad that the solution works for you. 
There's another way to listen for changes in a Form: **form.statusChanges**.

Thanks again.
