### ISSUE TITLE
ReactiveFormField  - Field value type - dynamic

### ISSUE THREAD

**Issue by vasilich6107** [joanpablo/reactive_forms#59]
Hi! Thanks for you work.

I'm building my first `ReactiveFormField` for custom checkbox and I have a question.
Why do the `field.value` type is `dynamic` despite we pass generic type? - https://tppr.me/OuXcZ

I tried to change in `reactive_form_field.dart`

`dynamic get value => this.valueAccessor.modelToViewValue(this.control.value);`
to
`T get value => this.valueAccessor.modelToViewValue(this.control.value);`

Seems to work fine)
All tests passing.

**Comment by joanpablo** [comment]
Hi @vasilich6107,

Thanks for your kind words!

Well, the **get value** in **ReactiveFormFieldState** returns the value in *view data type*, that means it is not the same data type of the **FormControl**.  If you use the expression

```dart
T get value => this.valueAccessor.modelToViewValue(this.control.value);
```

you are assuming that the data type that is returned by the **value accessor** is the same of the **FormControl** and that is not always true. For Example if you bind a **ReactiveTextField** with a FormControl of type **int** then ReactiveFormFieldState.value must return a String and not and int. All ReactiveTextField value accessor should return String.

**Comment by joanpablo** [comment]
Close the issue due not recent activity.
