### ISSUE TITLE
Add a validator that matches a parameter

### ISSUE THREAD

**Issue by rlazom** [joanpablo/reactive_forms#6]
Hey men, I love your plugin,
It is with me in all projects since I started using it, really good job, you nailed it.

I want if possible for you to add another validator that matches a given parameter.

For example: 
Validators.isEqualTo(true)
Validators.isEqualTo('String Field Value')
etc

Thanks in advance

**Comment by joanpablo** [comment]
Hi @rlazom,

Thanks for the issue, I've already implemented a validator fro this task called **Validators.equals()**

Here is an example of usage (this is actually a unit test in Reactive Forms):

```dart
// Given: an invalid control
final control = FormControl<double>(
    value: 0.0,
    validators: [Validators.equals(20.0)],
);

// Expect: control is invalid
expect(control.valid, false);

// When: change the value to true
control.value = 20.0;

// Then: control is valid
expect(control.valid, true);
```

**Comment by joanpablo** [comment]
> Hey men, I love your plugin,
> It is with me in all projects since I started using it, really good job, you nailed it.
> 
> I want if possible for you to add another validator that matches a given parameter.
> 
> For example:
> Validators.isEqualTo(true)
> Validators.isEqualTo('String Field Value')
> etc
> 
> Thanks in advance

Hi @rlazom,

I've just release a new version of Reactive Form with new validators
