### ISSUE TITLE
Complex ValidationMessage use

### ISSUE THREAD

**Issue by gmcdowell** [joanpablo/reactive_forms#60]
It would be great to see documentation on how to make use of a Validation Error where more that just the `key: true` is returned, in a ReactiveTextField for example

I see that you are returning these sub-maps in several validators, e.g. **MaxValidator**

`
ValidationMessage.max: {
  'max': max,
  'actual': control.value,
},
`

There does not appear to be any examples in your tests.

Really enjoying using the package overall.

**Comment by joanpablo** [comment]
Hi @gmcdowell,

Thanks for your comments, I'm glad you enjoy the use of Reactive Forms.

Here is a real example usage:

```dart
ReactiveTextField(
   formControl: viewModel(context).amount,
   keyboardType: TextInputType.numberWithOptions(),
   inputFormatters: [ FilteringTextInputFormatter.allow(RegExp(r'\d+')) ],
   decoration: InputDecoration(
      labelText: context.localizations.remittanceAmountHint,
      hintText: '0.00',
      prefixText: '\$ ',
  ),
  validationMessages: (control) => {
     ValidationMessage.required: context.localizations.requiredFieldErrorMessage,
     if (control.hasError('range'))
        'range': context.localizations.remittanceAmountRangeValidatorMessage(control.getError('range')['min'],
                          control.getError('range')['max'],
                        ),
                    },
                  ),
```

**Comment by gmcdowell** [comment]
Thanks heaps ;)
