### ISSUE TITLE
Add a multiselect

### ISSUE THREAD

**Issue by victorcatn** [joanpablo/reactive_forms#64]
Hello,
It will be great if there is easy way to create multiselects that receive a list of items and keep a FormArray of selected items, like the one for emails in samples/array_sample.dart. The ReactiveDropdownField widget already receives a list of items but only keeps one value.
This package is very useful, thanks.

**Comment by joanpablo** [comment]
Hi @victorcatn,

Because Flutter doesn't include a native multi-select widget, Reactive Forms doesn't include it either. But I'm sure that implement it should be very easy as a [Custom Reactive Widget](https://github.com/joanpablo/reactive_forms/wiki/Custom-Reactive-Widgets). You can implement it from scratch or maybe reuse some community plugin and convert it to a reactive widget like in this [post](https://dev.to/joanpablo/star-rating-with-flutter-reactive-forms-2d52).

I'm planning to create a new Flutter plugin Reactive Forms Widgets in a future, that include some widgets commonly used and implemented by the community like multi-select widget and many others but in a reactive way using Reactive Forms. Maybe you can help me with some contributions when I release it. But meanwhile I guess you will have to implement a custom reactive widget.

If you have any doubt about Custom Reactive Forms, don't hesitate to write me again, I will be very glad to help you.

Que tengas una excelente noche. Estaré dispuesto a ayudarte si lo necesitas.

**Comment by victorcatn** [comment]
Thank you @joanpablo 
I tried to make a reactive widget of `ReactiveMultiSelectDialogField` from the `reactive_forms: ^7.6.2` package but I found a problem, `MultiSelectChipDisplay`  `onTap` callback can update the `ReactiveFormFieldState` but at the rebuild, the changes are not seen, that does not happen with the `onConfirm` of `MultiSelectDialogField`. I think It has to do with what those widgets keep an internal state.
This is my code:

```dart
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:multi_select_flutter/multi_select_flutter.dart';
import 'package:reactive_forms/reactive_forms.dart';

void main() {
  runApp(MaterialApp(
    home: MyApp(),
  ));
}

class MyApp extends StatelessWidget {
  final control = FormControl<List<String>>();
  final items = ["a", "b", "c"];
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text("test")),
      body: Center(
        child: ReactiveMultiSelectDialogField<String>(
          formControl: control,
          items: items.map((e) => MultiSelectItem(e, e)).toList(),
        ),
      ),
    );
  }
}

class ReactiveMultiSelectDialogField<V> extends ReactiveFormField<List<V>> {
  final List<MultiSelectItem<V>> items;
  final Text buttonText;
  ReactiveMultiSelectDialogField({
    String formControlName,
    FormControl formControl,
    @required this.items,
    this.buttonText,
  }) : super(
            formControlName: formControlName,
            formControl: formControl,
            builder: (ReactiveFormFieldState<List<V>> field) {
              print(field.value);// looks like the new state is given

              return MultiSelectDialogField<V>(
                
                buttonText: buttonText,
                items: items,
                initialValue: field.value,
                listType: MultiSelectListType.CHIP,
                onConfirm: (values) {
                  field.didChange(values);
                },
                chipDisplay: MultiSelectChipDisplay<V>(
                  items: items,
                  onTap: (dynamic value) {
                    return field.didChange(
                      // The rebuild does not reflect this new value 😢
                      (field.value as List<V>)
                          .where((e) => e != value)
                          .toList(),
                    );
                  },
                ),
              );
            });

  @override
  ReactiveFormFieldState<List<V>> createState() =>
      ReactiveFormFieldState<List<V>>();
}

```

**Comment by joanpablo** [comment]
Hi @victorcatn,

Sorry for the late answare right now I'm moving from country so I will need some time to relocation. I will analize your code as soon as possible.

Thanks.

**Comment by victorcatn** [comment]
Hi,

Don't worry, you already made a very good work with this package. It helped me a lot building an app with dynamic and complex forms.
I already analyzed my issue and it happens because the widget from `multi_select_flutter` has its own state, that `ReactiveFormField` can't change once created. A workaround may be create a key for each rebuild of the stateful widget, that way the old state is deleted and the widget rebuilds with the new values given by `ReactiveFormField`. Maybe this is not the best solution. What do you think?

Good luck with your relocation.

**Comment by joanpablo** [comment]
Hi @victorcatn,

Thanks for your kind words. Yes it's definitely that the widget you are using is stateful and maybe it can have some issue with resetting initial value. It's always better to use stateless widget with Reactive Forms, but is not mandatory there are some widgets within Reactive Forms like ReactiveTextField that is stateful and also in this [post](https://dev.to/joanpablo/star-rating-with-flutter-reactive-forms-2d52) I show how to create a Star Rating Bar using a stateful widget, and everything works fine.

**Comment by daniel-lucas-silva** [comment]
> Thank you @joanpablo
> I tried to make a reactive widget of `ReactiveMultiSelectDialogField` from the `multi_select_flutter: ^3.1.6` package but I found a problem, `MultiSelectChipDisplay` `onTap` callback can update the `ReactiveFormFieldState` but at the rebuild, the changes are not seen, that does not happen with the `onConfirm` of `MultiSelectDialogField`. I think It has to do with what those widgets keep an internal state.
> This is my code:
> 
> ```dart
> import 'package:flutter/foundation.dart';
> import 'package:flutter/material.dart';
> import 'package:multi_select_flutter/multi_select_flutter.dart';
> import 'package:reactive_forms/reactive_forms.dart';
> 
> void main() {
>   runApp(MaterialApp(
>     home: MyApp(),
>   ));
> }
> 
> class MyApp extends StatelessWidget {
>   final control = FormControl<List<String>>();
>   final items = ["a", "b", "c"];
>   @override
>   Widget build(BuildContext context) {
>     return Scaffold(
>       appBar: AppBar(title: Text("test")),
>       body: Center(
>         child: ReactiveMultiSelectDialogField<String>(
>           formControl: control,
>           items: items.map((e) => MultiSelectItem(e, e)).toList(),
>         ),
>       ),
>     );
>   }
> }
> 
> class ReactiveMultiSelectDialogField<V> extends ReactiveFormField<List<V>> {
>   final List<MultiSelectItem<V>> items;
>   final Text buttonText;
>   ReactiveMultiSelectDialogField({
>     String formControlName,
>     FormControl formControl,
>     @required this.items,
>     this.buttonText,
>   }) : super(
>             formControlName: formControlName,
>             formControl: formControl,
>             builder: (ReactiveFormFieldState<List<V>> field) {
>               print(field.value);// looks like the new state is given
> 
>               return MultiSelectDialogField<V>(
>                 
>                 buttonText: buttonText,
>                 items: items,
>                 initialValue: field.value, // It ignores changes in the rebuild
>                 listType: MultiSelectListType.CHIP,
>                 onConfirm: (values) {
>                   field.didChange(values);
>                 },
>                 chipDisplay: MultiSelectChipDisplay<V>(
>                   items: items,
>                   onTap: (dynamic value) {
>                     return field.didChange(
>                       // The rebuild does not reflect this new value 😢
>                       (field.value as List<V>)
>                           .where((e) => e != value)
>                           .toList(),
>                     );
>                   },
>                 ),
>               );
>             });
> 
>   @override
>   ReactiveFormFieldState<List<V>> createState() =>
>       ReactiveFormFieldState<List<V>>();
> }
> ```



i solve this problem wrapping the result in a new List
for example 

```dart
   field.didChange(List.from(value))
```

**Comment by joanpablo** [comment]
Hi @daniel-lucas-silva,

It seems to be an issue with the **MultiSelectChipDisplay**. The reason why calling: **field.didChange(value)** is not triggered a value change is because there is no value change at all, which means you are passing the same value that the control has in its previous state.

There is a statement in **ControlValueAccessor** line 52 that prevents unnecessary event triggers when the value of current state is the same of previous state:

```dart
final modelValue = this.viewToModelValue(viewValue);
if (_control.value != modelValue) {
  _control.markAsDirty(emitEvent: false);
  _control.updateValue(modelValue);
} else {
  _viewToModelChange = false;
}
```

This statement works: **field.didChange(List.from(value))** because you are creating a new instance of a **List** each time you call **field.didChange**, so you are passing a new value each time.

So again It seems to be an issue with the **MultiSelectChipDisplay**.
