### ISSUE TITLE
Formly and dynamic forms

### ISSUE THREAD

**Issue by mitjaj76** [joanpablo/reactive_forms#65]
Reactive forms is really great package. 
Thanks to author.
This package is inspired by Angular reactive forms, very similiar.
It would be even better if there would be another package that would wrap reactive forms package and fields to formly package as angular formly.
Formly is great for dynamic forms from server or json and on my opinion it would be high compatible with reactive forms package.

**Comment by joanpablo** [comment]
Hi @mitjaj76,

Thanks for your kind words and for using Reactive Forms. Definitely Formly Angular is a great library. I will be very pleased if someone else implements a library like Formly Angular for Flutter based on Flutter Reactive Forms, that would by great. I still need to add some pending features to Reactive Forms and I would like to implement some extra widgets (this is another plugin with some extra widgets based on Flutter Reactive Forms).

**Comment by joanpablo** [comment]
I will close the issue for now, don't hesitate to reopen or open a new one for some issue.
