### ISSUE TITLE
valid state always false if I set field value manually via assignment

### ISSUE THREAD

**Issue by bandirsen** [joanpablo/reactive_forms#7]
I'm separate Model and UI class using Provider mechanism, everything works fine, all my Model variable accessed normally, but sometime we need to set the form field value manually like this:

```
//Model class
final FormGroup myForm = FormGroup({
    'lon': FormControl<double>(validators: [Validators.required]),
    'lat': FormControl<double>(validators: [Validators.required]),
  });

void setAddress(LatLng location) {
   myForm.value["lat"] = locaction.latittude;
   myForm.value["lon"] = location.longitude;
}

//UI class
onMapClicked: (location) => Provider.of<MyModel>(context).setAddress(location);
```

myForm variable in model class was updated when map is clicked, I can confirm it by using following test in my model class, however but the form it self is not valid.
```
//Model class
print(myForm.value) 
print(myForm.errors)
print(myForm.valid)
```
which resulting this in console
```
{lon: 6.57397257427442, lat: -4.879758560733243}   <-- values are sets
{lon: {required: true}, lat: {required: true}}  <-- why this still in required state ?
false  
```

Am I missing something here ?  why the form is invalid, even all field values are set ?

**Comment by bandirsen** [comment]
Oh shame on me, I was totally wrong.
The right way to manually set form field value is with fb.control("fieldName").value assignment

I put the example here, in case someone need it.
```
myForm.control("field_name").value = xxxx

```

I close this issue.

Thank you

**Comment by joanpablo** [comment]
> Oh shame on me, I was totally wrong.
> The right way to manually set form field value is with fb.control("fieldName").value assignment
> 
> I put the example here, in case someone need it.
> 
> ```
> myForm.control("field_name").value = xxxx
> ```
> 
> I close this issue.
> 
> Thank you

Hi @bandirsen,

Thanks for the issue.
You can update controls value in two different ways:

```dart
final form = fb.group({'name': ''});

// sets value directly to the control
form.control('name').value = 'john doe';

// sets value to control by setting value to the form
form.value = { 'name': 'little john' };
```

Both methods do the same.
