### ISSUE TITLE
How to disable a ReactiveTextField

### ISSUE THREAD

**Issue by Darksoulsong** [joanpablo/reactive_forms#74]
I'm playing around with it, and I'm liking it so far. But I can't figure how to enable/disable a field, it seems the enable prop native to TextFormFields is not available on ReactTextField. Is this doable?

**Comment by joanpablo** [comment]
Hi @Darksoulsong,

Thanks for the issue and for using Reactive Forms. 

To disable a ReactiveTextField just disable the control bound to the widget:

```dart
control.markAsDisabled();
```

And the widget will get disabled.

**Comment by Inmer** [comment]
Thanks, @joanpablo I was having a hard time to get the values from a disabled component, **form.rawValue** is what I needed. But I just want to mention that that property is not on the documentation on pub.dev, if this question would not have been here, I fear I would not have found the answer. Just one more thing and sorry if is out of topic, but I made you a question here https://dev.to/joanpablo/star-rating-with-flutter-reactive-forms-2d52 and still don't know how to do it.

**Comment by joanpablo** [comment]
Hi @Inmer,

You are right the property **form.rawValue** is not in the README.md or Wiki. Sorry for late answer in dev.to. Please let me know if I answered your question.

Thanks

**Comment by Darksoulsong** [comment]
I ended up using "readOnly", it fits perfectly my needs. Thank you and congrats on the awesome lib. It's a lifesaver.

**Comment by joanpablo** [comment]
> I ended up using "readOnly", it fits perfectly my needs. Thank you and congrats on the awesome lib. It's a lifesaver.

Thanks for your kind words @Darksoulsong.
