### ISSUE TITLE
Dynamically add and remove validator in a specific formControl

### ISSUE THREAD

**Issue by Zacharias02** [joanpablo/reactive_forms#77]
May I ask how to dynamically add and remove validator in a specific formControl.

For example,

[imgur.com/a/ERz7wGa](https://imgur.com/a/ERz7wGa)

**Comment by joanpablo** [comment]
Hi @Zacharias02,

This is not implemented yet. But you can use a **FormGroup** validator that checks the value of control *Country* and set *required* or not to the control *County*.

**Comment by joanpablo** [comment]
I closed the issue for now. Don't hesitate to reopen it or open a new one.

**Comment by fchiumeo** [comment]
I just created the PR #109
