### ISSUE TITLE
FormGroup in FormArray

### ISSUE THREAD

**Issue by angeloo** [joanpablo/reactive_forms#8]
Hey!

first of all, great work!

I've got something I'm not enable to do.

I want to use a FormGroup in a FormArray.

I define my form like that:

```dart
final form = FormGroup({
    'ea_id_objekt': FormControl(),
    'bat_id_objekt': FormControl(),
    'atoms': FormArray([
      FormGroup({
        'locationTypeId': FormControl()
      })
    ]),
    'userId': FormControl(),
    'plannedAt': FormControl(),
    'visitedAt': FormControl(),
    'statusId': FormControl(),
  });
```

How can I access the locationTypeId formControl? (formControlName?)

```dart
ReactiveDropdownField<int>(
    formControlName: 'atom.locationTypeId', // <----- HERE
    decoration: InputDecoration(labelText: 'Type de localisation'),
    items: locationTypesItems
),
```

Thanks!

**Comment by joanpablo** [comment]
Hi @angeloo 

Thanks for the issue, I have already implemented a solution for that situations. I'll release it in v5.0.0. I'm planing to release it by the end of next week. That solution is already implemented but I'm working in other features that I want to release in the same version. You can check the README.md in brach develop, there I've added some documentation about *arrays* of *groups*.

I've also include docs about access nested properties like **formControlName: 'atoms.0.locationTypeId'** (it is already implemented in develop branch but will be available in v5.0.0 by the end of the next week).

So I can sugest you a workaroung for doing that, until next release is available.

You can wrap the **ReactiveDropdownField** into a **ReactiveFormArray** something linke:

```dart
ReactiveFormArray<bool>(
  formArrayName: 'atoms',
  builder: (context, formArray, child) {
    return Column(
      children: formArray.controls
        .map((control) => control as FormGroup)
        .map((form) => ReactiveDropdownField<int>(
          formControl: form.control('locationTypeId'),
          decoration: InputDecoration(
            labelText: 'Type de localisation',
          ),
          items: locationTypesItems,
        )).toList(),
    );
  },
),
```

**Comment by angeloo** [comment]
Hi @joanpablo 

You rock! 

I'll have a test with the work around and then check the new possibility with v5.0.0.

BTW, I have many properties in atoms (That was only 1 for the code "example"), but thanks for the suggestion.
In fact I want a form which represents a three levels one to many relationship DB.
`items (1)->(n) atoms (1)-> (n) medias`

Thanks!

**Comment by joanpablo** [comment]
Thanks again @angeloo 

Please let me know if the solution I proposed to you fits your requirements.

**Comment by joanpablo** [comment]
> Hi @joanpablo
> 
> You rock!
> 
> I'll have a test with the work around and then check the new possibility with v5.0.0.
> 
> BTW, I have many properties in atoms (That was only 1 for the code "example"), but thanks for the suggestion.
> In fact I want a form which represents a three levels one to many relationship DB.
> `items (1)->(n) atoms (1)-> (n) medias`
> 
> Thanks!

Hi @angeloo 

I've just release a new version of Reactive Forms.

**Comment by angeloo** [comment]
Hi @joanpablo, 

I tried with the first solution, but all the fields where like binded (same values).

So i tried to use the develop branch and it works. (now I'll switch to the last stable version)

Thanks!

**Comment by joanpablo** [comment]
Hi @angeloo,

Thanks, I'm glad you have the solution. 
If you find another issue please let me know.
