### ISSUE TITLE
PatternValidator does not allow to specify regex parameters

### ISSUE THREAD

**Issue by vasilich6107** [joanpablo/reactive_forms#80]
RegExp class has some valuable parameters to specify

`multiLine`
`caseSensitive`
`unicode`
`dotAll`

Current implementation of `PatternValidator` does not allow to alter them

**Comment by joanpablo** [comment]
Yes @vasilich6107 you are right, let me think about the best solution.

**Comment by joanpablo** [comment]
Well, actually RegExp implements Pattern so it's possible to pass a Regex. Let me try some unit test and see what happen

**Comment by joanpablo** [comment]
I have two solutions:
A-) Change **Validators.pattern(Pattern)** contract for **Validators.pattern(RegEx)**. That represents a Breaking change.
B-) Add a new method **Validators.patternRegex(Regex)** and change **Validators.pattern(String)**. This doesn't represent a breaking change but adds an additional method.

What do you think?

**Comment by vasilich6107** [comment]
I choose B with marking `Validators.pattern` as deprecated with link to this topic in description.
We can delete deprecated items lately

**Comment by vasilich6107** [comment]
Consider renaming Validators.patternRegex to Validators.regex

**Comment by joanpablo** [comment]
Hi @vasilich6107,

I have just released v8.0.2.

Now you can pass an instance of a RegExp to the **Validators.pattern**. Please check if this resolves the issue.

**Comment by joanpablo** [comment]
Hi @vasilich6107,

I will close this issue for now. Please don't hesitate to open it again if you find some problems.
