### ISSUE TITLE
Access raw value in validator

### ISSUE THREAD

**Issue by kuhnroyal** [joanpablo/reactive_forms#82]
I have a `FormControl<double>` but the input field is obviously a text field.
I want to validate that the String matches a pattern before it is converted by the value accessor.

Is that possible somehow? Couldn't find a way.

**Comment by joanpablo** [comment]
Hi @kuhnroyal,

Could you please give an example of what you are trying to achieve? A use case to better understand the issue.

Thanks

**Comment by kuhnroyal** [comment]
I tried to add a `Validator.pattern()` to my `FormControl<double>` to validate a maximum amount of fraction digits and correct decimal/group separator depending on the users locale.
But the pattern validator calls `control.value.toString()` in this case and the value is already the converted double value and does never match the pattern.
I basically want to run the pattern validator on the raw input value before the control value accessor converted it to double.

Or find another way to solve this.

**Comment by joanpablo** [comment]
Hi @kuhnroyal,

Maybe with a full use case example, I will get the complete picture. Because maybe you just need to implement an  [TextInputFormatter](https://api.flutter.dev/flutter/services/TextInputFormatter-class.html) to correct decimal/group separator depending on the users locale.

**Comment by kuhnroyal** [comment]
I will try that and get back to you.

**Comment by joanpablo** [comment]
@kuhnroyal  another solution is to implement a custom [ControlValueAccessor](https://github.com/joanpablo/reactive_forms/wiki/Control-Value-Accessors) that correct String value before convert to double.

**Comment by kuhnroyal** [comment]
Yes, I already have a localized double accessor that uses `intl.NumberFormat` to parse.
I have now used a `FilteringTextInputFormatter.allow(RegExp(...))` and that works for my specific use case. Thanks for your advice!

I still think that any `ReactiveTextFormField` should work with `Validators.pattern` even if the backing ` FormControl<T>` is not `String` - for this to work, the validator needs access to the unprocessed input value.
But feel free to close this if you don't see this need.

**Comment by joanpablo** [comment]
Hi @kuhnroyal,

Sorry for the delay in the answer. I'm glad that you solved the issue. Please don't hesitate to reopen the issue or open a new one.
