### ISSUE TITLE
Can't use flutter_localizations with reactive_forms because of outdated intl

### ISSUE THREAD

**Issue by rbozan** [joanpablo/reactive_forms#84]
```
Because reactive_forms >=8.0.0 depends on intl ^0.16.1 and every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, reactive_forms >=8.0.0 is incompatible with flutter_localizations from sdk.

So, because student_client depends on both flutter_localizations any from sdk and reactive_forms ^8.0.1, version solving failed.
pub get failed (1; So, because student_client depends on both flutter_localizations any from sdk and reactive_forms ^8.0.1, version solving failed.
```

Using following override in your own pubspec.yaml seems to work for now:
```yml
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
```

**Comment by joanpablo** [comment]
Hi @rbozan,

Thanks for using Reactive Forms and for the issue. Yes that's the solution when an intl conflict is present. It's explained [here](https://github.com/joanpablo/reactive_forms#minimum-requirements) in de documentation. You have to override dependencies the **pubspec.yaml** of your project.

Is That the solution you did????

**Comment by rbozan** [comment]
Ah yes I did that and it works, but I think after some time it's nice to have this package also have updated `intl` so we don't have to override it ourselves. You can close this issue if you want :)

**Comment by joanpablo** [comment]
Hi @rbozan,

You're definitely right, I will update **intl** in the next release. Thanks.

**Comment by joanpablo** [comment]
Hi @rbozan,

I'm planning to create a pre-release version with null safety, and in that version, I will introduce the prerelease version of intl: ^0.17.0-nullsafety.x

**Comment by rbozan** [comment]
Thank you very much
