### ISSUE TITLE
How can I add validation error messages for ReactiveCheckbox as like ReactiveTextField

### ISSUE THREAD

**Issue by Skanda-Kumar** [joanpablo/reactive_forms#87]
ReactiveTextField(
      style: TextStyle(fontSize: 25),                
      formControl: store.fg.controls['name'],
      validationMessages: (control) => {
        ValidationMessage.required: 'Name Is Required',
        ValidationMessage.minLength: 'Min Length is 2'
      },
    )

**Comment by joanpablo** [comment]
Hi @Skanda-Kumar,

Thanks for using Reactive Forms and for the issue. Well actually in the native Flutter Checkbox there is no Validator function, which means that Flutter doesn't validate or show error messages for checkboxes. 

On the other hand, Reactive Forms does allow you to validate a form control bound to a Checkbox (for example **Validators.requiredTrue**). But is up to you to show the message of the error. You can use for example a **ReactiveStatusListenableBuilder** for listening when the control becomes **invalid** and show the message.

```dart
ReactiveStatusListenableBuilder(
  builder: (BuildContext context, AbstractControl<dynamic> control, Widget child) {
    return control.invalid ? Text("required true") : Container();
  },
),
```

Could you please give me a use case example so I can better understand what you are trying to achieve?

Thanks.

**Comment by Skanda-Kumar** [comment]
Thanks for your quick response!
 
My requirement is like if you have a **I Agree** check box and in the formgroup if you give the formcontrol as required, then it should show the error message as like how it is showing for text field as shown in the image below on clicking the submit button.

![image](https://user-images.githubusercontent.com/61859748/106735675-8b87c800-663a-11eb-9f31-72c2478a7f83.png)

How can I achieve this ?

**Comment by joanpablo** [comment]
Hi @Skanda-Kumar,

you can use the **ReactiveStatusListenableBuilder** to show/hide the error like this:

```dart
ReactiveStatusListenableBuilder(
  formControlName: 'control',
  builder: (BuildContext context, AbstractControl<dynamic> control, Widget child) {
    // if control is invalid and is touched then show the error
    return control.invalid && control.touched ? Text("required true") : Container();
  },
),
```

and in the onPressed of the button:

```dart
RaisedButton(
  child: Text('SUBMIT'),
  onPressed: () {
    if (form.valid) {
      //do something
    } else {
      // this will marks all children as touched and the errors will show up
      form.markAllAsTouched();
    }
  },
),
```

Of course, there is a second solution that is to disabled the Button and enabled just when the form is valid.

Please let me know if this answers responses your question.

**Comment by Skanda-Kumar** [comment]
This works for me. Thanks !!
