### ISSUE TITLE
Platform Specific Widget 

### ISSUE THREAD

**Issue by uhisdu** [joanpablo/reactive_forms#88]
how we can implement platform specific controls in reactive forms? Is it automattically handling the platform specific widgets ?

**Comment by joanpablo** [comment]
Hi @uhisdu,

Actually, the native Reactive Forms widgets use Material. You can easily create custom widgets wrapping Cupertino widgets or using a plugin that handles automatically the platform-specific widget.

[Here](https://github.com/joanpablo/reactive_forms/wiki/Custom-Reactive-Widgets) you can find how to create Custom Reactive widgets.
