### ISSUE TITLE
How do I test for a property in ReactiveTextField?

### ISSUE THREAD

**Issue by pbhuvanesh** [joanpablo/reactive_forms#89]
Hello, 
I would like to test the reactivetextfield for `autocorrect` property and several other properties using testWidget under flutter test. Could someone please tell me how to achieve this?
```

final phoneNumberFinder = find.byType(ReactiveTextField);
      final ReactiveTextField formfield =
          await tester.widget<ReactiveTextField>(find.byType(ReactiveTextField));
```
using this formfield I do not find any property called autocorrect or any other reactiveform property. 

Thanks!

**Comment by joanpablo** [comment]
Hi @pbhuvanesh,

Try using TextField instead of **ReactiveTextField**. ReactiveTextField is just a wrapper to TextField so you can  search this last one directly:

```dart
final phoneNumberFinder = find.byType(TextField);
```

**Comment by pbhuvanesh** [comment]
> Hi @pbhuvanesh,
> 
> Try using TextField instead of **ReactiveTextField**. ReactiveTextField is just a wrapper to TextField so you can search this last one directly:
> 
> ```dart
> final phoneNumberFinder = find.byType(TextField);
> ```

Thank you @joanpablo  this worked.
