### ISSUE TITLE
Implementing Groups of Groups 😁

### ISSUE THREAD

**Issue by huephase** [joanpablo/reactive_forms#91]
Its not clear how to render Groups of Groups:

`final form = FormGroup({
  'personal': FormGroup({
    'name': FormControl<String>(validators: [Validators.required]),
    'email': FormControl<String>(validators: [Validators.required]),
  }),
  'phone': FormGroup({
    'phoneNumber': FormControl<String>(validators: [Validators.required]),
    'countryIso': FormControl<String>(validators: [Validators.required]),
  }),
  'address': FormGroup({
    'street': FormControl<String>(validators: [Validators.required]),
    'city': FormControl<String>(validators: [Validators.required]),
    'zip': FormControl<String>(validators: [Validators.required]),
  }),
});`

Im using 

`ReactiveTextField(formControlName: 'personal', ),`

but throws error:

`Expected a value of type 'FormControl<dynamic>', but got one of type 'FormGroup'`

**Comment by joanpablo** [comment]
Hi @huephase,

Thanks for using Reactive Forms and for the issue.

As I see in your example, you have a several child groups of the principal *form*, that's good. Now you probably want to bind a **ReactiveTextField** to the *name* of the person, so you can use the sintax: 

```dart
ReactiveTextField(formControlName: 'personal.name', ),
```

The above code is in case you have for example a **ReactiveForm** (or a ReactiveFormBuilder) and as a child you have this **ReactiveTextField**:

```dart
ReactiveForm(
   formGroup: form,
   child: Column(children: [
      ReactiveTextField(
         formControlName: 'personal.name', 
      ),
   ]),
),
```

But you can also have nested **ReactiveForm** widgets:

```dart
ReactiveForm(
   formGroup: form,
   child: Column(children: [
      ReactiveForm(
         formGroup: form.control('personal') as FormGroup,
            child: Column(children: [
               ReactiveTextField(
                  formControlName: 'name', 
               ),
            ]),
         ),
   ]),
),
```

**Comment by huephase** [comment]
Excellent! much appreciated!
