### ISSUE TITLE
Dynamic Form Group

### ISSUE THREAD

**Issue by Mhamza-MM** [joanpablo/reactive_forms#93]
Is it possible to create FormGroup with the desired number of fields?
Like creating FormGroup from a JSON that returns an Array?

**Comment by joanpablo** [comment]
Hi @Mhamza-MM,

Thanks for the issue, but could you please give me an example (a use case) so I can better understand what you are trying to achieve?

**Comment by Mhamza-MM** [comment]
I have a sample JSON

{
    "display": "form",
    "data": [
        {
            "field_name": "name"
        },
        {
            "field_name": "email"
        },
        {
            "field_name": "password"
        }
    ]
}

now the number of Objects in "data" will be the number of fields in FormGroup. These can be dynamic. I want to show widgets (text fields for now) according to the response.
I tried putting FormArray in FormGroup but it is not working and showing this error

type 'FormArray<dynamic>' is not a subtype of type 'FormControl<dynamic>'

**Comment by joanpablo** [comment]
Hi @Mhamza-MM,

If you want to add controls dynamically to a FormGroup, you can try **FormGroup.addAll** method:

```dart
final form = FormGroup({});

f.addAll({
      'name': fb.control<String>(''),
      'email': fb.control<String>(''),
    });
```

Please let me know if this approach fits your needs.

**Comment by Mhamza-MM** [comment]
That solved my current problem. I am closing this issue now but I might reopen the issue if the topic of the problem is similar. I am learning the reactive forms and your repository is great. I wanted to know one more thing.
How can we separate different form groups? Is there any identifier so that I can separate fields from their type for better testing?
