### ISSUE TITLE
Problem using dependency_overrides intl: ^0.16.1 => conflict with "easy_localization" package (3.0.0)

### ISSUE THREAD

**Issue by jbt-cii** [joanpablo/reactive_forms#99]
Hello,

Thank you for your great package.

I am connected ton flutter "channel master" and I was very happy to use your package because it seems very more simple to interact with form fields than "TextFormField".

To make translations I need to use the great "easy_localization" package but only the version 3.0.0 of this package works with flutter "channel master" with "intl: ^0.17.0", so as it is explained in the documentation I implemented:

```
dependency_overrides:
  intl: ^0.16.1

```

But when I try to compile my application, it fails because of the usage of "intl: ^0.16.1" in "dependency_overrides" (in the  "pubspec.yaml" file) generate an error for "easy_localization" package:

```
Launching lib/main.dart on sdk gphone arm64 in debug mode...
lib/main.dart:1
/opt/homebrew/Caskroom/flutter/1.22.6/flutter/.pub-cache/hosted/pub.dartlang.org/easy_localization-3.0.0/lib/easy_localization.dart:7:1: Error: Null safe libraries are not allowed to export declarations from of opt-out libraries.
export 'package:intl/intl.dart';
^
...

```

So as I really need "easy_localization" package I have to rollback my development and try to do the job with "TextFormField" :-(
Except if it exists a workaround solution?

Here is the result of the command "flutter doctor -v":

[✓] Flutter (Channel master, 1.27.0-5.0.pre.18, on macOS 11.2.1 20D74 darwin-arm, locale fr-FR)
    • Flutter version 1.27.0-5.0.pre.18 at /opt/homebrew/Caskroom/flutter/1.22.6/flutter
    • Framework revision 50897c98fc (2 weeks ago), 2021-02-16 20:13:53 -0800
    • Engine revision 9bcb3bfb0e
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/myhome/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • sdk gphone arm64 (mobile) • emulator-5554 • android-arm64  • Android 11 (API 30) (emulator)
    • Chrome (web)              • chrome        • web-javascript • Google Chrome 88.0.4324.192

• No issues found!

**Comment by joanpablo** [comment]
Hi @jbt-cii,

Thanks for trying to use Reactive Forms and for the issue. Have you tried to use:

```yaml
dependency_overrides:
  intl: ^0.17.0
```

Please try setting 0.17.0 instead of 0.16.1 and let me know the results.

Best regards

**Comment by jbt-cii** [comment]
Yes it works now!
I can execute my application.
I will be able to continue my dev and my tests tomorrow.
Thanks a lot!
